// Generated by scripts/mirror from shadcn base-nova/alert-dialog. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { afterEach, describe, expect, it } from 'vitest'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogMedia,
  AlertDialogOverlay,
  AlertDialogPortal,
  AlertDialogTitle,
  AlertDialogTrigger,
} from './AlertDialog'
import styles from './AlertDialog.module.scss'

// React's useId output (_r_1_, and :r1: or «r1» before React 19.1), which
// differs between renders; Base UI puts it in ids and data-id.
const USE_ID = /_r_[0-9a-z]+_|:r[0-9a-z]+:|«r[0-9a-z]+»/g

afterEach(cleanup)

describe('AlertDialog', () => {
  it('renders its children', () => {
    cleanup()
    render(
      <AlertDialog>
        <i data-testid="child" />
      </AlertDialog>,
    )
    expect(document.querySelector('[data-testid="child"]')).not.toBeNull()
  })
})

function renderAlertDialogTrigger(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogTrigger>, unknown>> = {},
) {
  cleanup()
  render(
    <AlertDialog defaultOpen>
      <AlertDialogTrigger data-subject {...(props as ComponentProps<typeof AlertDialogTrigger>)} />
    </AlertDialog>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="alert-dialog-trigger"]')
}

describe('AlertDialogTrigger', () => {
  it('appends a consumer className last', () => {
    renderAlertDialogTrigger({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <AlertDialog defaultOpen>
        <AlertDialogTrigger data-subject>AlertDialogTrigger</AlertDialogTrigger>
      </AlertDialog>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderAlertDialogPortal(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogPortal>, unknown>> = {},
) {
  cleanup()
  render(
    <AlertDialog defaultOpen>
      <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogPortal
          data-subject
          {...({ keepMounted: true, children: 'AlertDialogPortal', ...props } as ComponentProps<
            typeof AlertDialogPortal
          >)}
        />
      </AlertDialogContent>
    </AlertDialog>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="alert-dialog-portal"]')
}

describe('AlertDialogPortal', () => {
  it('appends a consumer className last', () => {
    renderAlertDialogPortal({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderAlertDialogOverlay(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogOverlay>, unknown>> = {},
) {
  cleanup()
  render(
    <AlertDialog defaultOpen>
      <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogPortal keepMounted>
          <AlertDialogOverlay
            data-subject
            {...(props as ComponentProps<typeof AlertDialogOverlay>)}
          />
        </AlertDialogPortal>
      </AlertDialogContent>
    </AlertDialog>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="alert-dialog-overlay"]')
}

function classesOfAlertDialogOverlay(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogOverlay>, unknown>> = {},
) {
  return renderAlertDialogOverlay(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('AlertDialogOverlay', () => {
  it('renders [data-slot="alert-dialog-overlay"] with its classes', () => {
    expect(classesOfAlertDialogOverlay()).toEqual(
      expect.arrayContaining([styles.alertDialogOverlay]),
    )
  })

  it('appends a consumer className last', () => {
    renderAlertDialogOverlay({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderAlertDialogContent(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogContent>, unknown>> = {},
) {
  cleanup()
  render(
    <AlertDialog defaultOpen>
      <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
      <AlertDialogContent
        data-subject
        {...({ children: 'AlertDialogContent', ...props } as ComponentProps<
          typeof AlertDialogContent
        >)}
      />
    </AlertDialog>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="alert-dialog-content"]')
}

function classesOfAlertDialogContent(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogContent>, unknown>> = {},
) {
  return renderAlertDialogContent(props)?.getAttribute('class')?.split(' ') ?? []
}

function htmlOfAlertDialogContent(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogContent>, unknown>> = {},
) {
  renderAlertDialogContent(props)
  return document.body.innerHTML.replace(USE_ID, '')
}

function attributesOfAlertDialogContent(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogContent>, unknown>> = {},
) {
  const element = renderAlertDialogContent(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('AlertDialogContent', () => {
  it('renders [data-slot="alert-dialog-content"] with its classes', () => {
    expect(classesOfAlertDialogContent()).toEqual(
      expect.arrayContaining([styles.alertDialogContent]),
    )
  })

  it('renders the same with size="default" passed explicitly', () => {
    expect(attributesOfAlertDialogContent({ size: 'default' })).toEqual(
      attributesOfAlertDialogContent(),
    )
  })

  it('renders differently with size="sm"', () => {
    expect(htmlOfAlertDialogContent({ size: 'sm' })).not.toBe(htmlOfAlertDialogContent())
  })

  it('appends a consumer className last', () => {
    renderAlertDialogContent({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <AlertDialog defaultOpen>
        <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
        <AlertDialogContent data-subject size="sm">
          AlertDialogContent
        </AlertDialogContent>
      </AlertDialog>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderAlertDialogHeader(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogHeader>, unknown>> = {},
) {
  cleanup()
  render(
    <AlertDialog defaultOpen>
      <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogHeader
          data-subject
          {...({ children: 'AlertDialogHeader', ...props } as ComponentProps<
            typeof AlertDialogHeader
          >)}
        />
      </AlertDialogContent>
    </AlertDialog>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="alert-dialog-header"]')
}

function classesOfAlertDialogHeader(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogHeader>, unknown>> = {},
) {
  return renderAlertDialogHeader(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('AlertDialogHeader', () => {
  it('renders [data-slot="alert-dialog-header"] with its classes', () => {
    expect(classesOfAlertDialogHeader()).toEqual(expect.arrayContaining([styles.alertDialogHeader]))
  })

  it('appends a consumer className last', () => {
    renderAlertDialogHeader({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <AlertDialog defaultOpen>
        <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
        <AlertDialogContent size="sm">
          <AlertDialogHeader data-subject>AlertDialogHeader</AlertDialogHeader>
        </AlertDialogContent>
      </AlertDialog>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderAlertDialogFooter(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogFooter>, unknown>> = {},
) {
  cleanup()
  render(
    <AlertDialog defaultOpen>
      <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogFooter
          data-subject
          {...({ children: 'AlertDialogFooter', ...props } as ComponentProps<
            typeof AlertDialogFooter
          >)}
        />
      </AlertDialogContent>
    </AlertDialog>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="alert-dialog-footer"]')
}

function classesOfAlertDialogFooter(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogFooter>, unknown>> = {},
) {
  return renderAlertDialogFooter(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('AlertDialogFooter', () => {
  it('renders [data-slot="alert-dialog-footer"] with its classes', () => {
    expect(classesOfAlertDialogFooter()).toEqual(expect.arrayContaining([styles.alertDialogFooter]))
  })

  it('appends a consumer className last', () => {
    renderAlertDialogFooter({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <AlertDialog defaultOpen>
        <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
        <AlertDialogContent size="sm">
          <AlertDialogFooter data-subject>AlertDialogFooter</AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderAlertDialogMedia(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogMedia>, unknown>> = {},
) {
  cleanup()
  render(
    <AlertDialog defaultOpen>
      <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogMedia
            data-subject
            {...({ children: 'AlertDialogMedia', ...props } as ComponentProps<
              typeof AlertDialogMedia
            >)}
          />
        </AlertDialogHeader>
      </AlertDialogContent>
    </AlertDialog>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="alert-dialog-media"]')
}

function classesOfAlertDialogMedia(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogMedia>, unknown>> = {},
) {
  return renderAlertDialogMedia(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('AlertDialogMedia', () => {
  it('renders [data-slot="alert-dialog-media"] with its classes', () => {
    expect(classesOfAlertDialogMedia()).toEqual(expect.arrayContaining([styles.alertDialogMedia]))
  })

  it('appends a consumer className last', () => {
    renderAlertDialogMedia({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <AlertDialog defaultOpen>
        <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
        <AlertDialogContent size="sm">
          <AlertDialogHeader>
            <AlertDialogMedia data-subject>AlertDialogMedia</AlertDialogMedia>
          </AlertDialogHeader>
        </AlertDialogContent>
      </AlertDialog>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderAlertDialogTitle(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogTitle>, unknown>> = {},
) {
  cleanup()
  render(
    <AlertDialog defaultOpen>
      <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle
            data-subject
            {...({ children: 'AlertDialogTitle', ...props } as ComponentProps<
              typeof AlertDialogTitle
            >)}
          />
        </AlertDialogHeader>
      </AlertDialogContent>
    </AlertDialog>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="alert-dialog-title"]')
}

function classesOfAlertDialogTitle(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogTitle>, unknown>> = {},
) {
  return renderAlertDialogTitle(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('AlertDialogTitle', () => {
  it('renders [data-slot="alert-dialog-title"] with its classes', () => {
    expect(classesOfAlertDialogTitle()).toEqual(expect.arrayContaining([styles.alertDialogTitle]))
  })

  it('appends a consumer className last', () => {
    renderAlertDialogTitle({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <AlertDialog defaultOpen>
        <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
        <AlertDialogContent size="sm">
          <AlertDialogHeader>
            <AlertDialogTitle data-subject>AlertDialogTitle</AlertDialogTitle>
          </AlertDialogHeader>
        </AlertDialogContent>
      </AlertDialog>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderAlertDialogDescription(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogDescription>, unknown>> = {},
) {
  cleanup()
  render(
    <AlertDialog defaultOpen>
      <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogDescription
            data-subject
            {...({ children: 'AlertDialogDescription', ...props } as ComponentProps<
              typeof AlertDialogDescription
            >)}
          />
        </AlertDialogHeader>
      </AlertDialogContent>
    </AlertDialog>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="alert-dialog-description"]')
}

function classesOfAlertDialogDescription(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogDescription>, unknown>> = {},
) {
  return renderAlertDialogDescription(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('AlertDialogDescription', () => {
  it('renders [data-slot="alert-dialog-description"] with its classes', () => {
    expect(classesOfAlertDialogDescription()).toEqual(
      expect.arrayContaining([styles.alertDialogDescription]),
    )
  })

  it('appends a consumer className last', () => {
    renderAlertDialogDescription({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <AlertDialog defaultOpen>
        <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
        <AlertDialogContent size="sm">
          <AlertDialogHeader>
            <AlertDialogDescription data-subject>AlertDialogDescription</AlertDialogDescription>
          </AlertDialogHeader>
        </AlertDialogContent>
      </AlertDialog>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderAlertDialogAction(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogAction>, unknown>> = {},
) {
  cleanup()
  render(
    <AlertDialog defaultOpen>
      <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogFooter>
          <AlertDialogAction
            data-subject
            {...({ children: 'AlertDialogAction', ...props } as ComponentProps<
              typeof AlertDialogAction
            >)}
          />
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="alert-dialog-action"]')
}

describe('AlertDialogAction', () => {
  it('appends a consumer className last', () => {
    renderAlertDialogAction({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <AlertDialog defaultOpen>
        <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
        <AlertDialogContent size="sm">
          <AlertDialogFooter>
            <AlertDialogAction data-subject>AlertDialogAction</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <AlertDialog defaultOpen>
        <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
        <AlertDialogContent size="sm">
          <AlertDialogFooter>
            <AlertDialogAction data-subject variant="destructive">
              AlertDialogAction
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderAlertDialogCancel(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogCancel>, unknown>> = {},
) {
  cleanup()
  render(
    <AlertDialog defaultOpen>
      <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogFooter>
          <AlertDialogCancel
            data-subject
            {...({ children: 'AlertDialogCancel', ...props } as ComponentProps<
              typeof AlertDialogCancel
            >)}
          />
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="alert-dialog-cancel"]')
}

function attributesOfAlertDialogCancel(
  props: Partial<Record<keyof ComponentProps<typeof AlertDialogCancel>, unknown>> = {},
) {
  const element = renderAlertDialogCancel(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('AlertDialogCancel', () => {
  it('renders the same with variant="outline" passed explicitly', () => {
    expect(attributesOfAlertDialogCancel({ variant: 'outline' })).toEqual(
      attributesOfAlertDialogCancel(),
    )
  })

  it('renders the same with size="default" passed explicitly', () => {
    expect(attributesOfAlertDialogCancel({ size: 'default' })).toEqual(
      attributesOfAlertDialogCancel(),
    )
  })

  it('appends a consumer className last', () => {
    renderAlertDialogCancel({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <AlertDialog defaultOpen>
        <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
        <AlertDialogContent size="sm">
          <AlertDialogFooter>
            <AlertDialogCancel data-subject>AlertDialogCancel</AlertDialogCancel>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <AlertDialog defaultOpen>
        <AlertDialogTrigger>AlertDialogTrigger</AlertDialogTrigger>
        <AlertDialogContent size="sm">
          <AlertDialogFooter>
            <AlertDialogCancel data-subject variant="ghost">
              AlertDialogCancel
            </AlertDialogCancel>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})
