// Generated by scripts/mirror from shadcn base-nova/kbd. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { afterEach, describe, expect, it } from 'vitest'
import { Kbd, KbdGroup } from './Kbd'
import styles from './Kbd.module.scss'

afterEach(cleanup)

function renderKbd(props: Partial<Record<keyof ComponentProps<typeof Kbd>, unknown>> = {}) {
  cleanup()
  render(<Kbd data-subject {...({ children: 'Kbd', ...props } as ComponentProps<typeof Kbd>)} />)
  return document.querySelector('[data-subject]')?.closest('[data-slot="kbd"]')
}

function classesOfKbd(props: Partial<Record<keyof ComponentProps<typeof Kbd>, unknown>> = {}) {
  return renderKbd(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('Kbd', () => {
  it('renders [data-slot="kbd"] with its classes', () => {
    expect(classesOfKbd()).toEqual(expect.arrayContaining([styles.kbd]))
  })

  it('appends a consumer className last', () => {
    renderKbd({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <KbdGroup>
        <Kbd data-subject>Kbd</Kbd>
      </KbdGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderKbdGroup(
  props: Partial<Record<keyof ComponentProps<typeof KbdGroup>, unknown>> = {},
) {
  cleanup()
  render(
    <KbdGroup
      data-subject
      {...({ children: 'KbdGroup', ...props } as ComponentProps<typeof KbdGroup>)}
    />,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="kbd-group"]')
}

function classesOfKbdGroup(
  props: Partial<Record<keyof ComponentProps<typeof KbdGroup>, unknown>> = {},
) {
  return renderKbdGroup(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('KbdGroup', () => {
  it('renders [data-slot="kbd-group"] with its classes', () => {
    expect(classesOfKbdGroup()).toEqual(expect.arrayContaining([styles.kbdGroup]))
  })

  it('appends a consumer className last', () => {
    renderKbdGroup({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})
