// Generated by scripts/mirror from shadcn base-mira/field. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { afterEach, describe, expect, it } from 'vitest'
import {
  Field,
  FieldContent,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
  FieldLegend,
  FieldSeparator,
  FieldSet,
  FieldTitle,
} from './Field'
import styles from './Field.module.scss'

// React's useId output (_r_1_, and :r1: or «r1» before React 19.1), which
// differs between renders; Base UI puts it in ids and data-id.
const USE_ID = /_r_[0-9a-z]+_|:r[0-9a-z]+:|«r[0-9a-z]+»/g

afterEach(cleanup)

function renderFieldSet(
  props: Partial<Record<keyof ComponentProps<typeof FieldSet>, unknown>> = {},
) {
  cleanup()
  render(
    <FieldGroup>
      <FieldSet
        data-subject
        {...({ children: 'FieldSet', ...props } as ComponentProps<typeof FieldSet>)}
      />
    </FieldGroup>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="field-set"]')
}

function classesOfFieldSet(
  props: Partial<Record<keyof ComponentProps<typeof FieldSet>, unknown>> = {},
) {
  return renderFieldSet(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('FieldSet', () => {
  it('renders [data-slot="field-set"] with its classes', () => {
    expect(classesOfFieldSet()).toEqual(expect.arrayContaining([styles.fieldSet]))
  })

  it('appends a consumer className last', () => {
    renderFieldSet({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderFieldLegend(
  props: Partial<Record<keyof ComponentProps<typeof FieldLegend>, unknown>> = {},
) {
  cleanup()
  render(
    <FieldGroup>
      <FieldSet>
        <FieldLegend
          data-subject
          {...({ children: 'FieldLegend', ...props } as ComponentProps<typeof FieldLegend>)}
        />
      </FieldSet>
    </FieldGroup>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="field-legend"]')
}

function classesOfFieldLegend(
  props: Partial<Record<keyof ComponentProps<typeof FieldLegend>, unknown>> = {},
) {
  return renderFieldLegend(props)?.getAttribute('class')?.split(' ') ?? []
}

function htmlOfFieldLegend(
  props: Partial<Record<keyof ComponentProps<typeof FieldLegend>, unknown>> = {},
) {
  renderFieldLegend(props)
  return document.body.innerHTML.replace(USE_ID, '')
}

function attributesOfFieldLegend(
  props: Partial<Record<keyof ComponentProps<typeof FieldLegend>, unknown>> = {},
) {
  const element = renderFieldLegend(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('FieldLegend', () => {
  it('renders [data-slot="field-legend"] with its classes', () => {
    expect(classesOfFieldLegend()).toEqual(expect.arrayContaining([styles.fieldLegend]))
  })

  it('renders the same with variant="legend" passed explicitly', () => {
    expect(attributesOfFieldLegend({ variant: 'legend' })).toEqual(attributesOfFieldLegend())
  })

  it('renders differently with variant="label"', () => {
    expect(htmlOfFieldLegend({ variant: 'label' })).not.toBe(htmlOfFieldLegend())
  })

  it('appends a consumer className last', () => {
    renderFieldLegend({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderFieldGroup(
  props: Partial<Record<keyof ComponentProps<typeof FieldGroup>, unknown>> = {},
) {
  cleanup()
  render(
    <FieldGroup
      data-subject
      {...({ children: 'FieldGroup', ...props } as ComponentProps<typeof FieldGroup>)}
    />,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="field-group"]')
}

function classesOfFieldGroup(
  props: Partial<Record<keyof ComponentProps<typeof FieldGroup>, unknown>> = {},
) {
  return renderFieldGroup(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('FieldGroup', () => {
  it('renders [data-slot="field-group"] with its classes', () => {
    expect(classesOfFieldGroup()).toEqual(expect.arrayContaining([styles.fieldGroup]))
  })

  it('appends a consumer className last', () => {
    renderFieldGroup({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <FieldGroup data-subject>FieldGroup</FieldGroup>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderField(props: Partial<Record<keyof ComponentProps<typeof Field>, unknown>> = {}) {
  cleanup()
  render(
    <FieldGroup>
      <Field data-subject {...({ children: 'Field', ...props } as ComponentProps<typeof Field>)} />
    </FieldGroup>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="field"]')
}

function classesOfField(props: Partial<Record<keyof ComponentProps<typeof Field>, unknown>> = {}) {
  return renderField(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('Field', () => {
  it('renders [data-slot="field"] with its classes', () => {
    expect(classesOfField()).toEqual(
      expect.arrayContaining([styles.field, styles.orientationVertical]),
    )
  })

  it.each([
    ['vertical', styles.orientationVertical],
    ['horizontal', styles.orientationHorizontal],
    ['responsive', styles.orientationResponsive],
  ] as const)('orientation %s applies its class', (value, className) => {
    expect(classesOfField({ orientation: value })).toContain(className)
  })

  it('applies no group class for a null group', () => {
    const classes = classesOfField({ orientation: null })
    expect(classes).toContain(styles.field)
    for (const className of [
      styles.orientationVertical,
      styles.orientationHorizontal,
      styles.orientationResponsive,
    ]) {
      expect(classes).not.toContain(className)
    }
  })

  it('appends a consumer className last', () => {
    renderField({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-subject data-invalid>
          Field
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-subject data-disabled>
          Field
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-subject orientation="horizontal">
          Field
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldLabel htmlFor="checkbox-with-title">
          <Field data-subject orientation="horizontal">
            Field
          </Field>
        </FieldLabel>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <FieldGroup>
            <Field data-subject orientation="horizontal">
              Field
            </Field>
          </FieldGroup>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (7)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-subject data-invalid orientation="horizontal">
          Field
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (8)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-subject data-disabled orientation="horizontal">
          Field
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (9)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <Field data-subject orientation="horizontal">
            Field
          </Field>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (10)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldLabel htmlFor="radio-title-1">
          <Field data-subject orientation="horizontal">
            Field
          </Field>
        </FieldLabel>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (11)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <Field data-subject data-invalid orientation="horizontal">
            Field
          </Field>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (12)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <Field data-subject data-disabled orientation="horizontal">
            Field
          </Field>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (13)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <Field data-subject orientation="horizontal">
            Field
          </Field>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderFieldContent(
  props: Partial<Record<keyof ComponentProps<typeof FieldContent>, unknown>> = {},
) {
  cleanup()
  render(
    <FieldGroup>
      <Field orientation="horizontal">
        <FieldContent
          data-subject
          {...({ children: 'FieldContent', ...props } as ComponentProps<typeof FieldContent>)}
        />
      </Field>
    </FieldGroup>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="field-content"]')
}

function classesOfFieldContent(
  props: Partial<Record<keyof ComponentProps<typeof FieldContent>, unknown>> = {},
) {
  return renderFieldContent(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('FieldContent', () => {
  it('renders [data-slot="field-content"] with its classes', () => {
    expect(classesOfFieldContent()).toEqual(expect.arrayContaining([styles.fieldContent]))
  })

  it('appends a consumer className last', () => {
    renderFieldContent({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldLabel htmlFor="checkbox-with-title">
          <Field orientation="horizontal">
            <FieldContent data-subject>FieldContent</FieldContent>
          </Field>
        </FieldLabel>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldLabel htmlFor="radio-title-1">
          <Field orientation="horizontal">
            <FieldContent data-subject>FieldContent</FieldContent>
          </Field>
        </FieldLabel>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-invalid orientation="horizontal">
          <FieldContent data-subject>FieldContent</FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-disabled orientation="horizontal">
          <FieldContent data-subject>FieldContent</FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderFieldLabel(
  props: Partial<Record<keyof ComponentProps<typeof FieldLabel>, unknown>> = {},
) {
  cleanup()
  render(
    <FieldGroup>
      <Field>
        <FieldLabel
          data-subject
          {...({ htmlFor: 'input-basic', children: 'FieldLabel', ...props } as ComponentProps<
            typeof FieldLabel
          >)}
        />
      </Field>
    </FieldGroup>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="field-label"]')
}

function classesOfFieldLabel(
  props: Partial<Record<keyof ComponentProps<typeof FieldLabel>, unknown>> = {},
) {
  return renderFieldLabel(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('FieldLabel', () => {
  it('renders [data-slot="field-label"] with its classes', () => {
    expect(classesOfFieldLabel()).toEqual(expect.arrayContaining([styles.fieldLabel]))
  })

  it('appends a consumer className last', () => {
    renderFieldLabel({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="input-with-desc">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="input-desc-first">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="input-required">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="input-disabled">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="input-badge">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (7)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-invalid>
          <FieldLabel data-subject htmlFor="input-invalid">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (8)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-disabled>
          <FieldLabel data-subject htmlFor="input-disabled-field">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (9)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="textarea-basic">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (10)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="textarea-comments">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (11)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="textarea-bio">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (12)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="textarea-desc-after">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (13)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-invalid>
          <FieldLabel data-subject htmlFor="textarea-invalid">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (14)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-disabled>
          <FieldLabel data-subject htmlFor="textarea-disabled-field">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (15)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="select-basic">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (16)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="select-country">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (17)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="select-timezone">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (18)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-invalid>
          <FieldLabel data-subject htmlFor="select-invalid">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (19)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-disabled>
          <FieldLabel data-subject htmlFor="select-disabled-field">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (20)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="native-select-basic">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (21)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="native-select-country">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (22)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="native-select-timezone">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (23)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="native-select-grouped">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (24)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-invalid>
          <FieldLabel data-subject htmlFor="native-select-invalid">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (25)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-disabled>
          <FieldLabel data-subject htmlFor="native-select-disabled-field">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (26)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field orientation="horizontal">
          <FieldLabel data-subject htmlFor="checkbox-basic">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (27)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field orientation="horizontal">
          <FieldLabel data-subject htmlFor="checkbox-right">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (28)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field orientation="horizontal">
          <FieldContent>
            <FieldLabel data-subject htmlFor="checkbox-with-desc">
              FieldLabel
            </FieldLabel>
          </FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (29)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldLabel data-subject htmlFor="checkbox-with-title">
          FieldLabel
        </FieldLabel>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (30)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <FieldGroup>
            <Field orientation="horizontal">
              <FieldLabel data-subject htmlFor="pref-dark">
                FieldLabel
              </FieldLabel>
            </Field>
          </FieldGroup>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (31)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <FieldGroup>
            <Field orientation="horizontal">
              <FieldLabel data-subject htmlFor="pref-compact">
                FieldLabel
              </FieldLabel>
            </Field>
          </FieldGroup>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (32)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <FieldGroup>
            <Field orientation="horizontal">
              <FieldLabel data-subject htmlFor="pref-notifications">
                FieldLabel
              </FieldLabel>
            </Field>
          </FieldGroup>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (33)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-invalid orientation="horizontal">
          <FieldLabel data-subject htmlFor="checkbox-invalid">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (34)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-disabled orientation="horizontal">
          <FieldLabel data-subject htmlFor="checkbox-disabled-field">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (35)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <Field orientation="horizontal">
            <FieldLabel data-subject htmlFor="radio-free">
              FieldLabel
            </FieldLabel>
          </Field>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (36)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <Field orientation="horizontal">
            <FieldLabel data-subject htmlFor="radio-pro">
              FieldLabel
            </FieldLabel>
          </Field>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (37)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <Field orientation="horizontal">
            <FieldLabel data-subject htmlFor="radio-enterprise">
              FieldLabel
            </FieldLabel>
          </Field>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (38)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <Field orientation="horizontal">
            <FieldLabel data-subject htmlFor="battery-high">
              FieldLabel
            </FieldLabel>
          </Field>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (39)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <Field orientation="horizontal">
            <FieldLabel data-subject htmlFor="battery-medium">
              FieldLabel
            </FieldLabel>
          </Field>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (40)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <Field orientation="horizontal">
            <FieldLabel data-subject htmlFor="battery-low">
              FieldLabel
            </FieldLabel>
          </Field>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (41)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field orientation="horizontal">
          <FieldContent>
            <FieldLabel data-subject htmlFor="radio-content-1">
              FieldLabel
            </FieldLabel>
          </FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (42)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldLabel data-subject htmlFor="radio-title-1">
          FieldLabel
        </FieldLabel>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (43)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <Field data-invalid orientation="horizontal">
            <FieldLabel data-subject htmlFor="radio-invalid-1">
              FieldLabel
            </FieldLabel>
          </Field>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (44)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <Field data-invalid orientation="horizontal">
            <FieldLabel data-subject htmlFor="radio-invalid-2">
              FieldLabel
            </FieldLabel>
          </Field>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (45)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <Field data-disabled orientation="horizontal">
            <FieldLabel data-subject htmlFor="radio-disabled-1">
              FieldLabel
            </FieldLabel>
          </Field>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (46)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <Field data-disabled orientation="horizontal">
            <FieldLabel data-subject htmlFor="radio-disabled-2">
              FieldLabel
            </FieldLabel>
          </Field>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (47)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field orientation="horizontal">
          <FieldContent>
            <FieldLabel data-subject htmlFor="switch-airplane">
              FieldLabel
            </FieldLabel>
          </FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (48)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field orientation="horizontal">
          <FieldLabel data-subject htmlFor="switch-dark">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (49)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field orientation="horizontal">
          <FieldContent>
            <FieldLabel data-subject htmlFor="switch-marketing">
              FieldLabel
            </FieldLabel>
          </FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (50)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject>FieldLabel</FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (51)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <Field orientation="horizontal">
            <FieldLabel data-subject htmlFor="switch-profile">
              FieldLabel
            </FieldLabel>
          </Field>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (52)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <Field orientation="horizontal">
            <FieldLabel data-subject htmlFor="switch-email">
              FieldLabel
            </FieldLabel>
          </Field>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (53)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-invalid orientation="horizontal">
          <FieldContent>
            <FieldLabel data-subject htmlFor="switch-invalid">
              FieldLabel
            </FieldLabel>
          </FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (54)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-disabled orientation="horizontal">
          <FieldContent>
            <FieldLabel data-subject htmlFor="switch-disabled-field">
              FieldLabel
            </FieldLabel>
          </FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (55)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="slider-volume">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (56)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="slider-brightness">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (57)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="slider-quality">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (58)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="slider-temperature">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (59)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="slider-price-range">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (60)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="slider-color-balance">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (61)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-invalid>
          <FieldLabel data-subject htmlFor="slider-invalid">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (62)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-disabled>
          <FieldLabel data-subject htmlFor="slider-disabled-field">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (63)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="otp-basic">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (64)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="otp-with-desc">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (65)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="otp-separator">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (66)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field>
          <FieldLabel data-subject htmlFor="otp-pin">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (67)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-invalid>
          <FieldLabel data-subject htmlFor="otp-invalid">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (68)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-disabled>
          <FieldLabel data-subject htmlFor="otp-disabled-field">
            FieldLabel
          </FieldLabel>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (69)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field orientation="horizontal">
          <FieldContent>
            <FieldLabel data-subject htmlFor="horizontal-input">
              FieldLabel
            </FieldLabel>
          </FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (70)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field orientation="horizontal">
          <FieldContent>
            <FieldLabel data-subject htmlFor="horizontal-textarea">
              FieldLabel
            </FieldLabel>
          </FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (71)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field orientation="horizontal">
          <FieldContent>
            <FieldLabel data-subject htmlFor="horizontal-switch">
              FieldLabel
            </FieldLabel>
          </FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (72)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field orientation="horizontal">
          <FieldContent>
            <FieldLabel data-subject htmlFor="horizontal-select">
              FieldLabel
            </FieldLabel>
          </FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (73)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field orientation="horizontal">
          <FieldContent>
            <FieldLabel data-subject htmlFor="horizontal-native-select">
              FieldLabel
            </FieldLabel>
          </FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (74)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field orientation="horizontal">
          <FieldContent>
            <FieldLabel data-subject htmlFor="horizontal-slider">
              FieldLabel
            </FieldLabel>
          </FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderFieldTitle(
  props: Partial<Record<keyof ComponentProps<typeof FieldTitle>, unknown>> = {},
) {
  cleanup()
  render(
    <FieldGroup>
      <FieldLabel htmlFor="checkbox-with-title">
        <Field orientation="horizontal">
          <FieldContent>
            <FieldTitle
              data-subject
              {...({ children: 'FieldTitle', ...props } as ComponentProps<typeof FieldTitle>)}
            />
          </FieldContent>
        </Field>
      </FieldLabel>
    </FieldGroup>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="field-label"]')
}

function classesOfFieldTitle(
  props: Partial<Record<keyof ComponentProps<typeof FieldTitle>, unknown>> = {},
) {
  return renderFieldTitle(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('FieldTitle', () => {
  it('renders [data-slot="field-label"] with its classes', () => {
    expect(classesOfFieldTitle()).toEqual(expect.arrayContaining([styles.fieldTitle]))
  })

  it('appends a consumer className last', () => {
    renderFieldTitle({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldLabel htmlFor="radio-title-1">
          <Field orientation="horizontal">
            <FieldContent>
              <FieldTitle data-subject>FieldTitle</FieldTitle>
            </FieldContent>
          </Field>
        </FieldLabel>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderFieldDescription(
  props: Partial<Record<keyof ComponentProps<typeof FieldDescription>, unknown>> = {},
) {
  cleanup()
  render(
    <FieldGroup>
      <Field>
        <FieldDescription
          data-subject
          {...({ children: 'FieldDescription', ...props } as ComponentProps<
            typeof FieldDescription
          >)}
        />
      </Field>
    </FieldGroup>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="field-description"]')
}

function classesOfFieldDescription(
  props: Partial<Record<keyof ComponentProps<typeof FieldDescription>, unknown>> = {},
) {
  return renderFieldDescription(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('FieldDescription', () => {
  it('renders [data-slot="field-description"] with its classes', () => {
    expect(classesOfFieldDescription()).toEqual(expect.arrayContaining([styles.fieldDescription]))
  })

  it('appends a consumer className last', () => {
    renderFieldDescription({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-invalid>
          <FieldDescription data-subject>FieldDescription</FieldDescription>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-disabled>
          <FieldDescription data-subject>FieldDescription</FieldDescription>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field orientation="horizontal">
          <FieldContent>
            <FieldDescription data-subject>FieldDescription</FieldDescription>
          </FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldLabel htmlFor="checkbox-with-title">
          <Field orientation="horizontal">
            <FieldContent>
              <FieldDescription data-subject>FieldDescription</FieldDescription>
            </FieldContent>
          </Field>
        </FieldLabel>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldSet>
          <FieldDescription data-subject>FieldDescription</FieldDescription>
        </FieldSet>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (7)", () => {
    cleanup()
    render(
      <FieldGroup>
        <FieldLabel htmlFor="radio-title-1">
          <Field orientation="horizontal">
            <FieldContent>
              <FieldDescription data-subject>FieldDescription</FieldDescription>
            </FieldContent>
          </Field>
        </FieldLabel>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (8)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-invalid orientation="horizontal">
          <FieldContent>
            <FieldDescription data-subject>FieldDescription</FieldDescription>
          </FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (9)", () => {
    cleanup()
    render(
      <FieldGroup>
        <Field data-disabled orientation="horizontal">
          <FieldContent>
            <FieldDescription data-subject>FieldDescription</FieldDescription>
          </FieldContent>
        </Field>
      </FieldGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderFieldSeparator(
  props: Partial<Record<keyof ComponentProps<typeof FieldSeparator>, unknown>> = {},
) {
  cleanup()
  render(
    <FieldGroup>
      <FieldLabel htmlFor="checkbox-with-title">
        <Field orientation="horizontal">
          <FieldContent>
            <FieldSeparator
              data-subject
              {...({ children: 'FieldSeparator', ...props } as ComponentProps<
                typeof FieldSeparator
              >)}
            />
          </FieldContent>
        </Field>
      </FieldLabel>
    </FieldGroup>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="field-separator"]')
}

function classesOfFieldSeparator(
  props: Partial<Record<keyof ComponentProps<typeof FieldSeparator>, unknown>> = {},
) {
  return renderFieldSeparator(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('FieldSeparator', () => {
  it('renders [data-slot="field-separator"] with its classes', () => {
    expect(classesOfFieldSeparator()).toEqual(expect.arrayContaining([styles.fieldSeparator]))
  })

  it('appends a consumer className last', () => {
    renderFieldSeparator({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderFieldError(
  props: Partial<Record<keyof ComponentProps<typeof FieldError>, unknown>> = {},
) {
  cleanup()
  render(
    <FieldGroup>
      <FieldLabel htmlFor="checkbox-with-title">
        <Field orientation="horizontal">
          <FieldContent>
            <FieldError
              data-subject
              {...({ children: 'FieldError', ...props } as ComponentProps<typeof FieldError>)}
            />
          </FieldContent>
        </Field>
      </FieldLabel>
    </FieldGroup>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="field-error"]')
}

function classesOfFieldError(
  props: Partial<Record<keyof ComponentProps<typeof FieldError>, unknown>> = {},
) {
  return renderFieldError(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('FieldError', () => {
  it('renders [data-slot="field-error"] with its classes', () => {
    expect(classesOfFieldError()).toEqual(expect.arrayContaining([styles.fieldError]))
  })

  it('appends a consumer className last', () => {
    renderFieldError({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})
