import { describe, expect, it } from 'vitest'
import { buildComponent, dependenciesOf, type UpstreamItem } from './component.ts'
import { parseConfig } from './config.ts'

const config = parseConfig({
  upstream: { url: 'https://example.com/{style}/{name}.json', style: 'base-vega' },
  components: ['badge'],
  snapshotDir: 'upstream',
  outputDir: 'registry/ui',
})

const source = (classes: string) => `import { cva } from "class-variance-authority"
import { cn } from "cn"
const badgeVariants = cva("${classes}")
function Badge({ className }) {
  return <span data-slot="badge" className={cn(badgeVariants({ className }))} />
}
export { Badge }`

const badge = (content: string): UpstreamItem => ({
  name: 'badge',
  type: 'registry:ui',
  files: [{ path: 'registry/base-vega/ui/badge.tsx', type: 'registry:ui', content }],
})

describe('buildComponent', () => {
  it('writes the component and its module into a PascalCase folder', async () => {
    const result = await buildComponent(badge(source('group/badge inline-flex bg-primary')), config)
    expect(result.item).toEqual({
      name: 'badge',
      type: 'registry:ui',
      title: 'Badge',
      dependencies: ['clsx'],
      devDependencies: ['@testing-library/dom', '@testing-library/react', 'jsdom', 'vitest'],
      files: [
        { path: 'registry/ui/Badge/Badge.tsx', type: 'registry:ui' },
        { path: 'registry/ui/Badge/Badge.module.scss', type: 'registry:ui' },
        { path: 'registry/ui/Badge/Badge.test.tsx', type: 'registry:ui' },
      ],
    })
    const [tsx, scss, test] = result.files
    expect(test?.content).toContain('describe("Badge", () => {')
    expect(tsx?.content).toMatch(
      /^\/\/ Generated by scripts\/mirror from shadcn base-vega\/badge\./,
    )
    expect(scss?.content).toBe(
      [
        '// Generated by scripts/mirror from shadcn base-vega/badge. Do not edit.',
        '//',
        '// Custom properties read here and provided globally:',
        '//   --primary',
        '//',
        '// Upstream classes with no CSS output, dropped:',
        '//   group/badge',
        '',
        ':where(.badge) {',
        '  display: inline-flex;',
        '  background-color: var(--primary);',
        '}',
        '',
      ].join('\n'),
    )
    expect(result.unresolved).toEqual({ badge: ['group/badge'] })
  })

  it('wraps long property lists and omits empty sections', async () => {
    const properties = Array.from({ length: 12 }, (_, i) => `--a-long-custom-property-${i}`)
    const compile = async () =>
      `@layer utilities { .x { color: ${properties.map((p) => `var(${p})`).join(' ')}; } }`
    const [, scss] = (await buildComponent(badge(source('x')), config, compile)).files
    const comments = (scss?.content.split('\n') ?? []).filter((line) => line.startsWith('//'))
    expect(comments.filter((line) => line.startsWith('//   ')).length).toBeGreaterThan(1)
    expect(comments.every((line) => line.length <= 100)).toBe(true)
    expect(scss?.content).not.toContain('no CSS output')
  })

  it.each([
    ['a non-ui item', { ...badge('x'), type: 'registry:block' }, 'type registry:block'],
    [
      'registry dependencies',
      { ...badge('x'), registryDependencies: ['button'] },
      'registryDependencies',
    ],
    [
      'a file without content',
      { ...badge('x'), files: [{ path: 'a', type: 'registry:ui' }] },
      'one file',
    ],
    ['no files', { ...badge('x'), files: [] }, 'one file'],
    [
      'several files',
      { ...badge('x'), files: [...badge('x').files, ...badge('y').files] },
      'one file',
    ],
  ])('rejects %s', async (_, item, message) => {
    await expect(buildComponent(item as UpstreamItem, config)).rejects.toThrow(message)
  })
})

describe('dependenciesOf', () => {
  it('lists imported packages, excluding relative, aliased and implicit ones', () => {
    const code = `import * as React from "react"
import { createPortal } from "react-dom"
import { Button } from "@base-ui/react/button"
import { clsx } from "clsx"
import { thing } from "lodash/thing"
import styles from "./X.module.scss"
import { util } from "@/lib/util"
export const x = 1`
    expect(dependenciesOf(code)).toEqual(['@base-ui/react', 'clsx', 'lodash'])
  })
})
