// One upstream registry item in, the mirror's files and registry entry out.

import { parse } from '@babel/parser'
import type { MirrorConfig } from './config.ts'
import { pascalCase } from './names.ts'
import { slotToScss } from './scss.ts'
import { generateTest } from './tests.ts'
import { type TransformedComponent, transformComponent } from './tsx.ts'

export type UpstreamItem = {
  name: string
  type: string
  registryDependencies?: string[]
  files: { path: string; type: string; content?: string }[]
}

export type RegistryItem = {
  name: string
  type: 'registry:ui' | 'registry:file'
  title: string
  dependencies: string[]
  devDependencies: string[]
  registryDependencies: string[]
  files: { path: string; type: 'registry:ui' | 'registry:file'; target?: string }[]
}

export type GeneratedComponent = {
  item: RegistryItem
  files: { path: string; content: string }[]
  // Upstream classes Tailwind produced no CSS for, by module class.
  unresolved: Record<string, string[]>
  // Every upstream class the component uses, for the global stylesheets.
  classes: string[]
  // Upstream's source and what the transform learned, for the A/B harness.
  upstreamSource: string
  transformed: TransformedComponent
}

// Packages consumers already have, which shadcn items never list.
const IMPLICIT = new Set(['react', 'react-dom'])

// Needed to run the shipped test but never imported by it: Testing Library's
// peer dependency, and the DOM environment.
const TEST_RUNTIME = ['@testing-library/dom', 'jsdom']

function packageName(specifier: string): string {
  const parts = specifier.split('/')
  return (specifier.startsWith('@') ? parts.slice(0, 2) : parts.slice(0, 1)).join('/')
}

export function dependenciesOf(code: string): string[] {
  const ast = parse(code, {
    sourceType: 'module',
    plugins: ['typescript', 'jsx'],
  })
  const packages = new Set<string>()
  for (const statement of ast.program.body) {
    if (statement.type !== 'ImportDeclaration') continue
    const specifier = statement.source.value
    if (specifier.startsWith('.') || specifier.startsWith('@/')) continue
    const name = packageName(specifier)
    if (!IMPLICIT.has(name)) packages.add(name)
  }
  return [...packages].sort()
}

function wrap(label: string, values: string[]): string[] {
  if (values.length === 0) return []
  const lines = ['//', `// ${label}`]
  let line = '//  '
  for (const value of values) {
    if (line.length + value.length + 1 > 100) {
      lines.push(line)
      line = '//  '
    }
    line += ` ${value}`
  }
  lines.push(line)
  return lines
}

export async function buildComponent(
  upstream: UpstreamItem,
  config: MirrorConfig,
  compile: (candidates: string[]) => Promise<string>,
): Promise<GeneratedComponent> {
  const where = `${config.upstream.style}/${upstream.name}`
  if (upstream.type !== 'registry:ui')
    throw new Error(`${where}: type ${upstream.type} is not supported yet`)
  const [file, ...extra] = upstream.files
  if (!file?.content || extra.length > 0) {
    throw new Error(`${where}: expected exactly one file with content`)
  }

  const component = pascalCase(upstream.name)
  const dir = `${config.outputDir}/${component}`
  const source = transformComponent(file.content, upstream.name, config.namespace)

  // Upstream's bare names mean official shadcn items; each must be mirrored
  // too, and becomes a dependency on this registry's copy.
  const registryDependencies = [
    ...new Set([...(upstream.registryDependencies ?? []), ...source.registryImports]),
  ].map((dependency) => {
    if (!config.components.includes(dependency)) {
      throw new Error(`${where}: depends on ${dependency}, which mirror.config.json does not list`)
    }
    return `@${config.namespace}/${dependency}`
  })
  // Every component reads the global variables and relies on the base layer.
  registryDependencies.push(`@${config.namespace}/globals`)
  const generated = `// Generated by scripts/mirror from shadcn ${where}. Do not edit.`

  const blocks = []
  const unresolved: Record<string, string[]> = {}
  const properties = new Set<string>()
  for (const slot of source.slots) {
    const block = slotToScss(await compile(slot.classes), slot, config.selectorRewrites)
    blocks.push(block.scss)
    if (block.unresolved.length > 0) unresolved[slot.name] = block.unresolved
    for (const property of block.customProperties) properties.add(property)
  }

  const scss = [
    generated,
    ...wrap('Custom properties read here and provided globally:', [...properties].sort()),
    ...wrap('Upstream classes with no CSS output, dropped:', Object.values(unresolved).flat()),
    '',
    blocks.join('\n\n'),
    '',
  ].join('\n')
  const test = generateTest(upstream.name, source)
  const files = [
    {
      path: `${dir}/${component}.tsx`,
      content: `${generated}\n\n${source.code}`,
    },
    { path: `${dir}/${component}.module.scss`, content: scss },
    {
      path: `${dir}/${component}.test.tsx`,
      content: `${generated}\n\n${test}`,
    },
  ]

  return {
    item: {
      name: upstream.name,
      type: 'registry:ui',
      title: component,
      dependencies: dependenciesOf(source.code),
      devDependencies: [...new Set([...dependenciesOf(test), ...TEST_RUNTIME])].sort(),
      registryDependencies,
      files: files.map(({ path }) => ({ path, type: 'registry:ui' })),
    },
    files,
    unresolved,
    classes: [...new Set(source.slots.flatMap((slot) => slot.classes))],
    upstreamSource: file.content,
    transformed: source,
  }
}
