// Generates the A/B harness inputs (ab/generated): each component's upstream
// source verbatim, maps from item name to upstream and mirrored modules, the
// Tailwind entry for the upstream page, and one fixture per exported
// component and cva() option, so every mirrored component is compared without
// hand-written cases. Hand-written compositions live in ab/compositions.tsx.

import { relative } from 'node:path'
import type { MirrorConfig } from './config.ts'
import { camelCase, pascalCase } from './names.ts'
import { exportedNames } from './tests.ts'
import type { TransformedComponent, VariantSet } from './tsx.ts'

export type Fixture = {
  item: string
  component: string
  label: string
  props: Record<string, string>
}

export type HarnessInput = {
  name: string
  upstreamSource: string
  transformed: TransformedComponent
}

export function fixturesFor(name: string, transformed: TransformedComponent): Fixture[] {
  const exported = exportedNames(transformed.code)
  const sets = new Map(transformed.variantSets.map((set) => [set.variable, set]))
  return transformed.components
    .filter((component) => exported.has(component.name))
    .flatMap((component) => {
      // A component's variantSet always names a cva() the transform recorded.
      const groups = component.variantSet
        ? (sets.get(component.variantSet) as VariantSet).groups
        : []
      const base = { item: name, component: component.name }
      if (groups.length === 0) return [{ ...base, label: component.name, props: {} }]
      return groups.flatMap((group) =>
        group.options.map((option) => ({
          ...base,
          label: `${component.name} ${group.name}=${option.value}`,
          props: { [group.name]: option.value },
        })),
      )
    })
}

function moduleMap(
  exportName: string,
  inputs: HarnessInput[],
  specifier: (name: string) => string,
): string {
  return [
    ...inputs.map(
      ({ name }) => `import * as ${camelCase(name)} from ${JSON.stringify(specifier(name))}`,
    ),
    '',
    `export const ${exportName} = {`,
    ...inputs.map(({ name }) => `  ${JSON.stringify(name)}: ${camelCase(name)},`),
    '}',
  ].join('\n')
}

export function harnessFiles(
  config: MirrorConfig,
  inputs: HarnessInput[],
  header: string,
): { path: string; content: string }[] {
  const dir = config.harnessDir
  const indexCss = `${config.snapshotDir}/${config.upstream.style}/index.css`
  const fixtures = inputs.flatMap(({ name, transformed }) => fixturesFor(name, transformed))
  const ts = (content: string) => `${header}\n\n${content}\n`
  return [
    ...inputs.map(({ name, upstreamSource }) => ({
      path: `${dir}/upstream/${name}.tsx`,
      content: `${header}\n\n${upstreamSource}`,
    })),
    {
      path: `${dir}/upstream.ts`,
      content: ts(moduleMap('upstream', inputs, (name) => `./upstream/${name}`)),
    },
    {
      path: `${dir}/ours.ts`,
      content: ts(
        moduleMap('ours', inputs, (name) => {
          const file = pascalCase(name)
          return `@/registry/${config.namespace}/ui/${file}/${file}`
        }),
      ),
    },
    {
      path: `${dir}/fixtures.ts`,
      content: ts(`export const fixtures = ${JSON.stringify(fixtures, null, 2)}`),
    },
    {
      path: `${dir}/upstream.css`,
      content: [
        '/* Generated by scripts/mirror. Do not edit. */',
        `@import ${JSON.stringify(relative(dir, indexCss))};`,
        '@source "./upstream";',
        '',
      ].join('\n'),
    },
  ]
}
