// Generates the A/B harness inputs (ab/generated): each component's upstream
// source verbatim, maps from item name to upstream and mirrored modules, the
// Tailwind entry for the upstream page, and one fixture per exported
// component and cva() option, so every mirrored component is compared without
// hand-written cases. Hand-written compositions live in ab/compositions.tsx.

import { relative } from 'node:path'
import type { MirrorConfig } from './config.ts'
import type { PreparedExample } from './examples.ts'
import { camelCase, pascalCase } from './names.ts'
import { exportedNames } from './tests.ts'
import type { TransformedComponent, VariantSet } from './tsx.ts'
import type { TypesetFixture } from './typeset.ts'

export type Fixture = {
  item: string
  component: string
  label: string
  props: Record<string, string>
}

export type HarnessInput = {
  name: string
  upstreamSource: string
  transformed: TransformedComponent
}

export function fixturesFor(name: string, transformed: TransformedComponent): Fixture[] {
  const exported = exportedNames(transformed.code)
  const sets = new Map(transformed.variantSets.map((set) => [set.variable, set]))
  return transformed.components
    .filter((component) => exported.has(component.name))
    .flatMap((component) => {
      // A component's variantSet always names a cva() the transform recorded.
      const groups = component.variantSet
        ? (sets.get(component.variantSet) as VariantSet).groups
        : []
      const base = { item: name, component: component.name }
      if (groups.length === 0) return [{ ...base, label: component.name, props: {} }]
      return groups.flatMap((group) =>
        group.options.map((option) => ({
          ...base,
          label: `${component.name} ${group.name}=${option.value}`,
          props: { [group.name]: option.value },
        })),
      )
    })
}

export type HarnessExample = { name: string; prepared: PreparedExample }

function moduleMap(
  exportName: string,
  names: string[],
  specifier: (name: string) => string,
): string {
  return [
    ...names.map(
      (name) => `import * as ${camelCase(name)} from ${JSON.stringify(specifier(name))}`,
    ),
    '',
    `export const ${exportName} = {`,
    ...names.map((name) => `  ${JSON.stringify(name)}: ${camelCase(name)},`),
    '}',
  ].join('\n')
}

export function harnessFiles(
  config: MirrorConfig,
  harness: {
    components: HarnessInput[]
    examples: HarnessExample[]
    layoutCss: string
    typeset: TypesetFixture[]
  },
  header: string,
): { path: string; content: string }[] {
  const dir = config.harnessDir
  const indexCss = `${config.snapshotDir}/${config.upstream.style}/index.css`
  const typesetCss = `${config.snapshotDir}/typeset/typeset.css`
  const components = harness.components.map(({ name }) => name)
  const examples = harness.examples.map(({ name }) => name)
  const fixtures = harness.components.flatMap(({ name, transformed }) =>
    fixturesFor(name, transformed),
  )
  const cases = harness.examples.flatMap(({ name, prepared }) =>
    prepared.kept.map((sub) => ({ example: name, name: sub })),
  )
  const ts = (content: string) => `${header}\n\n${content}\n`
  return [
    ...harness.components.map(({ name, upstreamSource }) => ({
      path: `${dir}/upstream/${name}.tsx`,
      content: `${header}\n\n${upstreamSource}`,
    })),
    ...harness.examples.flatMap(({ name, prepared }) =>
      (['upstream', 'ours'] as const).map((side) => ({
        path: `${dir}/examples/${side}/${name}.tsx`,
        content: `${header}\n\n${prepared[side]}`,
      })),
    ),
    {
      path: `${dir}/upstream.ts`,
      content: ts(moduleMap('upstream', components, (n) => `./upstream/${n}`)),
    },
    {
      path: `${dir}/ours.ts`,
      content: ts(
        moduleMap('ours', components, (name) => {
          const file = pascalCase(name)
          return `@/registry/${config.namespace}/ui/${file}/${file}`
        }),
      ),
    },
    {
      path: `${dir}/examples-upstream.ts`,
      content: ts(moduleMap('upstreamExamples', examples, (n) => `./examples/upstream/${n}`)),
    },
    {
      path: `${dir}/examples-ours.ts`,
      content: ts(moduleMap('oursExamples', examples, (n) => `./examples/ours/${n}`)),
    },
    {
      path: `${dir}/fixtures.ts`,
      content: ts(`export const fixtures = ${JSON.stringify(fixtures, null, 2)}`),
    },
    {
      path: `${dir}/examples.ts`,
      content: ts(`export const examples = ${JSON.stringify(cases, null, 2)}`),
    },
    {
      path: `${dir}/typeset.ts`,
      content: ts(`export const typeset = ${JSON.stringify(harness.typeset, null, 2)}`),
    },
    {
      path: `${dir}/upstream.css`,
      content: [
        '/* Generated by scripts/mirror. Do not edit. */',
        `@import ${JSON.stringify(relative(dir, indexCss))};`,
        // After Tailwind, as upstream's docs set Typeset up.
        `@import ${JSON.stringify(relative(dir, typesetCss))};`,
        '@source "./upstream";',
        '@source "./examples/upstream";',
        '',
      ].join('\n'),
    },
    { path: `${dir}/examples.css`, content: harness.layoutCss },
  ]
}
