// Rebuilds the CSS entry file `shadcn init` writes into a project for the
// configured style and theme, from the same registry data the CLI reads:
// the style's index item (its imports and base layer), the base color's
// light and dark variables, and the font item. The mirror compiles upstream
// classes against it, derives the global stylesheets from it, and the A/B
// harness styles its upstream page with it, so all three agree with what an
// upstream project ships.
//
// Reference: packages/shadcn/src/utils/updaters/update-css-vars.ts.

import { internalName } from './internal.ts'

export type StyleIndex = { css?: CssTree }
export type CssTree = { [key: string]: CssTree }

export type BaseColor = {
  cssVarsV4: { light: Record<string, string>; dark: Record<string, string> }
}

export type FontItem = { font: { family: string; variable: string; dependency: string } }

// The radius scale the CLI derives from --radius.
const RADIUS = {
  sm: 'calc(var(--radius) * 0.6)',
  md: 'calc(var(--radius) * 0.8)',
  lg: 'var(--radius)',
  xl: 'calc(var(--radius) * 1.4)',
  '2xl': 'calc(var(--radius) * 1.8)',
  '3xl': 'calc(var(--radius) * 2.2)',
  '4xl': 'calc(var(--radius) * 2.6)',
}

function print(tree: CssTree, depth: number): string[] {
  const indent = '  '.repeat(depth)
  return Object.entries(tree).flatMap(([key, children]) =>
    Object.keys(children).length === 0 && key.startsWith('@')
      ? [`${indent}${key};`]
      : [`${indent}${key} {`, ...print(children, depth + 1), `${indent}}`],
  )
}

function declarations(vars: Record<string, string>): string[] {
  return Object.entries(vars).map(([name, value]) => `  --${name}: ${value};`)
}

// The style's imports (tw-animate-css, shadcn/tailwind.css), the dark variant,
// the @theme inline mapping and the font variables: what both the project CSS
// and the A/B harness's example layout CSS need.
function themeSetup(index: StyleIndex, color: BaseColor, font: FontItem): string[] {
  const imports = Object.fromEntries(
    Object.entries(index.css ?? {}).filter(([key]) => key.startsWith('@import')),
  )
  return [
    ...print(imports, 0),
    '',
    '@custom-variant dark (&:is(.dark *));',
    '',
    '@theme inline {',
    ...Object.keys(color.cssVarsV4.light)
      .filter((name) => name !== 'radius')
      .map((name) => `  --color-${name}: var(--${name});`),
    ...Object.entries(RADIUS).map(([size, value]) => `  --radius-${size}: ${value};`),
    '}',
    '',
    // Not inline, unlike upstream: the generated CSS then reads
    // var(--font-sans) and var(--font-heading), so a font item's stylesheet
    // can replace one. Upstream's CLI instead rewrites the variable in the
    // project's Tailwind entry.
    '@theme {',
    '  --font-heading: var(--font-sans);',
    `  ${font.font.variable}: ${font.font.family};`,
    '}',
  ]
}

export function projectCss(index: StyleIndex, color: BaseColor, font: FontItem): string {
  const { light, dark } = color.cssVarsV4
  const rest = Object.fromEntries(
    Object.entries(index.css ?? {}).filter(([key]) => !key.startsWith('@import')),
  )
  const base = { ...rest['@layer base'], html: { '@apply font-sans': {} } }

  return [
    '/* Generated by scripts/mirror from the upstream style, base color and font. Do not edit.',
    ' * The font package itself is imported by whoever renders with this file, since',
    ' * Tailwind would otherwise inline its @font-face rules with relative URLs. */',
    '',
    '@import "tailwindcss";',
    ...themeSetup(index, color, font),
    '',
    ':root {',
    ...declarations(light),
    '}',
    '',
    '.dark {',
    ...declarations(dark),
    '}',
    '',
    ...print({ ...rest, '@layer base': base }, 0),
    '',
  ].join('\n')
}

// Tailwind for the A/B harness's ours page: utilities for the classes in the
// example files under `source` only. No preflight and no base color variables
// (ours brings its own), and unlayered, so a class an example passes to one of our
// components outranks its :where() defaults, as tailwind-merge makes it win
// upstream.
export function layoutCss(
  index: StyleIndex,
  color: BaseColor,
  font: FontItem,
  source: string,
): string {
  return [
    '/* Generated by scripts/mirror. Do not edit. */',
    '',
    '@import "tailwindcss/theme.css" layer(theme);',
    '@import "tailwindcss/utilities.css" source(none);',
    ...themeSetup(index, color, font),
    '',
    `@source ${JSON.stringify(source)};`,
    '',
    // Upstream, tailwind-merge drops a component's leading-* when the example
    // passes a text size, so the component's other text-size rules (a
    // group-data size variant) read no leading. The component's module still
    // sets it here, so the example's text size clears it, unless the example
    // passes its own leading-*.
    `:is(${TEXT_SIZES.map((size) => `.text-${size}`).join(', ')}):not([class*="leading-"]) {`,
    `  ${internalName('--tw-leading')}: initial;`,
    '}',
    '',
  ].join('\n')
}

// The project CSS with Tailwind's theme emitted whole (theme(static)), for the
// global stylesheets.
export function staticTheme(css: string): string {
  const plain = '@import "tailwindcss";'
  if (!css.includes(plain)) throw new Error(`project CSS does not import tailwindcss as ${plain}`)
  return css.replace(plain, '@import "tailwindcss" theme(static);')
}

const TEXT_SIZES = [
  'xs',
  'sm',
  'base',
  'lg',
  'xl',
  '2xl',
  '3xl',
  '4xl',
  '5xl',
  '6xl',
  '7xl',
  '8xl',
  '9xl',
]
