// Rebuilds the CSS entry file `shadcn init` writes into a project for the
// configured style and theme, from the same registry data the CLI reads:
// the style's index item (its imports and base layer), the base color's
// light and dark variables, and the font item. The mirror compiles upstream
// classes against it, derives the global stylesheets from it, and the A/B
// harness styles its upstream page with it, so all three agree with what an
// upstream project ships.
//
// Reference: packages/shadcn/src/utils/updaters/update-css-vars.ts.

export type StyleIndex = { css?: CssTree }
export type CssTree = { [key: string]: CssTree }

export type BaseColor = {
  cssVarsV4: { light: Record<string, string>; dark: Record<string, string> }
}

export type FontItem = { font: { family: string; variable: string; dependency: string } }

// The radius scale the CLI derives from --radius.
const RADIUS = {
  sm: 'calc(var(--radius) * 0.6)',
  md: 'calc(var(--radius) * 0.8)',
  lg: 'var(--radius)',
  xl: 'calc(var(--radius) * 1.4)',
  '2xl': 'calc(var(--radius) * 1.8)',
  '3xl': 'calc(var(--radius) * 2.2)',
  '4xl': 'calc(var(--radius) * 2.6)',
}

function print(tree: CssTree, depth: number): string[] {
  const indent = '  '.repeat(depth)
  return Object.entries(tree).flatMap(([key, children]) =>
    Object.keys(children).length === 0 && key.startsWith('@')
      ? [`${indent}${key};`]
      : [`${indent}${key} {`, ...print(children, depth + 1), `${indent}}`],
  )
}

function declarations(vars: Record<string, string>): string[] {
  return Object.entries(vars).map(([name, value]) => `  --${name}: ${value};`)
}

export function projectCss(index: StyleIndex, color: BaseColor, font: FontItem): string {
  const { light, dark } = color.cssVarsV4
  const css = index.css ?? {}
  const imports = Object.fromEntries(
    Object.entries(css).filter(([key]) => key.startsWith('@import')),
  )
  const rest = Object.fromEntries(Object.entries(css).filter(([key]) => !key.startsWith('@import')))
  const base = { ...rest['@layer base'], html: { '@apply font-sans': {} } }

  return [
    '/* Generated by scripts/mirror from the upstream style, base color and font. Do not edit.',
    ' * The font package itself is imported by whoever renders with this file, since',
    ' * Tailwind would otherwise inline its @font-face rules with relative URLs. */',
    '',
    '@import "tailwindcss";',
    ...print(imports, 0),
    '',
    '@custom-variant dark (&:is(.dark *));',
    '',
    '@theme inline {',
    '  --font-heading: var(--font-sans);',
    `  ${font.font.variable}: ${font.font.family};`,
    ...Object.keys(light)
      .filter((name) => name !== 'radius')
      .map((name) => `  --color-${name}: var(--${name});`),
    ...Object.entries(RADIUS).map(([size, value]) => `  --radius-${size}: ${value};`),
    '}',
    '',
    ':root {',
    ...declarations(light),
    '}',
    '',
    '.dark {',
    ...declarations(dark),
    '}',
    '',
    ...print({ ...rest, '@layer base': base }, 0),
    '',
  ].join('\n')
}
