// Generated by scripts/mirror from shadcn base-vega/breadcrumb. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { describe, expect, it } from 'vitest'
import {
  Breadcrumb,
  BreadcrumbEllipsis,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from './Breadcrumb'
import styles from './Breadcrumb.module.scss'

function renderBreadcrumb(props: Partial<ComponentProps<typeof Breadcrumb>> = {}) {
  cleanup()
  render(<Breadcrumb {...(props as ComponentProps<typeof Breadcrumb>)} />)
  return document.querySelector('[data-slot="breadcrumb"]')?.getAttribute('class')?.split(' ') ?? []
}

describe('Breadcrumb', () => {
  it('appends a consumer className last', () => {
    expect(renderBreadcrumb({ className: 'consumer' }).at(-1)).toBe('consumer')
  })
})

function renderBreadcrumbList(props: Partial<ComponentProps<typeof BreadcrumbList>> = {}) {
  cleanup()
  render(
    <Breadcrumb>
      <BreadcrumbList {...(props as ComponentProps<typeof BreadcrumbList>)} />
    </Breadcrumb>,
  )
  return (
    document.querySelector('[data-slot="breadcrumb-list"]')?.getAttribute('class')?.split(' ') ?? []
  )
}

describe('BreadcrumbList', () => {
  it('renders [data-slot="breadcrumb-list"] with its classes', () => {
    expect(renderBreadcrumbList()).toEqual(expect.arrayContaining([styles.breadcrumbList]))
  })

  it('appends a consumer className last', () => {
    expect(renderBreadcrumbList({ className: 'consumer' }).at(-1)).toBe('consumer')
  })
})

function renderBreadcrumbItem(props: Partial<ComponentProps<typeof BreadcrumbItem>> = {}) {
  cleanup()
  render(
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbItem {...(props as ComponentProps<typeof BreadcrumbItem>)} />
      </BreadcrumbList>
    </Breadcrumb>,
  )
  return (
    document.querySelector('[data-slot="breadcrumb-item"]')?.getAttribute('class')?.split(' ') ?? []
  )
}

describe('BreadcrumbItem', () => {
  it('renders [data-slot="breadcrumb-item"] with its classes', () => {
    expect(renderBreadcrumbItem()).toEqual(expect.arrayContaining([styles.breadcrumbItem]))
  })

  it('appends a consumer className last', () => {
    expect(renderBreadcrumbItem({ className: 'consumer' }).at(-1)).toBe('consumer')
  })
})

function renderBreadcrumbLink(props: Partial<ComponentProps<typeof BreadcrumbLink>> = {}) {
  cleanup()
  render(
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbItem>
          <BreadcrumbLink href="#" {...(props as ComponentProps<typeof BreadcrumbLink>)} />
        </BreadcrumbItem>
      </BreadcrumbList>
    </Breadcrumb>,
  )
  return (
    document.querySelector('[data-slot="breadcrumb-link"]')?.getAttribute('class')?.split(' ') ?? []
  )
}

describe('BreadcrumbLink', () => {
  it('renders [data-slot="breadcrumb-link"] with its classes', () => {
    expect(renderBreadcrumbLink()).toEqual(expect.arrayContaining([styles.breadcrumbLink]))
  })

  it('appends a consumer className last', () => {
    expect(renderBreadcrumbLink({ className: 'consumer' }).at(-1)).toBe('consumer')
  })
})

function renderBreadcrumbPage(props: Partial<ComponentProps<typeof BreadcrumbPage>> = {}) {
  cleanup()
  render(
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbItem>
          <BreadcrumbPage {...(props as ComponentProps<typeof BreadcrumbPage>)} />
        </BreadcrumbItem>
      </BreadcrumbList>
    </Breadcrumb>,
  )
  return (
    document.querySelector('[data-slot="breadcrumb-page"]')?.getAttribute('class')?.split(' ') ?? []
  )
}

describe('BreadcrumbPage', () => {
  it('renders [data-slot="breadcrumb-page"] with its classes', () => {
    expect(renderBreadcrumbPage()).toEqual(expect.arrayContaining([styles.breadcrumbPage]))
  })

  it('appends a consumer className last', () => {
    expect(renderBreadcrumbPage({ className: 'consumer' }).at(-1)).toBe('consumer')
  })
})

function renderBreadcrumbSeparator(
  props: Partial<ComponentProps<typeof BreadcrumbSeparator>> = {},
) {
  cleanup()
  render(
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbSeparator {...(props as ComponentProps<typeof BreadcrumbSeparator>)} />
      </BreadcrumbList>
    </Breadcrumb>,
  )
  return (
    document
      .querySelector('[data-slot="breadcrumb-separator"]')
      ?.getAttribute('class')
      ?.split(' ') ?? []
  )
}

describe('BreadcrumbSeparator', () => {
  it('renders [data-slot="breadcrumb-separator"] with its classes', () => {
    expect(renderBreadcrumbSeparator()).toEqual(
      expect.arrayContaining([styles.breadcrumbSeparator]),
    )
  })

  it('appends a consumer className last', () => {
    expect(renderBreadcrumbSeparator({ className: 'consumer' }).at(-1)).toBe('consumer')
  })
})

function renderBreadcrumbEllipsis(props: Partial<ComponentProps<typeof BreadcrumbEllipsis>> = {}) {
  cleanup()
  render(
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbItem>
          <BreadcrumbEllipsis {...(props as ComponentProps<typeof BreadcrumbEllipsis>)} />
        </BreadcrumbItem>
      </BreadcrumbList>
    </Breadcrumb>,
  )
  return (
    document
      .querySelector('[data-slot="breadcrumb-ellipsis"]')
      ?.getAttribute('class')
      ?.split(' ') ?? []
  )
}

describe('BreadcrumbEllipsis', () => {
  it('renders [data-slot="breadcrumb-ellipsis"] with its classes', () => {
    expect(renderBreadcrumbEllipsis()).toEqual(expect.arrayContaining([styles.breadcrumbEllipsis]))
  })

  it('appends a consumer className last', () => {
    expect(renderBreadcrumbEllipsis({ className: 'consumer' }).at(-1)).toBe('consumer')
  })
})
