// Generated by scripts/mirror from shadcn base-nova/input-group. Do not edit.

'use client'

import { type ClassValue, clsx } from 'clsx'
import type * as React from 'react'

import { Button } from '@/registry/bje/ui/Button/Button'
import { Input } from '@/registry/bje/ui/Input/Input'
import { Textarea } from '@/registry/bje/ui/Textarea/Textarea'
import styles from './InputGroup.module.scss'

function InputGroup({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      data-slot="input-group"
      role="group"
      className={clsx(styles.inputGroup, className)}
      {...props}
    />
  )
}

const inputGroupAddonVariantClasses = {
  align: {
    'inline-start': styles.inputGroupAddonAlignInlineStart,
    'inline-end': styles.inputGroupAddonAlignInlineEnd,
    'block-start': styles.inputGroupAddonAlignBlockStart,
    'block-end': styles.inputGroupAddonAlignBlockEnd,
  },
} as const

type InputGroupAddonVariantProps = {
  [Group in keyof typeof inputGroupAddonVariantClasses]?:
    | keyof (typeof inputGroupAddonVariantClasses)[Group]
    | null
}

function inputGroupAddonVariants({
  align = 'inline-start',
  className,
}: InputGroupAddonVariantProps & { className?: ClassValue } = {}) {
  return clsx(
    styles.inputGroupAddon,
    align && inputGroupAddonVariantClasses.align[align],
    className,
  )
}

function InputGroupAddon({
  className,
  align = 'inline-start',
  ...props
}: React.ComponentProps<'div'> & InputGroupAddonVariantProps) {
  return (
    <div
      role="group"
      data-slot="input-group-addon"
      data-align={align}
      className={clsx(inputGroupAddonVariants({ align }), className)}
      onClick={(e) => {
        if ((e.target as HTMLElement).closest('button')) {
          return
        }
        e.currentTarget.parentElement?.querySelector('input')?.focus()
      }}
      {...props}
    />
  )
}

const inputGroupButtonVariantClasses = {
  size: {
    xs: styles.inputGroupButtonSizeXs,
    sm: undefined,
    'icon-xs': styles.inputGroupButtonSizeIconXs,
    'icon-sm': styles.inputGroupButtonSizeIconSm,
  },
} as const

type InputGroupButtonVariantProps = {
  [Group in keyof typeof inputGroupButtonVariantClasses]?:
    | keyof (typeof inputGroupButtonVariantClasses)[Group]
    | null
}

function inputGroupButtonVariants({
  size = 'xs',
  className,
}: InputGroupButtonVariantProps & { className?: ClassValue } = {}) {
  return clsx(styles.inputGroupButton, size && inputGroupButtonVariantClasses.size[size], className)
}

function InputGroupButton({
  className,
  type = 'button',
  variant = 'ghost',
  size = 'xs',
  ...props
}: Omit<React.ComponentProps<typeof Button>, 'size' | 'type'> &
  InputGroupButtonVariantProps & {
    type?: 'button' | 'submit' | 'reset'
  }) {
  return (
    <Button
      type={type}
      data-size={size}
      variant={variant}
      className={clsx(inputGroupButtonVariants({ size }), className)}
      {...props}
    />
  )
}

function InputGroupText({ className, ...props }: React.ComponentProps<'span'>) {
  return (
    <span data-class-size="" className={clsx(styles.inputGroupTextSpan, className)} {...props} />
  )
}

function InputGroupInput({ className, ...props }: React.ComponentProps<'input'>) {
  return (
    <Input
      data-slot="input-group-control"
      className={clsx(styles.inputGroupControl, className)}
      {...props}
    />
  )
}

function InputGroupTextarea({ className, ...props }: React.ComponentProps<'textarea'>) {
  return (
    <Textarea
      data-slot="input-group-control"
      className={clsx(styles.inputGroupTextarea, className)}
      {...props}
    />
  )
}

export {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput,
  InputGroupText,
  InputGroupTextarea,
}
