// Generated by scripts/mirror from shadcn base-maia/textarea. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { afterEach, describe, expect, it } from 'vitest'
import { Textarea } from './Textarea'
import styles from './Textarea.module.scss'

afterEach(cleanup)

function renderTextarea(
  props: Partial<Record<keyof ComponentProps<typeof Textarea>, unknown>> = {},
) {
  cleanup()
  render(
    <Textarea
      data-subject
      {...({ placeholder: 'Type your message here.', ...props } as ComponentProps<typeof Textarea>)}
    />,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="textarea"]')
}

function classesOfTextarea(
  props: Partial<Record<keyof ComponentProps<typeof Textarea>, unknown>> = {},
) {
  return renderTextarea(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('Textarea', () => {
  it('renders [data-slot="textarea"] with its classes', () => {
    expect(classesOfTextarea()).toEqual(expect.arrayContaining([styles.textarea]))
  })

  it('appends a consumer className last', () => {
    renderTextarea({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(<Textarea data-subject placeholder="Type your message here." aria-invalid="true" />)
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Textarea
        data-subject
        id="textarea-demo-message"
        placeholder="Type your message here."
        rows={6}
      />,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <Textarea
        data-subject
        id="textarea-demo-message-2"
        placeholder="Type your message here."
        rows={6}
      />,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <Textarea data-subject id="textarea-demo-disabled" placeholder="Type your message here." />,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})
