// Generated by scripts/mirror from shadcn base-nova/message. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { afterEach, describe, expect, it } from 'vitest'
import {
  Message,
  MessageAvatar,
  MessageContent,
  MessageFooter,
  MessageGroup,
  MessageHeader,
} from './Message'
import styles from './Message.module.scss'

// React's useId output (_r_1_, and :r1: or «r1» before React 19.1), which
// differs between renders; Base UI puts it in ids and data-id.
const USE_ID = /_r_[0-9a-z]+_|:r[0-9a-z]+:|«r[0-9a-z]+»/g

afterEach(cleanup)

function renderMessageGroup(
  props: Partial<Record<keyof ComponentProps<typeof MessageGroup>, unknown>> = {},
) {
  cleanup()
  render(
    <MessageGroup
      data-subject
      {...({ children: 'MessageGroup', ...props } as ComponentProps<typeof MessageGroup>)}
    />,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="message-group"]')
}

function classesOfMessageGroup(
  props: Partial<Record<keyof ComponentProps<typeof MessageGroup>, unknown>> = {},
) {
  return renderMessageGroup(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('MessageGroup', () => {
  it('renders [data-slot="message-group"] with its classes', () => {
    expect(classesOfMessageGroup()).toEqual(expect.arrayContaining([styles.messageGroup]))
  })

  it('appends a consumer className last', () => {
    renderMessageGroup({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderMessage(props: Partial<Record<keyof ComponentProps<typeof Message>, unknown>> = {}) {
  cleanup()
  render(
    <Message
      data-subject
      {...({ children: 'Message', ...props } as ComponentProps<typeof Message>)}
    />,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="message"]')
}

function classesOfMessage(
  props: Partial<Record<keyof ComponentProps<typeof Message>, unknown>> = {},
) {
  return renderMessage(props)?.getAttribute('class')?.split(' ') ?? []
}

function htmlOfMessage(props: Partial<Record<keyof ComponentProps<typeof Message>, unknown>> = {}) {
  renderMessage(props)
  return document.body.innerHTML.replace(USE_ID, '')
}

function attributesOfMessage(
  props: Partial<Record<keyof ComponentProps<typeof Message>, unknown>> = {},
) {
  const element = renderMessage(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('Message', () => {
  it('renders [data-slot="message"] with its classes', () => {
    expect(classesOfMessage()).toEqual(expect.arrayContaining([styles.message]))
  })

  it('renders the same with align="start" passed explicitly', () => {
    expect(attributesOfMessage({ align: 'start' })).toEqual(attributesOfMessage())
  })

  it('renders differently with align="end"', () => {
    expect(htmlOfMessage({ align: 'end' })).not.toBe(htmlOfMessage())
  })

  it('appends a consumer className last', () => {
    renderMessage({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(<Message data-subject>Message</Message>)
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <MessageGroup>
        <Message data-subject>Message</Message>
      </MessageGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <MessageGroup>
        <Message data-subject align="end">
          Message
        </Message>
      </MessageGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <Message data-subject align="start">
        Message
      </Message>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderMessageAvatar(
  props: Partial<Record<keyof ComponentProps<typeof MessageAvatar>, unknown>> = {},
) {
  cleanup()
  render(
    <Message>
      <MessageAvatar
        data-subject
        {...({ children: 'MessageAvatar', ...props } as ComponentProps<typeof MessageAvatar>)}
      />
    </Message>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="message-avatar"]')
}

function classesOfMessageAvatar(
  props: Partial<Record<keyof ComponentProps<typeof MessageAvatar>, unknown>> = {},
) {
  return renderMessageAvatar(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('MessageAvatar', () => {
  it('renders [data-slot="message-avatar"] with its classes', () => {
    expect(classesOfMessageAvatar()).toEqual(expect.arrayContaining([styles.messageAvatar]))
  })

  it('appends a consumer className last', () => {
    renderMessageAvatar({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Message align="end">
        <MessageAvatar data-subject>MessageAvatar</MessageAvatar>
      </Message>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <MessageGroup>
        <Message align="end">
          <MessageAvatar data-subject />
        </Message>
      </MessageGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <MessageGroup>
        <Message align="end">
          <MessageAvatar data-subject>MessageAvatar</MessageAvatar>
        </Message>
      </MessageGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <MessageGroup>
        <Message>
          <MessageAvatar data-subject />
        </Message>
      </MessageGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(
      <MessageGroup>
        <Message>
          <MessageAvatar data-subject>MessageAvatar</MessageAvatar>
        </Message>
      </MessageGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderMessageContent(
  props: Partial<Record<keyof ComponentProps<typeof MessageContent>, unknown>> = {},
) {
  cleanup()
  render(
    <Message align="end">
      <MessageContent
        data-subject
        {...({ children: 'MessageContent', ...props } as ComponentProps<typeof MessageContent>)}
      />
    </Message>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="message-content"]')
}

function classesOfMessageContent(
  props: Partial<Record<keyof ComponentProps<typeof MessageContent>, unknown>> = {},
) {
  return renderMessageContent(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('MessageContent', () => {
  it('renders [data-slot="message-content"] with its classes', () => {
    expect(classesOfMessageContent()).toEqual(expect.arrayContaining([styles.messageContent]))
  })

  it('appends a consumer className last', () => {
    renderMessageContent({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Message>
        <MessageContent data-subject>MessageContent</MessageContent>
      </Message>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <MessageGroup>
        <Message>
          <MessageContent data-subject>MessageContent</MessageContent>
        </Message>
      </MessageGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <MessageGroup>
        <Message align="end">
          <MessageContent data-subject>MessageContent</MessageContent>
        </Message>
      </MessageGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <Message align="start">
        <MessageContent data-subject>MessageContent</MessageContent>
      </Message>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderMessageHeader(
  props: Partial<Record<keyof ComponentProps<typeof MessageHeader>, unknown>> = {},
) {
  cleanup()
  render(
    <Message>
      <MessageContent>
        <MessageHeader
          data-subject
          {...({ children: 'MessageHeader', ...props } as ComponentProps<typeof MessageHeader>)}
        />
      </MessageContent>
    </Message>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="message-header"]')
}

function classesOfMessageHeader(
  props: Partial<Record<keyof ComponentProps<typeof MessageHeader>, unknown>> = {},
) {
  return renderMessageHeader(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('MessageHeader', () => {
  it('renders [data-slot="message-header"] with its classes', () => {
    expect(classesOfMessageHeader()).toEqual(expect.arrayContaining([styles.messageHeader]))
  })

  it('appends a consumer className last', () => {
    renderMessageHeader({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Message align="end">
        <MessageContent>
          <MessageHeader data-subject>MessageHeader</MessageHeader>
        </MessageContent>
      </Message>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Message align="start">
        <MessageContent>
          <MessageHeader data-subject>MessageHeader</MessageHeader>
        </MessageContent>
      </Message>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderMessageFooter(
  props: Partial<Record<keyof ComponentProps<typeof MessageFooter>, unknown>> = {},
) {
  cleanup()
  render(
    <Message align="end">
      <MessageContent>
        <MessageFooter
          data-subject
          {...({ children: 'MessageFooter', ...props } as ComponentProps<typeof MessageFooter>)}
        />
      </MessageContent>
    </Message>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="message-footer"]')
}

function classesOfMessageFooter(
  props: Partial<Record<keyof ComponentProps<typeof MessageFooter>, unknown>> = {},
) {
  return renderMessageFooter(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('MessageFooter', () => {
  it('renders [data-slot="message-footer"] with its classes', () => {
    expect(classesOfMessageFooter()).toEqual(expect.arrayContaining([styles.messageFooter]))
  })

  it('appends a consumer className last', () => {
    renderMessageFooter({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Message align="start">
        <MessageContent>
          <MessageFooter data-subject>MessageFooter</MessageFooter>
        </MessageContent>
      </Message>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Message>
        <MessageContent>
          <MessageFooter data-subject>MessageFooter</MessageFooter>
        </MessageContent>
      </Message>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})
