// Generated by scripts/mirror from shadcn base-vega/bubble. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { describe, expect, it } from 'vitest'
import { Bubble, BubbleContent, BubbleGroup, BubbleReactions } from './Bubble'
import styles from './Bubble.module.scss'

// React's useId output (_r_1_, and :r1: or «r1» before React 19.1), which
// differs between renders; Base UI puts it in ids and data-id.
const USE_ID = /_r_[0-9a-z]+_|:r[0-9a-z]+:|«r[0-9a-z]+»/g

function renderBubbleGroup(
  props: Partial<Record<keyof ComponentProps<typeof BubbleGroup>, unknown>> = {},
) {
  cleanup()
  render(
    <BubbleGroup
      data-subject
      {...({ children: 'BubbleGroup', ...props } as ComponentProps<typeof BubbleGroup>)}
    />,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="bubble-group"]')
}

function classesOfBubbleGroup(
  props: Partial<Record<keyof ComponentProps<typeof BubbleGroup>, unknown>> = {},
) {
  return renderBubbleGroup(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('BubbleGroup', () => {
  it('renders [data-slot="bubble-group"] with its classes', () => {
    expect(classesOfBubbleGroup()).toEqual(expect.arrayContaining([styles.bubbleGroup]))
  })

  it('appends a consumer className last', () => {
    renderBubbleGroup({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderBubble(props: Partial<Record<keyof ComponentProps<typeof Bubble>, unknown>> = {}) {
  cleanup()
  render(
    <Bubble
      data-subject
      {...({ children: 'Bubble', ...props } as ComponentProps<typeof Bubble>)}
    />,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="bubble"]')
}

function classesOfBubble(
  props: Partial<Record<keyof ComponentProps<typeof Bubble>, unknown>> = {},
) {
  return renderBubble(props)?.getAttribute('class')?.split(' ') ?? []
}

function htmlOfBubble(props: Partial<Record<keyof ComponentProps<typeof Bubble>, unknown>> = {}) {
  renderBubble(props)
  return document.body.innerHTML.replace(USE_ID, '')
}

function attributesOfBubble(
  props: Partial<Record<keyof ComponentProps<typeof Bubble>, unknown>> = {},
) {
  const element = renderBubble(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('Bubble', () => {
  it('renders [data-slot="bubble"] with its classes', () => {
    expect(classesOfBubble()).toEqual(
      expect.arrayContaining([styles.bubble, styles.variantDefault]),
    )
  })

  it.each([
    ['default', styles.variantDefault],
    ['secondary', styles.variantSecondary],
    ['muted', styles.variantMuted],
    ['tinted', styles.variantTinted],
    ['outline', styles.variantOutline],
    ['ghost', styles.variantGhost],
    ['destructive', styles.variantDestructive],
  ] as const)('variant %s applies its class', (value, className) => {
    expect(classesOfBubble({ variant: value })).toContain(className)
  })

  it('applies no group class for a null group', () => {
    const classes = classesOfBubble({ variant: null })
    expect(classes).toContain(styles.bubble)
    for (const className of [
      styles.variantDefault,
      styles.variantSecondary,
      styles.variantMuted,
      styles.variantTinted,
      styles.variantOutline,
      styles.variantGhost,
      styles.variantDestructive,
    ]) {
      expect(classes).not.toContain(className)
    }
  })

  it('renders the same with align="start" passed explicitly', () => {
    expect(attributesOfBubble({ align: 'start' })).toEqual(attributesOfBubble())
  })

  it('renders differently with align="end"', () => {
    expect(htmlOfBubble({ align: 'end' })).not.toBe(htmlOfBubble())
  })

  it('appends a consumer className last', () => {
    renderBubble({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Bubble data-subject variant="secondary">
        Bubble
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Bubble data-subject variant="muted">
        Bubble
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <Bubble data-subject variant="tinted" align="end">
        Bubble
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <Bubble data-subject variant="outline">
        Bubble
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(
      <Bubble data-subject variant="destructive">
        Bubble
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (7)", () => {
    cleanup()
    render(
      <Bubble data-subject variant="ghost">
        Bubble
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (8)", () => {
    cleanup()
    render(
      <BubbleGroup>
        <Bubble data-subject variant="secondary">
          Bubble
        </Bubble>
      </BubbleGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (9)", () => {
    cleanup()
    render(
      <BubbleGroup>
        <Bubble data-subject variant="tinted" align="end">
          Bubble
        </Bubble>
      </BubbleGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (10)", () => {
    cleanup()
    render(
      <Bubble data-subject variant="muted" align="end">
        Bubble
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (11)", () => {
    cleanup()
    render(
      <Bubble data-subject variant="secondary" align="end">
        Bubble
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (12)", () => {
    cleanup()
    render(
      <Bubble data-subject variant="tinted">
        Bubble
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (13)", () => {
    cleanup()
    render(
      <Bubble data-subject align="end">
        Bubble
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (14)", () => {
    cleanup()
    render(
      <BubbleGroup>
        <Bubble data-subject variant="outline" align="end">
          Bubble
        </Bubble>
      </BubbleGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderBubbleContent(
  props: Partial<Record<keyof ComponentProps<typeof BubbleContent>, unknown>> = {},
) {
  cleanup()
  render(
    <Bubble>
      <BubbleContent
        data-subject
        {...({ children: 'BubbleContent', ...props } as ComponentProps<typeof BubbleContent>)}
      />
    </Bubble>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="bubble-content"]')
}

function classesOfBubbleContent(
  props: Partial<Record<keyof ComponentProps<typeof BubbleContent>, unknown>> = {},
) {
  return renderBubbleContent(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('BubbleContent', () => {
  it('renders [data-slot="bubble-content"] with its classes', () => {
    expect(classesOfBubbleContent()).toEqual(expect.arrayContaining([styles.bubbleContent]))
  })

  it('appends a consumer className last', () => {
    renderBubbleContent({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Bubble variant="secondary">
        <BubbleContent data-subject>BubbleContent</BubbleContent>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Bubble variant="muted">
        <BubbleContent data-subject>BubbleContent</BubbleContent>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <Bubble variant="tinted" align="end">
        <BubbleContent data-subject>BubbleContent</BubbleContent>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <Bubble variant="outline">
        <BubbleContent data-subject>BubbleContent</BubbleContent>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(
      <Bubble variant="destructive">
        <BubbleContent data-subject>BubbleContent</BubbleContent>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (7)", () => {
    cleanup()
    render(
      <Bubble variant="ghost">
        <BubbleContent data-subject>BubbleContent</BubbleContent>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (8)", () => {
    cleanup()
    render(
      <BubbleGroup>
        <Bubble variant="secondary">
          <BubbleContent data-subject>BubbleContent</BubbleContent>
        </Bubble>
      </BubbleGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (9)", () => {
    cleanup()
    render(
      <BubbleGroup>
        <Bubble variant="tinted" align="end">
          <BubbleContent data-subject>BubbleContent</BubbleContent>
        </Bubble>
      </BubbleGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (10)", () => {
    cleanup()
    render(
      <Bubble variant="muted" align="end">
        <BubbleContent data-subject>BubbleContent</BubbleContent>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (11)", () => {
    cleanup()
    render(
      <Bubble variant="secondary" align="end">
        <BubbleContent data-subject>BubbleContent</BubbleContent>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (12)", () => {
    cleanup()
    render(
      <Bubble variant="tinted">
        <BubbleContent data-subject>BubbleContent</BubbleContent>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (13)", () => {
    cleanup()
    render(
      <Bubble align="end">
        <BubbleContent data-subject>BubbleContent</BubbleContent>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (14)", () => {
    cleanup()
    render(
      <BubbleGroup>
        <Bubble variant="outline" align="end">
          <BubbleContent data-subject>BubbleContent</BubbleContent>
        </Bubble>
      </BubbleGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderBubbleReactions(
  props: Partial<Record<keyof ComponentProps<typeof BubbleReactions>, unknown>> = {},
) {
  cleanup()
  render(
    <Bubble>
      <BubbleReactions
        data-subject
        {...({
          role: 'img',
          'aria-label': 'Reaction: thumbs up',
          children: 'BubbleReactions',
          ...props,
        } as ComponentProps<typeof BubbleReactions>)}
      />
    </Bubble>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="bubble-reactions"]')
}

function classesOfBubbleReactions(
  props: Partial<Record<keyof ComponentProps<typeof BubbleReactions>, unknown>> = {},
) {
  return renderBubbleReactions(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('BubbleReactions', () => {
  it('renders [data-slot="bubble-reactions"] with its classes', () => {
    expect(classesOfBubbleReactions()).toEqual(
      expect.arrayContaining([
        styles.bubbleReactions,
        styles.bubbleReactionsSideBottom,
        styles.bubbleReactionsAlignEnd,
      ]),
    )
  })

  it.each([
    ['top', styles.bubbleReactionsSideTop],
    ['bottom', styles.bubbleReactionsSideBottom],
  ] as const)('side %s applies its class', (value, className) => {
    expect(classesOfBubbleReactions({ side: value })).toContain(className)
  })

  it.each([
    ['start', styles.bubbleReactionsAlignStart],
    ['end', styles.bubbleReactionsAlignEnd],
  ] as const)('align %s applies its class', (value, className) => {
    expect(classesOfBubbleReactions({ align: value })).toContain(className)
  })

  it('applies no group class for a null group', () => {
    const classes = classesOfBubbleReactions({ side: null, align: null })
    expect(classes).toContain(styles.bubbleReactions)
    for (const className of [
      styles.bubbleReactionsSideTop,
      styles.bubbleReactionsSideBottom,
      styles.bubbleReactionsAlignStart,
      styles.bubbleReactionsAlignEnd,
    ]) {
      expect(classes).not.toContain(className)
    }
  })

  it('appends a consumer className last', () => {
    renderBubbleReactions({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Bubble variant="secondary" align="end">
        <BubbleReactions
          data-subject
          side="bottom"
          align="start"
          role="img"
          aria-label="Reactions: thumbs up, surprised"
        >
          BubbleReactions
        </BubbleReactions>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Bubble variant="tinted">
        <BubbleReactions
          data-subject
          side="bottom"
          align="end"
          role="img"
          aria-label="Reactions: thumbs up, surprised, fire, eyes, and 8 more"
        >
          BubbleReactions
        </BubbleReactions>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <Bubble variant="secondary">
        <BubbleReactions
          data-subject
          side="bottom"
          align="start"
          role="img"
          aria-label="Reaction: fire"
        >
          BubbleReactions
        </BubbleReactions>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <Bubble variant="secondary">
        <BubbleReactions
          data-subject
          side="bottom"
          align="start"
          role="img"
          aria-label="Reactions: thumbs up, surprised, fire, eyes"
        >
          BubbleReactions
        </BubbleReactions>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(
      <Bubble variant="secondary">
        <BubbleReactions
          data-subject
          side="top"
          align="start"
          role="img"
          aria-label="Reaction: fire"
        >
          BubbleReactions
        </BubbleReactions>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (7)", () => {
    cleanup()
    render(
      <Bubble variant="secondary">
        <BubbleReactions
          data-subject
          side="top"
          align="start"
          role="img"
          aria-label="Reactions: thumbs up, surprised, fire, eyes"
        >
          BubbleReactions
        </BubbleReactions>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (8)", () => {
    cleanup()
    render(
      <Bubble variant="muted">
        <BubbleReactions
          data-subject
          side="top"
          align="end"
          role="img"
          aria-label="Reaction: thumbs up"
        >
          BubbleReactions
        </BubbleReactions>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (9)", () => {
    cleanup()
    render(
      <Bubble variant="muted">
        <BubbleReactions
          data-subject
          side="top"
          align="end"
          role="img"
          aria-label="Reactions: thumbs up, surprised, fire, eyes"
        >
          BubbleReactions
        </BubbleReactions>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (10)", () => {
    cleanup()
    render(
      <Bubble>
        <BubbleReactions data-subject>BubbleReactions</BubbleReactions>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (11)", () => {
    cleanup()
    render(
      <Bubble align="end">
        <BubbleReactions data-subject align="start">
          BubbleReactions
        </BubbleReactions>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (12)", () => {
    cleanup()
    render(
      <Bubble variant="tinted">
        <BubbleReactions data-subject>BubbleReactions</BubbleReactions>
      </Bubble>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})
