// Generated by scripts/mirror from shadcn base-rhea/native-select. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { afterEach, describe, expect, it } from 'vitest'
import { NativeSelect, NativeSelectOptGroup, NativeSelectOption } from './NativeSelect'
import styles from './NativeSelect.module.scss'

// React's useId output (_r_1_, and :r1: or «r1» before React 19.1), which
// differs between renders; Base UI puts it in ids and data-id.
const USE_ID = /_r_[0-9a-z]+_|:r[0-9a-z]+:|«r[0-9a-z]+»/g

afterEach(cleanup)

function renderNativeSelect(
  props: Partial<Record<keyof ComponentProps<typeof NativeSelect>, unknown>> = {},
) {
  cleanup()
  render(
    <NativeSelect
      data-subject
      {...({ children: 'NativeSelect', ...props } as ComponentProps<typeof NativeSelect>)}
    />,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="native-select"]')
}

function classesOfNativeSelect(
  props: Partial<Record<keyof ComponentProps<typeof NativeSelect>, unknown>> = {},
) {
  return renderNativeSelect(props)?.getAttribute('class')?.split(' ') ?? []
}

function htmlOfNativeSelect(
  props: Partial<Record<keyof ComponentProps<typeof NativeSelect>, unknown>> = {},
) {
  renderNativeSelect(props)
  return document.body.innerHTML.replace(USE_ID, '')
}

function attributesOfNativeSelect(
  props: Partial<Record<keyof ComponentProps<typeof NativeSelect>, unknown>> = {},
) {
  const element = renderNativeSelect(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('NativeSelect', () => {
  it('renders [data-slot="native-select"] with its classes', () => {
    expect(classesOfNativeSelect()).toEqual(expect.arrayContaining([styles.nativeSelect]))
  })

  it('renders the same with size="default" passed explicitly', () => {
    expect(attributesOfNativeSelect({ size: 'default' })).toEqual(attributesOfNativeSelect())
  })

  it('renders differently with size="sm"', () => {
    expect(htmlOfNativeSelect({ size: 'sm' })).not.toBe(htmlOfNativeSelect())
  })

  it('appends a consumer className last', () => {
    renderNativeSelect({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <NativeSelect data-subject size="sm">
        NativeSelect
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <NativeSelect data-subject size="default">
        NativeSelect
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <NativeSelect data-subject id="native-select-country">
        NativeSelect
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <NativeSelect data-subject aria-invalid="true">
        NativeSelect
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderNativeSelectOption(
  props: Partial<Record<keyof ComponentProps<typeof NativeSelectOption>, unknown>> = {},
) {
  cleanup()
  render(
    <NativeSelect>
      <NativeSelectOption
        data-subject
        {...({ value: '', children: 'NativeSelectOption', ...props } as ComponentProps<
          typeof NativeSelectOption
        >)}
      />
    </NativeSelect>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="native-select-option"]')
}

function classesOfNativeSelectOption(
  props: Partial<Record<keyof ComponentProps<typeof NativeSelectOption>, unknown>> = {},
) {
  return renderNativeSelectOption(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('NativeSelectOption', () => {
  it('renders [data-slot="native-select-option"] with its classes', () => {
    expect(classesOfNativeSelectOption()).toEqual(
      expect.arrayContaining([styles.nativeSelectOption]),
    )
  })

  it('appends a consumer className last', () => {
    renderNativeSelectOption({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <NativeSelect>
        <NativeSelectOption data-subject value="apple">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <NativeSelect>
        <NativeSelectOption data-subject value="banana">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <NativeSelect>
        <NativeSelectOption data-subject value="blueberry">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <NativeSelect>
        <NativeSelectOption data-subject value="grapes">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(
      <NativeSelect>
        <NativeSelectOption data-subject value="pineapple">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (7)", () => {
    cleanup()
    render(
      <NativeSelect>
        <NativeSelectOptGroup label="Fruits">
          <NativeSelectOption data-subject value="apple">
            NativeSelectOption
          </NativeSelectOption>
        </NativeSelectOptGroup>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (8)", () => {
    cleanup()
    render(
      <NativeSelect>
        <NativeSelectOptGroup label="Fruits">
          <NativeSelectOption data-subject value="banana">
            NativeSelectOption
          </NativeSelectOption>
        </NativeSelectOptGroup>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (9)", () => {
    cleanup()
    render(
      <NativeSelect>
        <NativeSelectOptGroup label="Fruits">
          <NativeSelectOption data-subject value="blueberry">
            NativeSelectOption
          </NativeSelectOption>
        </NativeSelectOptGroup>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (10)", () => {
    cleanup()
    render(
      <NativeSelect>
        <NativeSelectOptGroup label="Vegetables">
          <NativeSelectOption data-subject value="carrot">
            NativeSelectOption
          </NativeSelectOption>
        </NativeSelectOptGroup>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (11)", () => {
    cleanup()
    render(
      <NativeSelect>
        <NativeSelectOptGroup label="Vegetables">
          <NativeSelectOption data-subject value="broccoli">
            NativeSelectOption
          </NativeSelectOption>
        </NativeSelectOptGroup>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (12)", () => {
    cleanup()
    render(
      <NativeSelect>
        <NativeSelectOptGroup label="Vegetables">
          <NativeSelectOption data-subject value="spinach">
            NativeSelectOption
          </NativeSelectOption>
        </NativeSelectOptGroup>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (13)", () => {
    cleanup()
    render(
      <NativeSelect size="sm">
        <NativeSelectOption data-subject value="">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (14)", () => {
    cleanup()
    render(
      <NativeSelect size="sm">
        <NativeSelectOption data-subject value="apple">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (15)", () => {
    cleanup()
    render(
      <NativeSelect size="sm">
        <NativeSelectOption data-subject value="banana">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (16)", () => {
    cleanup()
    render(
      <NativeSelect size="sm">
        <NativeSelectOption data-subject value="blueberry">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (17)", () => {
    cleanup()
    render(
      <NativeSelect size="default">
        <NativeSelectOption data-subject value="">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (18)", () => {
    cleanup()
    render(
      <NativeSelect size="default">
        <NativeSelectOption data-subject value="apple">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (19)", () => {
    cleanup()
    render(
      <NativeSelect size="default">
        <NativeSelectOption data-subject value="banana">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (20)", () => {
    cleanup()
    render(
      <NativeSelect size="default">
        <NativeSelectOption data-subject value="blueberry">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (21)", () => {
    cleanup()
    render(
      <NativeSelect id="native-select-country">
        <NativeSelectOption data-subject value="">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (22)", () => {
    cleanup()
    render(
      <NativeSelect id="native-select-country">
        <NativeSelectOption data-subject value="us">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (23)", () => {
    cleanup()
    render(
      <NativeSelect id="native-select-country">
        <NativeSelectOption data-subject value="uk">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (24)", () => {
    cleanup()
    render(
      <NativeSelect id="native-select-country">
        <NativeSelectOption data-subject value="ca">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (25)", () => {
    cleanup()
    render(
      <NativeSelect id="native-select-country">
        <NativeSelectOption data-subject value="au">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (26)", () => {
    cleanup()
    render(
      <NativeSelect aria-invalid="true">
        <NativeSelectOption data-subject value="">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (27)", () => {
    cleanup()
    render(
      <NativeSelect aria-invalid="true">
        <NativeSelectOption data-subject value="apple">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (28)", () => {
    cleanup()
    render(
      <NativeSelect aria-invalid="true">
        <NativeSelectOption data-subject value="banana">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (29)", () => {
    cleanup()
    render(
      <NativeSelect aria-invalid="true">
        <NativeSelectOption data-subject value="blueberry">
          NativeSelectOption
        </NativeSelectOption>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderNativeSelectOptGroup(
  props: Partial<Record<keyof ComponentProps<typeof NativeSelectOptGroup>, unknown>> = {},
) {
  cleanup()
  render(
    <NativeSelect>
      <NativeSelectOptGroup
        data-subject
        {...({ label: 'Fruits', children: 'NativeSelectOptGroup', ...props } as ComponentProps<
          typeof NativeSelectOptGroup
        >)}
      />
    </NativeSelect>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="native-select-optgroup"]')
}

function classesOfNativeSelectOptGroup(
  props: Partial<Record<keyof ComponentProps<typeof NativeSelectOptGroup>, unknown>> = {},
) {
  return renderNativeSelectOptGroup(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('NativeSelectOptGroup', () => {
  it('renders [data-slot="native-select-optgroup"] with its classes', () => {
    expect(classesOfNativeSelectOptGroup()).toEqual(
      expect.arrayContaining([styles.nativeSelectOptgroup]),
    )
  })

  it('appends a consumer className last', () => {
    renderNativeSelectOptGroup({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <NativeSelect>
        <NativeSelectOptGroup data-subject label="Vegetables">
          NativeSelectOptGroup
        </NativeSelectOptGroup>
      </NativeSelect>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})
