// Generated by scripts/mirror from shadcn base-lyra/toggle. Do not edit.

'use client'

import { Toggle as TogglePrimitive } from '@base-ui/react/toggle'
import { type ClassValue, clsx } from 'clsx'
import styles from './Toggle.module.scss'

const toggleVariantClasses = {
  variant: {
    default: styles.variantDefault,
    outline: styles.variantOutline,
  },
  size: {
    default: styles.sizeDefault,
    sm: styles.sizeSm,
    lg: styles.sizeLg,
  },
} as const

type ToggleVariantProps = {
  [Group in keyof typeof toggleVariantClasses]?: keyof (typeof toggleVariantClasses)[Group] | null
}

function toggleVariants({
  variant = 'default',
  size = 'default',
  className,
}: ToggleVariantProps & { className?: ClassValue } = {}) {
  return clsx(
    styles.toggle,
    variant && toggleVariantClasses.variant[variant],
    size && toggleVariantClasses.size[size],
    className,
  )
}

function Toggle({
  className,
  variant = 'default',
  size = 'default',
  ...props
}: TogglePrimitive.Props & ToggleVariantProps) {
  return (
    <TogglePrimitive
      data-slot="toggle"
      className={toggleVariants({ variant, size, className })}
      {...props}
    />
  )
}

export { Toggle, toggleVariants }
