// Generated by scripts/mirror from shadcn base-vega/textarea. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { describe, expect, it } from 'vitest'
import { Textarea } from './Textarea'
import styles from './Textarea.module.scss'

function renderTextarea(props: Partial<ComponentProps<typeof Textarea>> = {}) {
  cleanup()
  render(
    <Textarea
      placeholder="Type your message here."
      {...(props as ComponentProps<typeof Textarea>)}
    />,
  )
  return document.querySelector('[data-slot="textarea"]')?.getAttribute('class')?.split(' ') ?? []
}

describe('Textarea', () => {
  it('renders [data-slot="textarea"] with its classes', () => {
    expect(renderTextarea()).toEqual(expect.arrayContaining([styles.textarea]))
  })

  it('appends a consumer className last', () => {
    expect(renderTextarea({ className: 'consumer' }).at(-1)).toBe('consumer')
  })
})
