// Generated by scripts/mirror from shadcn base-sera/button. Do not edit.

import { Button as ButtonPrimitive } from '@base-ui/react/button'
import { type ClassValue, clsx } from 'clsx'
import styles from './Button.module.scss'

const buttonVariantClasses = {
  variant: {
    default: styles.variantDefault,
    outline: styles.variantOutline,
    secondary: styles.variantSecondary,
    ghost: styles.variantGhost,
    destructive: styles.variantDestructive,
    link: styles.variantLink,
  },
  size: {
    default: styles.sizeDefault,
    xs: styles.sizeXs,
    sm: styles.sizeSm,
    lg: styles.sizeLg,
    icon: styles.sizeIcon,
    'icon-xs': styles.sizeIconXs,
    'icon-sm': styles.sizeIconSm,
    'icon-lg': styles.sizeIconLg,
  },
} as const

type ButtonVariantProps = {
  [Group in keyof typeof buttonVariantClasses]?: keyof (typeof buttonVariantClasses)[Group] | null
}

function buttonVariants({
  variant = 'default',
  size = 'default',
  className,
}: ButtonVariantProps & { className?: ClassValue } = {}) {
  return clsx(
    styles.button,
    variant && buttonVariantClasses.variant[variant],
    size && buttonVariantClasses.size[size],
    className,
  )
}

function Button({
  className,
  variant = 'default',
  size = 'default',
  ...props
}: ButtonPrimitive.Props & ButtonVariantProps) {
  return (
    <ButtonPrimitive
      data-slot="button"
      className={buttonVariants({ variant, size, className })}
      {...props}
    />
  )
}

export { Button, buttonVariants }
