// Generated by scripts/mirror from shadcn base-mira/empty. Do not edit.

import { type ClassValue, clsx } from 'clsx'
import styles from './Empty.module.scss'

function Empty({ className, ...props }: React.ComponentProps<'div'>) {
  return <div data-slot="empty" className={clsx(styles.empty, className)} {...props} />
}

function EmptyHeader({ className, ...props }: React.ComponentProps<'div'>) {
  return <div data-slot="empty-header" className={clsx(styles.emptyHeader, className)} {...props} />
}

const emptyMediaVariantClasses = {
  variant: {
    default: styles.emptyMediaVariantDefault,
    icon: styles.emptyMediaVariantIcon,
  },
} as const

type EmptyMediaVariantProps = {
  [Group in keyof typeof emptyMediaVariantClasses]?:
    | keyof (typeof emptyMediaVariantClasses)[Group]
    | null
}

function emptyMediaVariants({
  variant = 'default',
  className,
}: EmptyMediaVariantProps & { className?: ClassValue } = {}) {
  return clsx(styles.emptyMedia, variant && emptyMediaVariantClasses.variant[variant], className)
}

function EmptyMedia({
  className,
  variant = 'default',
  ...props
}: React.ComponentProps<'div'> & EmptyMediaVariantProps) {
  return (
    <div
      data-slot="empty-icon"
      data-variant={variant}
      className={emptyMediaVariants({ variant, className })}
      {...props}
    />
  )
}

function EmptyTitle({ className, ...props }: React.ComponentProps<'div'>) {
  return <div data-slot="empty-title" className={clsx(styles.emptyTitle, className)} {...props} />
}

function EmptyDescription({ className, ...props }: React.ComponentProps<'p'>) {
  return (
    <div
      data-slot="empty-description"
      className={clsx(styles.emptyDescription, className)}
      {...props}
    />
  )
}

function EmptyContent({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div data-slot="empty-content" className={clsx(styles.emptyContent, className)} {...props} />
  )
}

export { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle }
