// Generated by scripts/mirror from shadcn base-mira/empty. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { afterEach, describe, expect, it } from 'vitest'
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from './Empty'
import styles from './Empty.module.scss'

afterEach(cleanup)

function renderEmpty(props: Partial<Record<keyof ComponentProps<typeof Empty>, unknown>> = {}) {
  cleanup()
  render(
    <Empty data-subject {...({ children: 'Empty', ...props } as ComponentProps<typeof Empty>)} />,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="empty"]')
}

function classesOfEmpty(props: Partial<Record<keyof ComponentProps<typeof Empty>, unknown>> = {}) {
  return renderEmpty(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('Empty', () => {
  it('renders [data-slot="empty"] with its classes', () => {
    expect(classesOfEmpty()).toEqual(expect.arrayContaining([styles.empty]))
  })

  it('appends a consumer className last', () => {
    renderEmpty({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderEmptyHeader(
  props: Partial<Record<keyof ComponentProps<typeof EmptyHeader>, unknown>> = {},
) {
  cleanup()
  render(
    <Empty>
      <EmptyHeader
        data-subject
        {...({ children: 'EmptyHeader', ...props } as ComponentProps<typeof EmptyHeader>)}
      />
    </Empty>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="empty-header"]')
}

function classesOfEmptyHeader(
  props: Partial<Record<keyof ComponentProps<typeof EmptyHeader>, unknown>> = {},
) {
  return renderEmptyHeader(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('EmptyHeader', () => {
  it('renders [data-slot="empty-header"] with its classes', () => {
    expect(classesOfEmptyHeader()).toEqual(expect.arrayContaining([styles.emptyHeader]))
  })

  it('appends a consumer className last', () => {
    renderEmptyHeader({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderEmptyMedia(
  props: Partial<Record<keyof ComponentProps<typeof EmptyMedia>, unknown>> = {},
) {
  cleanup()
  render(
    <Empty>
      <EmptyHeader>
        <EmptyMedia
          data-subject
          {...({ children: 'EmptyMedia', ...props } as ComponentProps<typeof EmptyMedia>)}
        />
      </EmptyHeader>
    </Empty>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="empty-icon"]')
}

function classesOfEmptyMedia(
  props: Partial<Record<keyof ComponentProps<typeof EmptyMedia>, unknown>> = {},
) {
  return renderEmptyMedia(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('EmptyMedia', () => {
  it('renders [data-slot="empty-icon"] with its classes', () => {
    expect(classesOfEmptyMedia()).toEqual(
      expect.arrayContaining([styles.emptyMedia, styles.emptyMediaVariantDefault]),
    )
  })

  it.each([
    ['default', styles.emptyMediaVariantDefault],
    ['icon', styles.emptyMediaVariantIcon],
  ] as const)('variant %s applies its class', (value, className) => {
    expect(classesOfEmptyMedia({ variant: value })).toContain(className)
  })

  it('applies no group class for a null group', () => {
    const classes = classesOfEmptyMedia({ variant: null })
    expect(classes).toContain(styles.emptyMedia)
    for (const className of [styles.emptyMediaVariantDefault, styles.emptyMediaVariantIcon]) {
      expect(classes).not.toContain(className)
    }
  })

  it('appends a consumer className last', () => {
    renderEmptyMedia({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderEmptyTitle(
  props: Partial<Record<keyof ComponentProps<typeof EmptyTitle>, unknown>> = {},
) {
  cleanup()
  render(
    <Empty>
      <EmptyHeader>
        <EmptyTitle
          data-subject
          {...({ children: 'EmptyTitle', ...props } as ComponentProps<typeof EmptyTitle>)}
        />
      </EmptyHeader>
    </Empty>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="empty-title"]')
}

function classesOfEmptyTitle(
  props: Partial<Record<keyof ComponentProps<typeof EmptyTitle>, unknown>> = {},
) {
  return renderEmptyTitle(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('EmptyTitle', () => {
  it('renders [data-slot="empty-title"] with its classes', () => {
    expect(classesOfEmptyTitle()).toEqual(expect.arrayContaining([styles.emptyTitle]))
  })

  it('appends a consumer className last', () => {
    renderEmptyTitle({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderEmptyDescription(
  props: Partial<Record<keyof ComponentProps<typeof EmptyDescription>, unknown>> = {},
) {
  cleanup()
  render(
    <Empty>
      <EmptyHeader>
        <EmptyDescription
          data-subject
          {...({ children: 'EmptyDescription', ...props } as ComponentProps<
            typeof EmptyDescription
          >)}
        />
      </EmptyHeader>
    </Empty>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="empty-description"]')
}

function classesOfEmptyDescription(
  props: Partial<Record<keyof ComponentProps<typeof EmptyDescription>, unknown>> = {},
) {
  return renderEmptyDescription(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('EmptyDescription', () => {
  it('renders [data-slot="empty-description"] with its classes', () => {
    expect(classesOfEmptyDescription()).toEqual(expect.arrayContaining([styles.emptyDescription]))
  })

  it('appends a consumer className last', () => {
    renderEmptyDescription({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Empty>
        <EmptyContent>
          <EmptyDescription data-subject>EmptyDescription</EmptyDescription>
        </EmptyContent>
      </Empty>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderEmptyContent(
  props: Partial<Record<keyof ComponentProps<typeof EmptyContent>, unknown>> = {},
) {
  cleanup()
  render(
    <Empty>
      <EmptyContent
        data-subject
        {...({ children: 'EmptyContent', ...props } as ComponentProps<typeof EmptyContent>)}
      />
    </Empty>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="empty-content"]')
}

function classesOfEmptyContent(
  props: Partial<Record<keyof ComponentProps<typeof EmptyContent>, unknown>> = {},
) {
  return renderEmptyContent(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('EmptyContent', () => {
  it('renders [data-slot="empty-content"] with its classes', () => {
    expect(classesOfEmptyContent()).toEqual(expect.arrayContaining([styles.emptyContent]))
  })

  it('appends a consumer className last', () => {
    renderEmptyContent({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})
