// Generated by scripts/mirror from shadcn base-vega/aspect-ratio. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { describe, expect, it } from 'vitest'
import { AspectRatio } from './AspectRatio'
import styles from './AspectRatio.module.scss'

function renderAspectRatio(
  props: Partial<Record<keyof ComponentProps<typeof AspectRatio>, unknown>> = {},
) {
  cleanup()
  render(
    <AspectRatio
      data-testid="subject"
      {...({ children: 'AspectRatio', ...props } as ComponentProps<typeof AspectRatio>)}
    />,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="aspect-ratio"]')
}

function classesOfAspectRatio(
  props: Partial<Record<keyof ComponentProps<typeof AspectRatio>, unknown>> = {},
) {
  return renderAspectRatio(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('AspectRatio', () => {
  it('renders [data-slot="aspect-ratio"] with its classes', () => {
    expect(classesOfAspectRatio()).toEqual(expect.arrayContaining([styles.aspectRatio]))
  })

  it('appends a consumer className last', () => {
    renderAspectRatio({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})
