// Generated by scripts/mirror from shadcn base-rhea/separator. Do not edit.

'use client'

import { Separator as SeparatorPrimitive } from '@base-ui/react/separator'
import { clsx } from 'clsx'
import styles from './Separator.module.scss'

function Separator({ className, orientation = 'horizontal', ...props }: SeparatorPrimitive.Props) {
  return (
    <SeparatorPrimitive
      data-slot="separator"
      orientation={orientation}
      className={clsx(styles.separator, className)}
      {...props}
    />
  )
}

export { Separator }
