// Generated by scripts/mirror from shadcn base-mira/bubble. Do not edit.

import { mergeProps } from '@base-ui/react/merge-props'
import { useRender } from '@base-ui/react/use-render'
import { type ClassValue, clsx } from 'clsx'
import type * as React from 'react'
import styles from './Bubble.module.scss'

function BubbleGroup({ className, ...props }: React.ComponentProps<'div'>) {
  return <div data-slot="bubble-group" className={clsx(styles.bubbleGroup, className)} {...props} />
}

const bubbleVariantClasses = {
  variant: {
    default: styles.variantDefault,
    secondary: styles.variantSecondary,
    muted: styles.variantMuted,
    tinted: styles.variantTinted,
    outline: styles.variantOutline,
    ghost: styles.variantGhost,
    destructive: styles.variantDestructive,
  },
} as const

type BubbleVariantProps = {
  [Group in keyof typeof bubbleVariantClasses]?: keyof (typeof bubbleVariantClasses)[Group] | null
}

function bubbleVariants({
  variant = 'default',
  className,
}: BubbleVariantProps & { className?: ClassValue } = {}) {
  return clsx(styles.bubble, variant && bubbleVariantClasses.variant[variant], className)
}

function Bubble({
  variant = 'default',
  align = 'start',
  className,
  ...props
}: React.ComponentProps<'div'> &
  BubbleVariantProps & {
    align?: 'start' | 'end'
  }) {
  return (
    <div
      data-slot="bubble"
      data-variant={variant}
      data-align={align}
      className={clsx(bubbleVariants({ variant }), className)}
      {...props}
    />
  )
}

function BubbleContent({ className, render, ...props }: useRender.ComponentProps<'div'>) {
  return useRender({
    defaultTagName: 'div',
    props: mergeProps<'div'>(
      {
        className: clsx(styles.bubbleContent, className),
      },
      props,
    ),
    render,
    state: {
      slot: 'bubble-content',
    },
  })
}

const bubbleReactionsVariantClasses = {
  side: {
    top: styles.bubbleReactionsSideTop,
    bottom: styles.bubbleReactionsSideBottom,
  },
  align: {
    start: styles.bubbleReactionsAlignStart,
    end: styles.bubbleReactionsAlignEnd,
  },
} as const

type BubbleReactionsVariantProps = {
  [Group in keyof typeof bubbleReactionsVariantClasses]?:
    | keyof (typeof bubbleReactionsVariantClasses)[Group]
    | null
}

function bubbleReactionsVariants({
  side = 'bottom',
  align = 'end',
  className,
}: BubbleReactionsVariantProps & { className?: ClassValue } = {}) {
  return clsx(
    styles.bubbleReactions,
    side && bubbleReactionsVariantClasses.side[side],
    align && bubbleReactionsVariantClasses.align[align],
    className,
  )
}

function BubbleReactions({
  side = 'bottom',
  align = 'end',
  className,
  ...props
}: React.ComponentProps<'div'> & {
  align?: 'start' | 'end'
  side?: 'top' | 'bottom'
}) {
  return (
    <div
      data-slot="bubble-reactions"
      data-align={align}
      data-side={side}
      className={clsx(bubbleReactionsVariants({ side, align }), className)}
      {...props}
    />
  )
}

export { Bubble, BubbleContent, BubbleGroup, BubbleReactions }
