// Generated by scripts/mirror from shadcn base-mira/tooltip. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { afterEach, describe, expect, it } from 'vitest'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from './Tooltip'
import styles from './Tooltip.module.scss'

// React's useId output (_r_1_, and :r1: or «r1» before React 19.1), which
// differs between renders; Base UI puts it in ids and data-id.
const USE_ID = /_r_[0-9a-z]+_|:r[0-9a-z]+:|«r[0-9a-z]+»/g

afterEach(cleanup)

describe('TooltipProvider', () => {
  it('renders its children', () => {
    cleanup()
    render(
      <Tooltip defaultOpen>
        <TooltipProvider>
          <i data-testid="child" />
        </TooltipProvider>
      </Tooltip>,
    )
    expect(document.querySelector('[data-testid="child"]')).not.toBeNull()
  })
})

describe('Tooltip', () => {
  it('renders its children', () => {
    cleanup()
    render(
      <Tooltip>
        <i data-testid="child" />
      </Tooltip>,
    )
    expect(document.querySelector('[data-testid="child"]')).not.toBeNull()
  })
})

function renderTooltipTrigger(
  props: Partial<Record<keyof ComponentProps<typeof TooltipTrigger>, unknown>> = {},
) {
  cleanup()
  render(
    <Tooltip defaultOpen>
      <TooltipTrigger
        data-subject
        {...({ children: 'TooltipTrigger', ...props } as ComponentProps<typeof TooltipTrigger>)}
      />
    </Tooltip>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="tooltip-trigger"]')
}

describe('TooltipTrigger', () => {
  it('appends a consumer className last', () => {
    renderTooltipTrigger({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderTooltipContent(
  props: Partial<Record<keyof ComponentProps<typeof TooltipContent>, unknown>> = {},
) {
  cleanup()
  render(
    <Tooltip defaultOpen>
      <TooltipTrigger>TooltipTrigger</TooltipTrigger>
      <TooltipContent
        data-subject
        {...({ children: 'TooltipContent', ...props } as ComponentProps<typeof TooltipContent>)}
      />
    </Tooltip>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="tooltip-content"]')
}

function classesOfTooltipContent(
  props: Partial<Record<keyof ComponentProps<typeof TooltipContent>, unknown>> = {},
) {
  return renderTooltipContent(props)?.getAttribute('class')?.split(' ') ?? []
}

function htmlOfTooltipContent(
  props: Partial<Record<keyof ComponentProps<typeof TooltipContent>, unknown>> = {},
) {
  renderTooltipContent(props)
  return document.body.innerHTML.replace(USE_ID, '')
}

function attributesOfTooltipContent(
  props: Partial<Record<keyof ComponentProps<typeof TooltipContent>, unknown>> = {},
) {
  const element = renderTooltipContent(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('TooltipContent', () => {
  it('renders [data-slot="tooltip-content"] with its classes', () => {
    expect(classesOfTooltipContent()).toEqual(expect.arrayContaining([styles.tooltipContent]))
  })

  it('renders the same with side="top" passed explicitly', () => {
    expect(attributesOfTooltipContent({ side: 'top' })).toEqual(attributesOfTooltipContent())
  })

  it('renders the same with sideOffset=4 passed explicitly', () => {
    expect(attributesOfTooltipContent({ sideOffset: 4 })).toEqual(attributesOfTooltipContent())
  })

  it('renders the same with align="center" passed explicitly', () => {
    expect(attributesOfTooltipContent({ align: 'center' })).toEqual(attributesOfTooltipContent())
  })

  it('renders the same with alignOffset=0 passed explicitly', () => {
    expect(attributesOfTooltipContent({ alignOffset: 0 })).toEqual(attributesOfTooltipContent())
  })

  it('renders differently with side="left"', () => {
    expect(htmlOfTooltipContent({ side: 'left' })).not.toBe(htmlOfTooltipContent())
  })

  it('renders differently with side="right"', () => {
    expect(htmlOfTooltipContent({ side: 'right' })).not.toBe(htmlOfTooltipContent())
  })

  it('renders differently with side="bottom"', () => {
    expect(htmlOfTooltipContent({ side: 'bottom' })).not.toBe(htmlOfTooltipContent())
  })

  it('renders differently with side="inline-start"', () => {
    expect(htmlOfTooltipContent({ side: 'inline-start' })).not.toBe(htmlOfTooltipContent())
  })

  it('renders differently with side="inline-end"', () => {
    expect(htmlOfTooltipContent({ side: 'inline-end' })).not.toBe(htmlOfTooltipContent())
  })

  it('renders differently with align="start"', () => {
    expect(htmlOfTooltipContent({ align: 'start' })).not.toBe(htmlOfTooltipContent())
  })

  it('renders differently with align="end"', () => {
    expect(htmlOfTooltipContent({ align: 'end' })).not.toBe(htmlOfTooltipContent())
  })

  it('appends a consumer className last', () => {
    renderTooltipContent({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})
