// Generated by scripts/mirror from shadcn base-vega/collapsible. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { describe, expect, it } from 'vitest'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from './Collapsible'

function renderCollapsible(props: Partial<ComponentProps<typeof Collapsible>> = {}) {
  cleanup()
  render(<Collapsible data-testid="subject" {...(props as ComponentProps<typeof Collapsible>)} />)
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="collapsible"]')
}

describe('Collapsible', () => {
  it('appends a consumer className last', () => {
    renderCollapsible({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderCollapsibleTrigger(props: Partial<ComponentProps<typeof CollapsibleTrigger>> = {}) {
  cleanup()
  render(
    <Collapsible defaultOpen>
      <CollapsibleTrigger
        data-testid="subject"
        {...(props as ComponentProps<typeof CollapsibleTrigger>)}
      />
    </Collapsible>,
  )
  return document
    .querySelector('[data-testid="subject"]')
    ?.closest('[data-slot="collapsible-trigger"]')
}

describe('CollapsibleTrigger', () => {
  it('appends a consumer className last', () => {
    renderCollapsibleTrigger({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderCollapsibleContent(props: Partial<ComponentProps<typeof CollapsibleContent>> = {}) {
  cleanup()
  render(
    <Collapsible defaultOpen>
      <CollapsibleContent
        data-testid="subject"
        {...({ keepMounted: true, ...props } as ComponentProps<typeof CollapsibleContent>)}
      />
    </Collapsible>,
  )
  return document
    .querySelector('[data-testid="subject"]')
    ?.closest('[data-slot="collapsible-content"]')
}

describe('CollapsibleContent', () => {
  it('appends a consumer className last', () => {
    renderCollapsibleContent({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})
