// Generated by scripts/mirror from shadcn base-vega/dialog. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { describe, expect, it } from 'vitest'
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogPortal,
  DialogTitle,
  DialogTrigger,
} from './Dialog'
import styles from './Dialog.module.scss'

// React's useId output (_r_1_, and :r1: or «r1» before React 19.1), which
// differs between renders; Base UI puts it in ids and data-id.
const USE_ID = /_r_[0-9a-z]+_|:r[0-9a-z]+:|«r[0-9a-z]+»/g

describe('Dialog', () => {
  it('renders its children', () => {
    cleanup()
    render(
      <Dialog>
        <i data-testid="child" />
      </Dialog>,
    )
    expect(document.querySelector('[data-testid="child"]')).not.toBeNull()
  })
})

function renderDialogTrigger(
  props: Partial<Record<keyof ComponentProps<typeof DialogTrigger>, unknown>> = {},
) {
  cleanup()
  render(
    <Dialog defaultOpen>
      <DialogTrigger
        data-testid="subject"
        {...({ children: 'DialogTrigger', ...props } as ComponentProps<typeof DialogTrigger>)}
      />
    </Dialog>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="dialog-trigger"]')
}

describe('DialogTrigger', () => {
  it('appends a consumer className last', () => {
    renderDialogTrigger({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Dialog defaultOpen>
        <DialogTrigger>DialogTrigger</DialogTrigger>
        <DialogTrigger data-testid="subject">DialogTrigger</DialogTrigger>
      </Dialog>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

function renderDialogPortal(
  props: Partial<Record<keyof ComponentProps<typeof DialogPortal>, unknown>> = {},
) {
  cleanup()
  render(
    <Dialog defaultOpen>
      <DialogContent>
        <DialogPortal
          data-testid="subject"
          {...({ keepMounted: true, children: 'DialogPortal', ...props } as ComponentProps<
            typeof DialogPortal
          >)}
        />
      </DialogContent>
    </Dialog>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="dialog-portal"]')
}

describe('DialogPortal', () => {
  it('appends a consumer className last', () => {
    renderDialogPortal({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderDialogClose(
  props: Partial<Record<keyof ComponentProps<typeof DialogClose>, unknown>> = {},
) {
  cleanup()
  render(
    <Dialog defaultOpen>
      <DialogContent>
        <DialogFooter>
          <DialogClose
            data-testid="subject"
            {...({ children: 'DialogClose', ...props } as ComponentProps<typeof DialogClose>)}
          />
        </DialogFooter>
      </DialogContent>
    </Dialog>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="dialog-close"]')
}

describe('DialogClose', () => {
  it('appends a consumer className last', () => {
    renderDialogClose({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Dialog defaultOpen>
        <DialogTrigger>DialogTrigger</DialogTrigger>
        <DialogContent>
          <DialogFooter>
            <DialogClose data-testid="subject">DialogClose</DialogClose>
          </DialogFooter>
        </DialogContent>
      </Dialog>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Dialog defaultOpen>
        <DialogTrigger>DialogTrigger</DialogTrigger>
        <DialogContent showCloseButton={false}>
          <DialogFooter>
            <DialogClose data-testid="subject">DialogClose</DialogClose>
          </DialogFooter>
        </DialogContent>
      </Dialog>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

function renderDialogOverlay(
  props: Partial<Record<keyof ComponentProps<typeof DialogOverlay>, unknown>> = {},
) {
  cleanup()
  render(
    <Dialog defaultOpen>
      <DialogContent>
        <DialogOverlay
          data-testid="subject"
          {...({ children: 'DialogOverlay', ...props } as ComponentProps<typeof DialogOverlay>)}
        />
      </DialogContent>
    </Dialog>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="dialog-overlay"]')
}

function classesOfDialogOverlay(
  props: Partial<Record<keyof ComponentProps<typeof DialogOverlay>, unknown>> = {},
) {
  return renderDialogOverlay(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('DialogOverlay', () => {
  it('renders [data-slot="dialog-overlay"] with its classes', () => {
    expect(classesOfDialogOverlay()).toEqual(expect.arrayContaining([styles.dialogOverlay]))
  })

  it('appends a consumer className last', () => {
    renderDialogOverlay({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderDialogContent(
  props: Partial<Record<keyof ComponentProps<typeof DialogContent>, unknown>> = {},
) {
  cleanup()
  render(
    <Dialog defaultOpen>
      <DialogContent
        data-testid="subject"
        {...({ children: 'DialogContent', ...props } as ComponentProps<typeof DialogContent>)}
      />
    </Dialog>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="dialog-content"]')
}

function classesOfDialogContent(
  props: Partial<Record<keyof ComponentProps<typeof DialogContent>, unknown>> = {},
) {
  return renderDialogContent(props)?.getAttribute('class')?.split(' ') ?? []
}

function attributesOfDialogContent(
  props: Partial<Record<keyof ComponentProps<typeof DialogContent>, unknown>> = {},
) {
  const element = renderDialogContent(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('DialogContent', () => {
  it('renders [data-slot="dialog-content"] with its classes', () => {
    expect(classesOfDialogContent()).toEqual(expect.arrayContaining([styles.dialogContent]))
  })

  it('renders the same with showCloseButton=true passed explicitly', () => {
    expect(attributesOfDialogContent({ showCloseButton: true })).toEqual(
      attributesOfDialogContent(),
    )
  })

  it('renders with showCloseButton=false', () => {
    expect(renderDialogContent({ showCloseButton: false })).toBeTruthy()
  })

  it('appends a consumer className last', () => {
    renderDialogContent({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Dialog defaultOpen>
        <DialogTrigger>DialogTrigger</DialogTrigger>
        <DialogContent data-testid="subject">DialogContent</DialogContent>
      </Dialog>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Dialog defaultOpen>
        <DialogTrigger>DialogTrigger</DialogTrigger>
        <DialogContent data-testid="subject" showCloseButton={false}>
          DialogContent
        </DialogContent>
      </Dialog>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

function renderDialogHeader(
  props: Partial<Record<keyof ComponentProps<typeof DialogHeader>, unknown>> = {},
) {
  cleanup()
  render(
    <Dialog defaultOpen>
      <DialogContent>
        <DialogHeader
          data-testid="subject"
          {...({ children: 'DialogHeader', ...props } as ComponentProps<typeof DialogHeader>)}
        />
      </DialogContent>
    </Dialog>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="dialog-header"]')
}

function classesOfDialogHeader(
  props: Partial<Record<keyof ComponentProps<typeof DialogHeader>, unknown>> = {},
) {
  return renderDialogHeader(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('DialogHeader', () => {
  it('renders [data-slot="dialog-header"] with its classes', () => {
    expect(classesOfDialogHeader()).toEqual(expect.arrayContaining([styles.dialogHeader]))
  })

  it('appends a consumer className last', () => {
    renderDialogHeader({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Dialog defaultOpen>
        <DialogTrigger>DialogTrigger</DialogTrigger>
        <DialogContent>
          <DialogHeader data-testid="subject">DialogHeader</DialogHeader>
        </DialogContent>
      </Dialog>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Dialog defaultOpen>
        <DialogTrigger>DialogTrigger</DialogTrigger>
        <DialogContent showCloseButton={false}>
          <DialogHeader data-testid="subject">DialogHeader</DialogHeader>
        </DialogContent>
      </Dialog>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

function renderDialogFooter(
  props: Partial<Record<keyof ComponentProps<typeof DialogFooter>, unknown>> = {},
) {
  cleanup()
  render(
    <Dialog defaultOpen>
      <DialogContent>
        <DialogFooter
          data-testid="subject"
          {...({ children: 'DialogFooter', ...props } as ComponentProps<typeof DialogFooter>)}
        />
      </DialogContent>
    </Dialog>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="dialog-footer"]')
}

function classesOfDialogFooter(
  props: Partial<Record<keyof ComponentProps<typeof DialogFooter>, unknown>> = {},
) {
  return renderDialogFooter(props)?.getAttribute('class')?.split(' ') ?? []
}

function attributesOfDialogFooter(
  props: Partial<Record<keyof ComponentProps<typeof DialogFooter>, unknown>> = {},
) {
  const element = renderDialogFooter(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('DialogFooter', () => {
  it('renders [data-slot="dialog-footer"] with its classes', () => {
    expect(classesOfDialogFooter()).toEqual(expect.arrayContaining([styles.dialogFooter]))
  })

  it('renders the same with showCloseButton=false passed explicitly', () => {
    expect(attributesOfDialogFooter({ showCloseButton: false })).toEqual(attributesOfDialogFooter())
  })

  it('renders with showCloseButton=true', () => {
    expect(renderDialogFooter({ showCloseButton: true })).toBeTruthy()
  })

  it('appends a consumer className last', () => {
    renderDialogFooter({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Dialog defaultOpen>
        <DialogTrigger>DialogTrigger</DialogTrigger>
        <DialogContent>
          <DialogFooter data-testid="subject">DialogFooter</DialogFooter>
        </DialogContent>
      </Dialog>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Dialog defaultOpen>
        <DialogTrigger>DialogTrigger</DialogTrigger>
        <DialogContent showCloseButton={false}>
          <DialogFooter data-testid="subject">DialogFooter</DialogFooter>
        </DialogContent>
      </Dialog>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

function renderDialogTitle(
  props: Partial<Record<keyof ComponentProps<typeof DialogTitle>, unknown>> = {},
) {
  cleanup()
  render(
    <Dialog defaultOpen>
      <DialogContent>
        <DialogHeader>
          <DialogTitle
            data-testid="subject"
            {...({ children: 'DialogTitle', ...props } as ComponentProps<typeof DialogTitle>)}
          />
        </DialogHeader>
      </DialogContent>
    </Dialog>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="dialog-title"]')
}

function classesOfDialogTitle(
  props: Partial<Record<keyof ComponentProps<typeof DialogTitle>, unknown>> = {},
) {
  return renderDialogTitle(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('DialogTitle', () => {
  it('renders [data-slot="dialog-title"] with its classes', () => {
    expect(classesOfDialogTitle()).toEqual(expect.arrayContaining([styles.dialogTitle]))
  })

  it('appends a consumer className last', () => {
    renderDialogTitle({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Dialog defaultOpen>
        <DialogTrigger>DialogTrigger</DialogTrigger>
        <DialogContent>
          <DialogHeader>
            <DialogTitle data-testid="subject">DialogTitle</DialogTitle>
          </DialogHeader>
        </DialogContent>
      </Dialog>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Dialog defaultOpen>
        <DialogTrigger>DialogTrigger</DialogTrigger>
        <DialogContent showCloseButton={false}>
          <DialogHeader>
            <DialogTitle data-testid="subject">DialogTitle</DialogTitle>
          </DialogHeader>
        </DialogContent>
      </Dialog>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

function renderDialogDescription(
  props: Partial<Record<keyof ComponentProps<typeof DialogDescription>, unknown>> = {},
) {
  cleanup()
  render(
    <Dialog defaultOpen>
      <DialogContent>
        <DialogHeader>
          <DialogDescription
            data-testid="subject"
            {...({ children: 'DialogDescription', ...props } as ComponentProps<
              typeof DialogDescription
            >)}
          />
        </DialogHeader>
      </DialogContent>
    </Dialog>,
  )
  return document
    .querySelector('[data-testid="subject"]')
    ?.closest('[data-slot="dialog-description"]')
}

function classesOfDialogDescription(
  props: Partial<Record<keyof ComponentProps<typeof DialogDescription>, unknown>> = {},
) {
  return renderDialogDescription(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('DialogDescription', () => {
  it('renders [data-slot="dialog-description"] with its classes', () => {
    expect(classesOfDialogDescription()).toEqual(expect.arrayContaining([styles.dialogDescription]))
  })

  it('appends a consumer className last', () => {
    renderDialogDescription({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Dialog defaultOpen>
        <DialogTrigger>DialogTrigger</DialogTrigger>
        <DialogContent>
          <DialogHeader>
            <DialogDescription data-testid="subject">DialogDescription</DialogDescription>
          </DialogHeader>
        </DialogContent>
      </Dialog>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Dialog defaultOpen>
        <DialogTrigger>DialogTrigger</DialogTrigger>
        <DialogContent showCloseButton={false}>
          <DialogHeader>
            <DialogDescription data-testid="subject">DialogDescription</DialogDescription>
          </DialogHeader>
        </DialogContent>
      </Dialog>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})
