// Generated by scripts/mirror from shadcn base-vega/table. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { describe, expect, it } from 'vitest'
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from './Table'
import styles from './Table.module.scss'

function renderTable(props: Partial<ComponentProps<typeof Table>> = {}) {
  cleanup()
  render(<Table data-testid="subject" {...(props as ComponentProps<typeof Table>)} />)
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="table"]')
}

function classesOfTable(props: Partial<ComponentProps<typeof Table>> = {}) {
  return renderTable(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('Table', () => {
  it('renders [data-slot="table"] with its classes', () => {
    expect(classesOfTable()).toEqual(expect.arrayContaining([styles.table]))
  })

  it('appends a consumer className last', () => {
    renderTable({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderTableHeader(props: Partial<ComponentProps<typeof TableHeader>> = {}) {
  cleanup()
  render(
    <Table>
      <TableHeader data-testid="subject" {...(props as ComponentProps<typeof TableHeader>)} />
    </Table>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="table-header"]')
}

function classesOfTableHeader(props: Partial<ComponentProps<typeof TableHeader>> = {}) {
  return renderTableHeader(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('TableHeader', () => {
  it('renders [data-slot="table-header"] with its classes', () => {
    expect(classesOfTableHeader()).toEqual(expect.arrayContaining([styles.tableHeader]))
  })

  it('appends a consumer className last', () => {
    renderTableHeader({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderTableBody(props: Partial<ComponentProps<typeof TableBody>> = {}) {
  cleanup()
  render(
    <Table>
      <TableBody data-testid="subject" {...(props as ComponentProps<typeof TableBody>)} />
    </Table>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="table-body"]')
}

function classesOfTableBody(props: Partial<ComponentProps<typeof TableBody>> = {}) {
  return renderTableBody(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('TableBody', () => {
  it('renders [data-slot="table-body"] with its classes', () => {
    expect(classesOfTableBody()).toEqual(expect.arrayContaining([styles.tableBody]))
  })

  it('appends a consumer className last', () => {
    renderTableBody({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderTableFooter(props: Partial<ComponentProps<typeof TableFooter>> = {}) {
  cleanup()
  render(
    <Table>
      <TableFooter data-testid="subject" {...(props as ComponentProps<typeof TableFooter>)} />
    </Table>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="table-footer"]')
}

function classesOfTableFooter(props: Partial<ComponentProps<typeof TableFooter>> = {}) {
  return renderTableFooter(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('TableFooter', () => {
  it('renders [data-slot="table-footer"] with its classes', () => {
    expect(classesOfTableFooter()).toEqual(expect.arrayContaining([styles.tableFooter]))
  })

  it('appends a consumer className last', () => {
    renderTableFooter({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderTableRow(props: Partial<ComponentProps<typeof TableRow>> = {}) {
  cleanup()
  render(
    <Table>
      <TableHeader>
        <TableRow data-testid="subject" {...(props as ComponentProps<typeof TableRow>)} />
      </TableHeader>
    </Table>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="table-row"]')
}

function classesOfTableRow(props: Partial<ComponentProps<typeof TableRow>> = {}) {
  return renderTableRow(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('TableRow', () => {
  it('renders [data-slot="table-row"] with its classes', () => {
    expect(classesOfTableRow()).toEqual(expect.arrayContaining([styles.tableRow]))
  })

  it('appends a consumer className last', () => {
    renderTableRow({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Table>
        <TableBody>
          <TableRow data-testid="subject">TableRow</TableRow>
        </TableBody>
      </Table>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Table>
        <TableFooter>
          <TableRow data-testid="subject">TableRow</TableRow>
        </TableFooter>
      </Table>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

function renderTableHead(props: Partial<ComponentProps<typeof TableHead>> = {}) {
  cleanup()
  render(
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead data-testid="subject" {...(props as ComponentProps<typeof TableHead>)} />
        </TableRow>
      </TableHeader>
    </Table>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="table-head"]')
}

function classesOfTableHead(props: Partial<ComponentProps<typeof TableHead>> = {}) {
  return renderTableHead(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('TableHead', () => {
  it('renders [data-slot="table-head"] with its classes', () => {
    expect(classesOfTableHead()).toEqual(expect.arrayContaining([styles.tableHead]))
  })

  it('appends a consumer className last', () => {
    renderTableHead({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderTableCell(props: Partial<ComponentProps<typeof TableCell>> = {}) {
  cleanup()
  render(
    <Table>
      <TableBody>
        <TableRow>
          <TableCell data-testid="subject" {...(props as ComponentProps<typeof TableCell>)} />
        </TableRow>
      </TableBody>
    </Table>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="table-cell"]')
}

function classesOfTableCell(props: Partial<ComponentProps<typeof TableCell>> = {}) {
  return renderTableCell(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('TableCell', () => {
  it('renders [data-slot="table-cell"] with its classes', () => {
    expect(classesOfTableCell()).toEqual(expect.arrayContaining([styles.tableCell]))
  })

  it('appends a consumer className last', () => {
    renderTableCell({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Table>
        <TableFooter>
          <TableRow>
            <TableCell data-testid="subject" colSpan={3}>
              TableCell
            </TableCell>
          </TableRow>
        </TableFooter>
      </Table>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Table>
        <TableFooter>
          <TableRow>
            <TableCell data-testid="subject">TableCell</TableCell>
          </TableRow>
        </TableFooter>
      </Table>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

function renderTableCaption(props: Partial<ComponentProps<typeof TableCaption>> = {}) {
  cleanup()
  render(
    <Table>
      <TableCaption data-testid="subject" {...(props as ComponentProps<typeof TableCaption>)} />
    </Table>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="table-caption"]')
}

function classesOfTableCaption(props: Partial<ComponentProps<typeof TableCaption>> = {}) {
  return renderTableCaption(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('TableCaption', () => {
  it('renders [data-slot="table-caption"] with its classes', () => {
    expect(classesOfTableCaption()).toEqual(expect.arrayContaining([styles.tableCaption]))
  })

  it('appends a consumer className last', () => {
    renderTableCaption({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})
