// Generated by scripts/mirror from shadcn base-vega/badge. Do not edit.

import { mergeProps } from '@base-ui/react/merge-props'
import { useRender } from '@base-ui/react/use-render'
import { type ClassValue, clsx } from 'clsx'
import styles from './Badge.module.scss'

const badgeVariantClasses = {
  variant: {
    default: styles.variantDefault,
    secondary: styles.variantSecondary,
    destructive: styles.variantDestructive,
    outline: styles.variantOutline,
    ghost: styles.variantGhost,
    link: styles.variantLink,
  },
} as const

type BadgeVariantProps = {
  [Group in keyof typeof badgeVariantClasses]?: keyof (typeof badgeVariantClasses)[Group] | null
}

function badgeVariants({
  variant = 'default',
  className,
}: BadgeVariantProps & { className?: ClassValue } = {}) {
  return clsx(styles.badge, variant && badgeVariantClasses.variant[variant], className)
}

function Badge({
  className,
  variant = 'default',
  render,
  ...props
}: useRender.ComponentProps<'span'> & BadgeVariantProps) {
  return useRender({
    defaultTagName: 'span',
    props: mergeProps<'span'>(
      {
        className: clsx(badgeVariants({ variant }), className),
      },
      props,
    ),
    render,
    state: {
      slot: 'badge',
      variant,
    },
  })
}

export { Badge, badgeVariants }
