// Generated by scripts/mirror from shadcn base-vega/combobox. Do not edit.

import { Combobox as ComboboxPrimitive } from '@base-ui/react'
import { cleanup, render, renderHook } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { describe, expect, it } from 'vitest'
import {
  Combobox,
  ComboboxChip,
  ComboboxChips,
  ComboboxChipsInput,
  ComboboxCollection,
  ComboboxContent,
  ComboboxEmpty,
  ComboboxGroup,
  ComboboxInput,
  ComboboxItem,
  ComboboxLabel,
  ComboboxList,
  ComboboxSeparator,
  ComboboxTrigger,
  ComboboxValue,
  useComboboxAnchor,
} from './Combobox'
import styles from './Combobox.module.scss'

// React's useId output (_r_1_, and :r1: or «r1» before React 19.1), which
// differs between renders; Base UI puts it in ids and data-id.
const USE_ID = /_r_[0-9a-z]+_|:r[0-9a-z]+:|«r[0-9a-z]+»/g

describe('ComboboxValue', () => {
  it('renders its children', () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxTrigger>ComboboxTrigger</ComboboxTrigger>
        <ComboboxTrigger>
          <ComboboxValue>
            <i data-testid="child" />
          </ComboboxValue>
        </ComboboxTrigger>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="child"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Combobox multiple autoHighlight defaultOpen>
        <ComboboxChips>
          <ComboboxValue>
            <i data-testid="child" />
          </ComboboxValue>
        </ComboboxChips>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="child"]')).not.toBeNull()
  })
})

function renderComboboxTrigger(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxTrigger>, unknown>> = {},
) {
  cleanup()
  render(
    <Combobox defaultOpen>
      <ComboboxTrigger>ComboboxTrigger</ComboboxTrigger>
      <ComboboxTrigger
        data-testid="subject"
        {...({ children: 'ComboboxTrigger', ...props } as ComponentProps<typeof ComboboxTrigger>)}
      />
    </Combobox>,
  )
  return document
    .querySelector('[data-testid="subject"]')
    ?.closest('[data-slot="combobox-trigger"]')
}

function classesOfComboboxTrigger(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxTrigger>, unknown>> = {},
) {
  return renderComboboxTrigger(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('ComboboxTrigger', () => {
  it('renders [data-slot="combobox-trigger"] with its classes', () => {
    expect(classesOfComboboxTrigger()).toEqual(expect.arrayContaining([styles.comboboxTrigger]))
  })

  it('appends a consumer className last', () => {
    renderComboboxTrigger({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderComboboxInput(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxInput>, unknown>> = {},
) {
  cleanup()
  render(
    <Combobox defaultOpen>
      <ComboboxInput
        data-testid="subject"
        {...({ placeholder: 'Select a framework', ...props } as ComponentProps<
          typeof ComboboxInput
        >)}
      />
    </Combobox>,
  )
  return document.querySelector('[data-testid="subject"]')
}

function attributesOfComboboxInput(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxInput>, unknown>> = {},
) {
  const element = renderComboboxInput(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('ComboboxInput', () => {
  it('renders the same with disabled=false passed explicitly', () => {
    expect(attributesOfComboboxInput({ disabled: false })).toEqual(attributesOfComboboxInput())
  })

  it('renders the same with showTrigger=true passed explicitly', () => {
    expect(attributesOfComboboxInput({ showTrigger: true })).toEqual(attributesOfComboboxInput())
  })

  it('renders the same with showClear=false passed explicitly', () => {
    expect(attributesOfComboboxInput({ showClear: false })).toEqual(attributesOfComboboxInput())
  })

  it('renders with disabled=true', () => {
    expect(renderComboboxInput({ disabled: true })).toBeTruthy()
  })

  it('renders with showTrigger=false', () => {
    expect(renderComboboxInput({ showTrigger: false })).toBeTruthy()
  })

  it('renders with showClear=true', () => {
    expect(renderComboboxInput({ showClear: true })).toBeTruthy()
  })

  it('appends a consumer className last', () => {
    renderComboboxInput({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxInput data-testid="subject" />
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxInput data-testid="subject" placeholder="Select a framework" aria-invalid="true" />
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxInput
          data-testid="subject"
          id="combobox-framework-invalid"
          placeholder="Select a framework"
          aria-invalid
        />
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxInput data-testid="subject" placeholder="Select a framework" showClear />
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxInput data-testid="subject" placeholder="Select a timezone" />
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (7)", () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxInput
          data-testid="subject"
          id="framework"
          name="framework"
          placeholder="Select a framework"
          required
        />
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (8)", () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxInput data-testid="subject" placeholder="Search from 100 items" />
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (9)", () => {
    cleanup()
    render(
      <Combobox autoHighlight defaultOpen>
        <ComboboxInput data-testid="subject" placeholder="Select a framework" />
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (10)", () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxInput data-testid="subject" placeholder="Select a timezone">
          ComboboxInput
        </ComboboxInput>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (11)", () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxTrigger>ComboboxTrigger</ComboboxTrigger>
        <ComboboxContent>
          <ComboboxInput data-testid="subject" showTrigger={false} placeholder="Search" />
        </ComboboxContent>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (12)", () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxInput data-testid="subject" placeholder="Search countries..." />
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (13)", () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxInput
          data-testid="subject"
          id="framework-dialog"
          placeholder="Select a framework"
        />
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

function renderComboboxContent(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxContent>, unknown>> = {},
) {
  cleanup()
  render(
    <Combobox defaultOpen>
      <ComboboxContent
        data-testid="subject"
        {...({ children: 'ComboboxContent', ...props } as ComponentProps<typeof ComboboxContent>)}
      />
    </Combobox>,
  )
  return document
    .querySelector('[data-testid="subject"]')
    ?.closest('[data-slot="combobox-content"]')
}

function classesOfComboboxContent(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxContent>, unknown>> = {},
) {
  return renderComboboxContent(props)?.getAttribute('class')?.split(' ') ?? []
}

function attributesOfComboboxContent(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxContent>, unknown>> = {},
) {
  const element = renderComboboxContent(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('ComboboxContent', () => {
  it('renders [data-slot="combobox-content"] with its classes', () => {
    expect(classesOfComboboxContent()).toEqual(expect.arrayContaining([styles.comboboxContent]))
  })

  it('renders the same with side="bottom" passed explicitly', () => {
    expect(attributesOfComboboxContent({ side: 'bottom' })).toEqual(attributesOfComboboxContent())
  })

  it('renders the same with sideOffset=6 passed explicitly', () => {
    expect(attributesOfComboboxContent({ sideOffset: 6 })).toEqual(attributesOfComboboxContent())
  })

  it('renders the same with align="start" passed explicitly', () => {
    expect(attributesOfComboboxContent({ align: 'start' })).toEqual(attributesOfComboboxContent())
  })

  it('renders the same with alignOffset=0 passed explicitly', () => {
    expect(attributesOfComboboxContent({ alignOffset: 0 })).toEqual(attributesOfComboboxContent())
  })

  it('appends a consumer className last', () => {
    renderComboboxContent({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Combobox autoHighlight defaultOpen>
        <ComboboxContent data-testid="subject">ComboboxContent</ComboboxContent>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxTrigger>ComboboxTrigger</ComboboxTrigger>
        <ComboboxContent data-testid="subject">ComboboxContent</ComboboxContent>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <Combobox multiple autoHighlight defaultOpen>
        <ComboboxContent data-testid="subject">ComboboxContent</ComboboxContent>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

function renderComboboxList(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxList>, unknown>> = {},
) {
  cleanup()
  render(
    <Combobox defaultOpen>
      <ComboboxContent>
        <ComboboxList
          data-testid="subject"
          {...({ children: 'ComboboxList', ...props } as ComponentProps<typeof ComboboxList>)}
        />
      </ComboboxContent>
    </Combobox>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="combobox-list"]')
}

function classesOfComboboxList(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxList>, unknown>> = {},
) {
  return renderComboboxList(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('ComboboxList', () => {
  it('renders [data-slot="combobox-list"] with its classes', () => {
    expect(classesOfComboboxList()).toEqual(expect.arrayContaining([styles.comboboxList]))
  })

  it('appends a consumer className last', () => {
    renderComboboxList({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Combobox autoHighlight defaultOpen>
        <ComboboxContent>
          <ComboboxList data-testid="subject">ComboboxList</ComboboxList>
        </ComboboxContent>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxTrigger>ComboboxTrigger</ComboboxTrigger>
        <ComboboxContent>
          <ComboboxList data-testid="subject">ComboboxList</ComboboxList>
        </ComboboxContent>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <Combobox multiple autoHighlight defaultOpen>
        <ComboboxContent>
          <ComboboxList data-testid="subject">ComboboxList</ComboboxList>
        </ComboboxContent>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

function renderComboboxItem(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxItem>, unknown>> = {},
) {
  cleanup()
  render(
    <Combobox defaultOpen>
      <ComboboxContent>
        <ComboboxList>
          <ComboboxItem
            data-testid="subject"
            {...({ children: 'ComboboxItem', ...props } as ComponentProps<typeof ComboboxItem>)}
          />
        </ComboboxList>
      </ComboboxContent>
    </Combobox>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="combobox-item"]')
}

function classesOfComboboxItem(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxItem>, unknown>> = {},
) {
  return renderComboboxItem(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('ComboboxItem', () => {
  it('renders [data-slot="combobox-item"] with its classes', () => {
    expect(classesOfComboboxItem()).toEqual(expect.arrayContaining([styles.comboboxItem]))
  })

  it('appends a consumer className last', () => {
    renderComboboxItem({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Combobox autoHighlight defaultOpen>
        <ComboboxContent>
          <ComboboxList>
            <ComboboxItem data-testid="subject">ComboboxItem</ComboboxItem>
          </ComboboxList>
        </ComboboxContent>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxTrigger>ComboboxTrigger</ComboboxTrigger>
        <ComboboxContent>
          <ComboboxList>
            <ComboboxItem data-testid="subject">ComboboxItem</ComboboxItem>
          </ComboboxList>
        </ComboboxContent>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <Combobox multiple autoHighlight defaultOpen>
        <ComboboxContent>
          <ComboboxList>
            <ComboboxItem data-testid="subject">ComboboxItem</ComboboxItem>
          </ComboboxList>
        </ComboboxContent>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

function renderComboboxGroup(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxGroup>, unknown>> = {},
) {
  cleanup()
  render(
    <Combobox defaultOpen>
      <ComboboxContent>
        <ComboboxList>
          <ComboboxGroup
            data-testid="subject"
            {...({ children: 'ComboboxGroup', ...props } as ComponentProps<typeof ComboboxGroup>)}
          />
        </ComboboxList>
      </ComboboxContent>
    </Combobox>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="combobox-group"]')
}

describe('ComboboxGroup', () => {
  it('appends a consumer className last', () => {
    renderComboboxGroup({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderComboboxLabel(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxLabel>, unknown>> = {},
) {
  cleanup()
  render(
    <Combobox defaultOpen>
      <ComboboxContent>
        <ComboboxList>
          <ComboboxGroup>
            <ComboboxLabel
              data-testid="subject"
              {...({ children: 'ComboboxLabel', ...props } as ComponentProps<typeof ComboboxLabel>)}
            />
          </ComboboxGroup>
        </ComboboxList>
      </ComboboxContent>
    </Combobox>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="combobox-label"]')
}

function classesOfComboboxLabel(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxLabel>, unknown>> = {},
) {
  return renderComboboxLabel(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('ComboboxLabel', () => {
  it('renders [data-slot="combobox-label"] with its classes', () => {
    expect(classesOfComboboxLabel()).toEqual(expect.arrayContaining([styles.comboboxLabel]))
  })

  it('appends a consumer className last', () => {
    renderComboboxLabel({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

describe('ComboboxCollection', () => {
  it('renders with a function of each item as its children', () => {
    cleanup()
    expect(() =>
      render(
        <Combobox defaultOpen>
          <ComboboxContent>
            <ComboboxList>
              <ComboboxGroup>
                <ComboboxCollection>{() => <i />}</ComboboxCollection>
              </ComboboxGroup>
            </ComboboxList>
          </ComboboxContent>
        </Combobox>,
      ),
    ).not.toThrow()
  })
})

function renderComboboxEmpty(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxEmpty>, unknown>> = {},
) {
  cleanup()
  render(
    <Combobox defaultOpen>
      <ComboboxContent>
        <ComboboxEmpty
          data-testid="subject"
          {...({ children: 'ComboboxEmpty', ...props } as ComponentProps<typeof ComboboxEmpty>)}
        />
      </ComboboxContent>
    </Combobox>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="combobox-empty"]')
}

function classesOfComboboxEmpty(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxEmpty>, unknown>> = {},
) {
  return renderComboboxEmpty(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('ComboboxEmpty', () => {
  it('renders [data-slot="combobox-empty"] with its classes', () => {
    expect(classesOfComboboxEmpty()).toEqual(expect.arrayContaining([styles.comboboxEmpty]))
  })

  it('appends a consumer className last', () => {
    renderComboboxEmpty({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Combobox autoHighlight defaultOpen>
        <ComboboxContent>
          <ComboboxEmpty data-testid="subject">ComboboxEmpty</ComboboxEmpty>
        </ComboboxContent>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Combobox defaultOpen>
        <ComboboxTrigger>ComboboxTrigger</ComboboxTrigger>
        <ComboboxContent>
          <ComboboxEmpty data-testid="subject">ComboboxEmpty</ComboboxEmpty>
        </ComboboxContent>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <Combobox multiple autoHighlight defaultOpen>
        <ComboboxContent>
          <ComboboxEmpty data-testid="subject">ComboboxEmpty</ComboboxEmpty>
        </ComboboxContent>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

function renderComboboxSeparator(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxSeparator>, unknown>> = {},
) {
  cleanup()
  render(
    <Combobox defaultOpen>
      <ComboboxContent>
        <ComboboxList>
          <ComboboxGroup>
            <ComboboxSeparator
              data-testid="subject"
              {...(props as ComponentProps<typeof ComboboxSeparator>)}
            />
          </ComboboxGroup>
        </ComboboxList>
      </ComboboxContent>
    </Combobox>,
  )
  return document
    .querySelector('[data-testid="subject"]')
    ?.closest('[data-slot="combobox-separator"]')
}

function classesOfComboboxSeparator(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxSeparator>, unknown>> = {},
) {
  return renderComboboxSeparator(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('ComboboxSeparator', () => {
  it('renders [data-slot="combobox-separator"] with its classes', () => {
    expect(classesOfComboboxSeparator()).toEqual(expect.arrayContaining([styles.comboboxSeparator]))
  })

  it('appends a consumer className last', () => {
    renderComboboxSeparator({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderComboboxChips(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxChips>, unknown>> = {},
) {
  cleanup()
  render(
    <Combobox multiple autoHighlight defaultOpen>
      <ComboboxChips
        data-testid="subject"
        {...({ children: 'ComboboxChips', ...props } as ComponentProps<typeof ComboboxChips>)}
      />
    </Combobox>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="combobox-chips"]')
}

function classesOfComboboxChips(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxChips>, unknown>> = {},
) {
  return renderComboboxChips(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('ComboboxChips', () => {
  it('renders [data-slot="combobox-chips"] with its classes', () => {
    expect(classesOfComboboxChips()).toEqual(expect.arrayContaining([styles.comboboxChips]))
  })

  it('appends a consumer className last', () => {
    renderComboboxChips({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderComboboxChip(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxChip>, unknown>> = {},
) {
  cleanup()
  render(
    <Combobox multiple autoHighlight defaultOpen>
      <ComboboxChips>
        <ComboboxValue>
          <ComboboxChip
            data-testid="subject"
            {...({ children: 'ComboboxChip', ...props } as ComponentProps<typeof ComboboxChip>)}
          />
        </ComboboxValue>
      </ComboboxChips>
    </Combobox>,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="combobox-chip"]')
}

function classesOfComboboxChip(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxChip>, unknown>> = {},
) {
  return renderComboboxChip(props)?.getAttribute('class')?.split(' ') ?? []
}

function attributesOfComboboxChip(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxChip>, unknown>> = {},
) {
  const element = renderComboboxChip(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('ComboboxChip', () => {
  it('renders [data-slot="combobox-chip"] with its classes', () => {
    expect(classesOfComboboxChip()).toEqual(expect.arrayContaining([styles.comboboxChip]))
  })

  it('renders the same with showRemove=true passed explicitly', () => {
    expect(attributesOfComboboxChip({ showRemove: true })).toEqual(attributesOfComboboxChip())
  })

  it('renders with showRemove=false', () => {
    expect(renderComboboxChip({ showRemove: false })).toBeTruthy()
  })

  it('appends a consumer className last', () => {
    renderComboboxChip({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Combobox multiple autoHighlight defaultOpen>
        <ComboboxChips>
          <ComboboxValue>
            <ComboboxChip data-testid="subject" showRemove={false}>
              ComboboxChip
            </ComboboxChip>
          </ComboboxValue>
        </ComboboxChips>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

function renderComboboxChipsInput(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxChipsInput>, unknown>> = {},
) {
  cleanup()
  render(
    <Combobox multiple autoHighlight defaultOpen>
      <ComboboxChips>
        <ComboboxValue>
          <ComboboxChipsInput
            data-testid="subject"
            {...(props as ComponentProps<typeof ComboboxChipsInput>)}
          />
        </ComboboxValue>
      </ComboboxChips>
    </Combobox>,
  )
  return document
    .querySelector('[data-testid="subject"]')
    ?.closest('[data-slot="combobox-chip-input"]')
}

function classesOfComboboxChipsInput(
  props: Partial<Record<keyof ComponentProps<typeof ComboboxChipsInput>, unknown>> = {},
) {
  return renderComboboxChipsInput(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('ComboboxChipsInput', () => {
  it('renders [data-slot="combobox-chip-input"] with its classes', () => {
    expect(classesOfComboboxChipsInput()).toEqual(
      expect.arrayContaining([styles.comboboxChipInput]),
    )
  })

  it('appends a consumer className last', () => {
    renderComboboxChipsInput({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Combobox multiple autoHighlight defaultOpen>
        <ComboboxChips>
          <ComboboxValue>
            <ComboboxChipsInput data-testid="subject" aria-invalid="true" />
          </ComboboxValue>
        </ComboboxChips>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Combobox multiple autoHighlight defaultOpen>
        <ComboboxChips>
          <ComboboxValue>
            <ComboboxChipsInput data-testid="subject" id="combobox-multiple-invalid" aria-invalid />
          </ComboboxValue>
        </ComboboxChips>
      </Combobox>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

describe('re-exports', () => {
  it('re-exports Combobox from @base-ui/react', () => {
    expect(Combobox).toBe(ComboboxPrimitive.Root)
  })
})

describe('useComboboxAnchor', () => {
  it('runs inside Combobox', () => {
    cleanup()
    const { result } = renderHook(() => useComboboxAnchor(), {
      wrapper: ({ children }) => <Combobox>{children}</Combobox>,
    })
    expect(result.current).toBeDefined()
  })
})
