// Generated by scripts/mirror from shadcn base-rhea/item. Do not edit.

import { mergeProps } from '@base-ui/react/merge-props'
import { useRender } from '@base-ui/react/use-render'
import { type ClassValue, clsx } from 'clsx'
import type * as React from 'react'

import { Separator } from '@/registry/bje/ui/Separator/Separator'
import styles from './Item.module.scss'

function ItemGroup({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      role="list"
      data-slot="item-group"
      className={clsx(styles.itemGroup, className)}
      {...props}
    />
  )
}

function ItemSeparator({ className, ...props }: React.ComponentProps<typeof Separator>) {
  return (
    <Separator
      data-slot="item-separator"
      orientation="horizontal"
      className={clsx(styles.itemSeparator, className)}
      {...props}
    />
  )
}

const itemVariantClasses = {
  variant: {
    default: styles.variantDefault,
    outline: styles.variantOutline,
    muted: styles.variantMuted,
  },
  size: {
    default: styles.sizeDefault,
    sm: styles.sizeSm,
    xs: styles.sizeXs,
  },
} as const

type ItemVariantProps = {
  [Group in keyof typeof itemVariantClasses]?: keyof (typeof itemVariantClasses)[Group] | null
}

function itemVariants({
  variant = 'default',
  size = 'default',
  className,
}: ItemVariantProps & { className?: ClassValue } = {}) {
  return clsx(
    styles.item,
    variant && itemVariantClasses.variant[variant],
    size && itemVariantClasses.size[size],
    className,
  )
}

function Item({
  className,
  variant = 'default',
  size = 'default',
  render,
  ...props
}: useRender.ComponentProps<'div'> & ItemVariantProps) {
  return useRender({
    defaultTagName: 'div',
    props: mergeProps<'div'>(
      {
        className: itemVariants({ variant, size, className }),
      },
      props,
    ),
    render,
    state: {
      slot: 'item',
      variant,
      size,
    },
  })
}

const itemMediaVariantClasses = {
  variant: {
    default: styles.itemMediaVariantDefault,
    icon: styles.itemMediaVariantIcon,
    image: styles.itemMediaVariantImage,
  },
} as const

type ItemMediaVariantProps = {
  [Group in keyof typeof itemMediaVariantClasses]?:
    | keyof (typeof itemMediaVariantClasses)[Group]
    | null
}

function itemMediaVariants({
  variant = 'default',
  className,
}: ItemMediaVariantProps & { className?: ClassValue } = {}) {
  return clsx(styles.itemMedia, variant && itemMediaVariantClasses.variant[variant], className)
}

function ItemMedia({
  className,
  variant = 'default',
  ...props
}: React.ComponentProps<'div'> & ItemMediaVariantProps) {
  return (
    <div
      data-slot="item-media"
      data-variant={variant}
      className={itemMediaVariants({ variant, className })}
      {...props}
    />
  )
}

function ItemContent({ className, ...props }: React.ComponentProps<'div'>) {
  return <div data-slot="item-content" className={clsx(styles.itemContent, className)} {...props} />
}

function ItemTitle({ className, ...props }: React.ComponentProps<'div'>) {
  return <div data-slot="item-title" className={clsx(styles.itemTitle, className)} {...props} />
}

function ItemDescription({ className, ...props }: React.ComponentProps<'p'>) {
  return (
    <p
      data-slot="item-description"
      className={clsx(styles.itemDescription, className)}
      {...props}
    />
  )
}

function ItemActions({ className, ...props }: React.ComponentProps<'div'>) {
  return <div data-slot="item-actions" className={clsx(styles.itemActions, className)} {...props} />
}

function ItemHeader({ className, ...props }: React.ComponentProps<'div'>) {
  return <div data-slot="item-header" className={clsx(styles.itemHeader, className)} {...props} />
}

function ItemFooter({ className, ...props }: React.ComponentProps<'div'>) {
  return <div data-slot="item-footer" className={clsx(styles.itemFooter, className)} {...props} />
}

export {
  Item,
  ItemActions,
  ItemContent,
  ItemDescription,
  ItemFooter,
  ItemGroup,
  ItemHeader,
  ItemMedia,
  ItemSeparator,
  ItemTitle,
}
