// Generated by scripts/mirror from shadcn base-vega/resizable. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { describe, expect, it } from 'vitest'
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from './Resizable'
import styles from './Resizable.module.scss'

// jsdom has no ResizeObserver, which react-resizable-panels measures panels with.
globalThis.ResizeObserver ??= class {
  observe() {}
  unobserve() {}
  disconnect() {}
}

function renderResizablePanelGroup(
  props: Partial<Record<keyof ComponentProps<typeof ResizablePanelGroup>, unknown>> = {},
) {
  cleanup()
  render(
    <ResizablePanelGroup
      data-subject
      {...({
        orientation: 'horizontal',
        children: 'ResizablePanelGroup',
        ...props,
      } as ComponentProps<typeof ResizablePanelGroup>)}
    />,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="resizable-panel-group"]')
}

function classesOfResizablePanelGroup(
  props: Partial<Record<keyof ComponentProps<typeof ResizablePanelGroup>, unknown>> = {},
) {
  return renderResizablePanelGroup(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('ResizablePanelGroup', () => {
  it('renders [data-slot="resizable-panel-group"] with its classes', () => {
    expect(classesOfResizablePanelGroup()).toEqual(
      expect.arrayContaining([styles.resizablePanelGroup]),
    )
  })

  it('appends a consumer className last', () => {
    renderResizablePanelGroup({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <ResizablePanelGroup data-subject orientation="vertical">
        ResizablePanelGroup
      </ResizablePanelGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <ResizablePanelGroup orientation="horizontal">
        <ResizablePanel defaultSize="50%">
          <ResizablePanelGroup data-subject orientation="vertical">
            ResizablePanelGroup
          </ResizablePanelGroup>
        </ResizablePanel>
      </ResizablePanelGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderResizablePanel(
  props: Partial<Record<keyof ComponentProps<typeof ResizablePanel>, unknown>> = {},
) {
  cleanup()
  render(
    <ResizablePanelGroup orientation="horizontal">
      <ResizablePanel
        data-subject
        {...({ defaultSize: '25%', children: 'ResizablePanel', ...props } as ComponentProps<
          typeof ResizablePanel
        >)}
      />
    </ResizablePanelGroup>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="resizable-panel"]')
}

describe('ResizablePanel', () => {
  it('appends a consumer className last', () => {
    renderResizablePanel({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <ResizablePanelGroup orientation="horizontal">
        <ResizablePanel data-subject defaultSize="75%">
          ResizablePanel
        </ResizablePanel>
      </ResizablePanelGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <ResizablePanelGroup orientation="vertical">
        <ResizablePanel data-subject defaultSize="25%">
          ResizablePanel
        </ResizablePanel>
      </ResizablePanelGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <ResizablePanelGroup orientation="vertical">
        <ResizablePanel data-subject defaultSize="75%">
          ResizablePanel
        </ResizablePanel>
      </ResizablePanelGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <ResizablePanelGroup orientation="horizontal">
        <ResizablePanel data-subject defaultSize="50%">
          ResizablePanel
        </ResizablePanel>
      </ResizablePanelGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(
      <ResizablePanelGroup orientation="horizontal">
        <ResizablePanel defaultSize="50%">
          <ResizablePanelGroup orientation="vertical">
            <ResizablePanel data-subject defaultSize="25%">
              ResizablePanel
            </ResizablePanel>
          </ResizablePanelGroup>
        </ResizablePanel>
      </ResizablePanelGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (7)", () => {
    cleanup()
    render(
      <ResizablePanelGroup orientation="horizontal">
        <ResizablePanel defaultSize="50%">
          <ResizablePanelGroup orientation="vertical">
            <ResizablePanel data-subject defaultSize="75%">
              ResizablePanel
            </ResizablePanel>
          </ResizablePanelGroup>
        </ResizablePanel>
      </ResizablePanelGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (8)", () => {
    cleanup()
    render(
      <ResizablePanelGroup orientation="horizontal">
        <ResizablePanel data-subject defaultSize="30%" id="left" minSize="20%">
          ResizablePanel
        </ResizablePanel>
      </ResizablePanelGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (9)", () => {
    cleanup()
    render(
      <ResizablePanelGroup orientation="horizontal">
        <ResizablePanel data-subject defaultSize="70%" id="right" minSize="30%">
          ResizablePanel
        </ResizablePanel>
      </ResizablePanelGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderResizableHandle(
  props: Partial<Record<keyof ComponentProps<typeof ResizableHandle>, unknown>> = {},
) {
  cleanup()
  render(
    <ResizablePanelGroup orientation="horizontal">
      <ResizableHandle data-subject {...(props as ComponentProps<typeof ResizableHandle>)} />
    </ResizablePanelGroup>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="resizable-handle"]')
}

function classesOfResizableHandle(
  props: Partial<Record<keyof ComponentProps<typeof ResizableHandle>, unknown>> = {},
) {
  return renderResizableHandle(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('ResizableHandle', () => {
  it('renders [data-slot="resizable-handle"] with its classes', () => {
    expect(classesOfResizableHandle()).toEqual(expect.arrayContaining([styles.resizableHandle]))
  })

  it('appends a consumer className last', () => {
    renderResizableHandle({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <ResizablePanelGroup orientation="vertical">
        <ResizableHandle data-subject />
      </ResizablePanelGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <ResizablePanelGroup orientation="horizontal">
        <ResizableHandle data-subject withHandle />
      </ResizablePanelGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <ResizablePanelGroup orientation="horizontal">
        <ResizablePanel defaultSize="50%">
          <ResizablePanelGroup orientation="vertical">
            <ResizableHandle data-subject />
          </ResizablePanelGroup>
        </ResizablePanel>
      </ResizablePanelGroup>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})
