// Generated by scripts/mirror from shadcn base-mira/scroll-area. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { afterEach, describe, expect, it } from 'vitest'
import { ScrollArea, ScrollBar } from './ScrollArea'
import styles from './ScrollArea.module.scss'

// React's useId output (_r_1_, and :r1: or «r1» before React 19.1), which
// differs between renders; Base UI puts it in ids and data-id.
const USE_ID = /_r_[0-9a-z]+_|:r[0-9a-z]+:|«r[0-9a-z]+»/g

afterEach(cleanup)

function renderScrollArea(
  props: Partial<Record<keyof ComponentProps<typeof ScrollArea>, unknown>> = {},
) {
  cleanup()
  render(
    <ScrollArea
      data-subject
      {...({ children: 'ScrollArea', ...props } as ComponentProps<typeof ScrollArea>)}
    />,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="scroll-area"]')
}

function classesOfScrollArea(
  props: Partial<Record<keyof ComponentProps<typeof ScrollArea>, unknown>> = {},
) {
  return renderScrollArea(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('ScrollArea', () => {
  it('renders [data-slot="scroll-area"] with its classes', () => {
    expect(classesOfScrollArea()).toEqual(expect.arrayContaining([styles.scrollArea]))
  })

  it('appends a consumer className last', () => {
    renderScrollArea({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderScrollBar(
  props: Partial<Record<keyof ComponentProps<typeof ScrollBar>, unknown>> = {},
) {
  cleanup()
  render(
    <ScrollArea>
      <ScrollBar
        data-subject
        {...({ keepMounted: true, ...props } as ComponentProps<typeof ScrollBar>)}
      />
    </ScrollArea>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="scroll-area-scrollbar"]')
}

function classesOfScrollBar(
  props: Partial<Record<keyof ComponentProps<typeof ScrollBar>, unknown>> = {},
) {
  return renderScrollBar(props)?.getAttribute('class')?.split(' ') ?? []
}

function htmlOfScrollBar(
  props: Partial<Record<keyof ComponentProps<typeof ScrollBar>, unknown>> = {},
) {
  renderScrollBar(props)
  return document.body.innerHTML.replace(USE_ID, '')
}

function attributesOfScrollBar(
  props: Partial<Record<keyof ComponentProps<typeof ScrollBar>, unknown>> = {},
) {
  const element = renderScrollBar(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('ScrollBar', () => {
  it('renders [data-slot="scroll-area-scrollbar"] with its classes', () => {
    expect(classesOfScrollBar()).toEqual(expect.arrayContaining([styles.scrollAreaScrollbar]))
  })

  it('renders the same with orientation="vertical" passed explicitly', () => {
    expect(attributesOfScrollBar({ orientation: 'vertical' })).toEqual(attributesOfScrollBar())
  })

  it('renders differently with orientation="horizontal"', () => {
    expect(htmlOfScrollBar({ orientation: 'horizontal' })).not.toBe(htmlOfScrollBar())
  })

  it('appends a consumer className last', () => {
    renderScrollBar({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})
