// Generated by scripts/mirror from shadcn base-luma/direction. Do not edit.

import * as directionProvider from '@base-ui/react/direction-provider'
import { describe, expect, it } from 'vitest'
import { DirectionProvider, useDirection } from './Direction'

describe('re-exports', () => {
  it('re-exports DirectionProvider from @base-ui\u002Freact\u002Fdirection-provider', () => {
    expect(DirectionProvider).toBe(directionProvider.DirectionProvider)
  })

  it('re-exports useDirection from @base-ui\u002Freact\u002Fdirection-provider', () => {
    expect(useDirection).toBe(directionProvider.useDirection)
  })
})
