// Generated by scripts/mirror from shadcn base-luma/resizable. Do not edit.

'use client'

import { clsx } from 'clsx'
import * as ResizablePrimitive from 'react-resizable-panels'
import styles from './Resizable.module.scss'

function ResizablePanelGroup({ className, ...props }: ResizablePrimitive.GroupProps) {
  return (
    <ResizablePrimitive.Group
      data-slot="resizable-panel-group"
      className={clsx(styles.resizablePanelGroup, className)}
      {...props}
    />
  )
}

function ResizablePanel({ ...props }: ResizablePrimitive.PanelProps) {
  return <ResizablePrimitive.Panel data-slot="resizable-panel" {...props} />
}

function ResizableHandle({
  withHandle,
  className,
  ...props
}: ResizablePrimitive.SeparatorProps & {
  withHandle?: boolean
}) {
  return (
    <ResizablePrimitive.Separator
      data-slot="resizable-handle"
      className={clsx(styles.resizableHandle, className)}
      {...props}
    >
      {withHandle && <div className={styles.resizableHandleDiv} />}
    </ResizablePrimitive.Separator>
  )
}

export { ResizableHandle, ResizablePanel, ResizablePanelGroup }
