// Generated by scripts/mirror from shadcn base-sera/alert. Do not edit.

import { type ClassValue, clsx } from 'clsx'
import type * as React from 'react'
import styles from './Alert.module.scss'

const alertVariantClasses = {
  variant: {
    default: styles.variantDefault,
    destructive: styles.variantDestructive,
  },
} as const

type AlertVariantProps = {
  [Group in keyof typeof alertVariantClasses]?: keyof (typeof alertVariantClasses)[Group] | null
}

function alertVariants({
  variant = 'default',
  className,
}: AlertVariantProps & { className?: ClassValue } = {}) {
  return clsx(styles.alert, variant && alertVariantClasses.variant[variant], className)
}

function Alert({ className, variant, ...props }: React.ComponentProps<'div'> & AlertVariantProps) {
  return (
    <div
      data-slot="alert"
      role="alert"
      className={clsx(alertVariants({ variant }), className)}
      {...props}
    />
  )
}

function AlertTitle({ className, ...props }: React.ComponentProps<'div'>) {
  return <div data-slot="alert-title" className={clsx(styles.alertTitle, className)} {...props} />
}

function AlertDescription({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      data-slot="alert-description"
      className={clsx(styles.alertDescription, className)}
      {...props}
    />
  )
}

function AlertAction({ className, ...props }: React.ComponentProps<'div'>) {
  return <div data-slot="alert-action" className={clsx(styles.alertAction, className)} {...props} />
}

export { Alert, AlertAction, AlertDescription, AlertTitle }
