// Generated by scripts/mirror from shadcn base-mira/slider. Do not edit.

import { Slider as SliderPrimitive } from '@base-ui/react/slider'
import { clsx } from 'clsx'
import styles from './Slider.module.scss'

function Slider({
  className,
  defaultValue,
  value,
  min = 0,
  max = 100,
  ...props
}: SliderPrimitive.Root.Props) {
  const _values = Array.isArray(value)
    ? value
    : Array.isArray(defaultValue)
      ? defaultValue
      : [min, max]

  return (
    <SliderPrimitive.Root
      className={clsx(styles.slider, className)}
      data-slot="slider"
      defaultValue={defaultValue}
      value={value}
      min={min}
      max={max}
      thumbAlignment="edge"
      {...props}
    >
      <SliderPrimitive.Control className={styles.sliderControl}>
        <SliderPrimitive.Track data-slot="slider-track" className={styles.sliderTrack}>
          <SliderPrimitive.Indicator data-slot="slider-range" className={styles.sliderRange} />
        </SliderPrimitive.Track>
        {Array.from({ length: _values.length }, (_, index) => (
          <SliderPrimitive.Thumb
            data-slot="slider-thumb"
            key={index}
            className={styles.sliderThumb}
          />
        ))}
      </SliderPrimitive.Control>
    </SliderPrimitive.Root>
  )
}

export { Slider }
