// Generated by scripts/mirror from shadcn base-vega/navigation-menu. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { describe, expect, it } from 'vitest'
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuPositioner,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle,
} from './NavigationMenu'
import styles from './NavigationMenu.module.scss'

// React's useId output (_r_1_, and :r1: or «r1» before React 19.1), which
// differs between renders; Base UI puts it in ids and data-id.
const USE_ID = /_r_[0-9a-z]+_|:r[0-9a-z]+:|«r[0-9a-z]+»/g

function renderNavigationMenu(
  props: Partial<Record<keyof ComponentProps<typeof NavigationMenu>, unknown>> = {},
) {
  cleanup()
  render(
    <NavigationMenu
      data-testid="subject"
      {...({ children: 'NavigationMenu', ...props } as ComponentProps<typeof NavigationMenu>)}
    />,
  )
  return document.querySelector('[data-testid="subject"]')?.closest('[data-slot="navigation-menu"]')
}

function classesOfNavigationMenu(
  props: Partial<Record<keyof ComponentProps<typeof NavigationMenu>, unknown>> = {},
) {
  return renderNavigationMenu(props)?.getAttribute('class')?.split(' ') ?? []
}

function attributesOfNavigationMenu(
  props: Partial<Record<keyof ComponentProps<typeof NavigationMenu>, unknown>> = {},
) {
  const element = renderNavigationMenu(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('NavigationMenu', () => {
  it('renders [data-slot="navigation-menu"] with its classes', () => {
    expect(classesOfNavigationMenu()).toEqual(expect.arrayContaining([styles.navigationMenu]))
  })

  it('renders the same with align="start" passed explicitly', () => {
    expect(attributesOfNavigationMenu({ align: 'start' })).toEqual(attributesOfNavigationMenu())
  })

  it('appends a consumer className last', () => {
    renderNavigationMenu({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderNavigationMenuList(
  props: Partial<Record<keyof ComponentProps<typeof NavigationMenuList>, unknown>> = {},
) {
  cleanup()
  render(
    <NavigationMenu>
      <NavigationMenuList
        data-testid="subject"
        {...({ children: 'NavigationMenuList', ...props } as ComponentProps<
          typeof NavigationMenuList
        >)}
      />
    </NavigationMenu>,
  )
  return document
    .querySelector('[data-testid="subject"]')
    ?.closest('[data-slot="navigation-menu-list"]')
}

function classesOfNavigationMenuList(
  props: Partial<Record<keyof ComponentProps<typeof NavigationMenuList>, unknown>> = {},
) {
  return renderNavigationMenuList(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('NavigationMenuList', () => {
  it('renders [data-slot="navigation-menu-list"] with its classes', () => {
    expect(classesOfNavigationMenuList()).toEqual(
      expect.arrayContaining([styles.navigationMenuList]),
    )
  })

  it('appends a consumer className last', () => {
    renderNavigationMenuList({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderNavigationMenuItem(
  props: Partial<Record<keyof ComponentProps<typeof NavigationMenuItem>, unknown>> = {},
) {
  cleanup()
  render(
    <NavigationMenu>
      <NavigationMenuList>
        <NavigationMenuItem
          data-testid="subject"
          {...({ children: 'NavigationMenuItem', ...props } as ComponentProps<
            typeof NavigationMenuItem
          >)}
        />
      </NavigationMenuList>
    </NavigationMenu>,
  )
  return document
    .querySelector('[data-testid="subject"]')
    ?.closest('[data-slot="navigation-menu-item"]')
}

function classesOfNavigationMenuItem(
  props: Partial<Record<keyof ComponentProps<typeof NavigationMenuItem>, unknown>> = {},
) {
  return renderNavigationMenuItem(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('NavigationMenuItem', () => {
  it('renders [data-slot="navigation-menu-item"] with its classes', () => {
    expect(classesOfNavigationMenuItem()).toEqual(
      expect.arrayContaining([styles.navigationMenuItem]),
    )
  })

  it('appends a consumer className last', () => {
    renderNavigationMenuItem({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderNavigationMenuTrigger(
  props: Partial<Record<keyof ComponentProps<typeof NavigationMenuTrigger>, unknown>> = {},
) {
  cleanup()
  render(
    <NavigationMenu>
      <NavigationMenuList>
        <NavigationMenuItem>
          <NavigationMenuTrigger
            data-testid="subject"
            {...({ children: 'NavigationMenuTrigger', ...props } as ComponentProps<
              typeof NavigationMenuTrigger
            >)}
          />
        </NavigationMenuItem>
      </NavigationMenuList>
    </NavigationMenu>,
  )
  return document
    .querySelector('[data-testid="subject"]')
    ?.closest('[data-slot="navigation-menu-trigger"]')
}

function classesOfNavigationMenuTrigger(
  props: Partial<Record<keyof ComponentProps<typeof NavigationMenuTrigger>, unknown>> = {},
) {
  return renderNavigationMenuTrigger(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('NavigationMenuTrigger', () => {
  it('renders [data-slot="navigation-menu-trigger"] with its classes', () => {
    expect(classesOfNavigationMenuTrigger()).toEqual(
      expect.arrayContaining([styles.navigationMenuTriggerStyle]),
    )
  })

  it('appends a consumer className last', () => {
    renderNavigationMenuTrigger({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderNavigationMenuContent(
  props: Partial<Record<keyof ComponentProps<typeof NavigationMenuContent>, unknown>> = {},
) {
  cleanup()
  render(
    <NavigationMenu>
      <NavigationMenuList>
        <NavigationMenuItem>
          <NavigationMenuContent
            data-testid="subject"
            {...({
              keepMounted: true,
              children: 'NavigationMenuContent',
              ...props,
            } as ComponentProps<typeof NavigationMenuContent>)}
          />
        </NavigationMenuItem>
      </NavigationMenuList>
    </NavigationMenu>,
  )
  return document
    .querySelector('[data-testid="subject"]')
    ?.closest('[data-slot="navigation-menu-content"]')
}

function classesOfNavigationMenuContent(
  props: Partial<Record<keyof ComponentProps<typeof NavigationMenuContent>, unknown>> = {},
) {
  return renderNavigationMenuContent(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('NavigationMenuContent', () => {
  it('renders [data-slot="navigation-menu-content"] with its classes', () => {
    expect(classesOfNavigationMenuContent()).toEqual(
      expect.arrayContaining([styles.navigationMenuContent]),
    )
  })

  it('appends a consumer className last', () => {
    renderNavigationMenuContent({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

describe('NavigationMenuPositioner', () => {
  it("renders nothing in jsdom: Base UI mounts it only while a menu item is open, which takes the item's value on NavigationMenu.", () => {
    cleanup()
    render(
      <NavigationMenu>
        <NavigationMenuPositioner data-testid="subject" />
      </NavigationMenu>,
    )
    expect(document.querySelector('[data-testid="subject"]')).toBeNull()
  })
})

function renderNavigationMenuLink(
  props: Partial<Record<keyof ComponentProps<typeof NavigationMenuLink>, unknown>> = {},
) {
  cleanup()
  render(
    <NavigationMenu>
      <NavigationMenuList>
        <NavigationMenuItem>
          <NavigationMenuContent keepMounted>
            <NavigationMenuLink
              data-testid="subject"
              {...({ children: 'NavigationMenuLink', ...props } as ComponentProps<
                typeof NavigationMenuLink
              >)}
            />
          </NavigationMenuContent>
        </NavigationMenuItem>
      </NavigationMenuList>
    </NavigationMenu>,
  )
  return document
    .querySelector('[data-testid="subject"]')
    ?.closest('[data-slot="navigation-menu-link"]')
}

function classesOfNavigationMenuLink(
  props: Partial<Record<keyof ComponentProps<typeof NavigationMenuLink>, unknown>> = {},
) {
  return renderNavigationMenuLink(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('NavigationMenuLink', () => {
  it('renders [data-slot="navigation-menu-link"] with its classes', () => {
    expect(classesOfNavigationMenuLink()).toEqual(
      expect.arrayContaining([styles.navigationMenuLink]),
    )
  })

  it('appends a consumer className last', () => {
    renderNavigationMenuLink({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <NavigationMenu>
        <NavigationMenuList>
          <NavigationMenuItem>
            <NavigationMenuLink data-testid="subject">NavigationMenuLink</NavigationMenuLink>
          </NavigationMenuItem>
        </NavigationMenuList>
      </NavigationMenu>,
    )
    expect(document.querySelector('[data-testid="subject"]')).not.toBeNull()
  })
})

function renderNavigationMenuIndicator(
  props: Partial<Record<keyof ComponentProps<typeof NavigationMenuIndicator>, unknown>> = {},
) {
  cleanup()
  render(
    <NavigationMenu>
      <NavigationMenuList>
        <NavigationMenuItem>
          <NavigationMenuContent keepMounted>
            <NavigationMenuIndicator
              data-testid="subject"
              {...({ children: 'NavigationMenuIndicator', ...props } as ComponentProps<
                typeof NavigationMenuIndicator
              >)}
            />
          </NavigationMenuContent>
        </NavigationMenuItem>
      </NavigationMenuList>
    </NavigationMenu>,
  )
  return document
    .querySelector('[data-testid="subject"]')
    ?.closest('[data-slot="navigation-menu-indicator"]')
}

function classesOfNavigationMenuIndicator(
  props: Partial<Record<keyof ComponentProps<typeof NavigationMenuIndicator>, unknown>> = {},
) {
  return renderNavigationMenuIndicator(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('NavigationMenuIndicator', () => {
  it('renders [data-slot="navigation-menu-indicator"] with its classes', () => {
    expect(classesOfNavigationMenuIndicator()).toEqual(
      expect.arrayContaining([styles.navigationMenuIndicator]),
    )
  })

  it('appends a consumer className last', () => {
    renderNavigationMenuIndicator({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

describe('navigationMenuTriggerStyle', () => {
  it('applies the base and default classes when called with no arguments', () => {
    expect(navigationMenuTriggerStyle()).toBe([styles.navigationMenuTriggerStyle].join(' '))
  })
})
