// Generated by scripts/mirror from shadcn base-rhea/select. Do not edit.

import { Select as SelectPrimitive } from '@base-ui/react/select'
import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { afterEach, describe, expect, it } from 'vitest'
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectScrollDownButton,
  SelectScrollUpButton,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
} from './Select'
import styles from './Select.module.scss'

// React's useId output (_r_1_, and :r1: or «r1» before React 19.1), which
// differs between renders; Base UI puts it in ids and data-id.
const USE_ID = /_r_[0-9a-z]+_|:r[0-9a-z]+:|«r[0-9a-z]+»/g

afterEach(cleanup)

function renderSelectGroup(
  props: Partial<Record<keyof ComponentProps<typeof SelectGroup>, unknown>> = {},
) {
  cleanup()
  render(
    <Select defaultOpen>
      <SelectTrigger>SelectTrigger</SelectTrigger>
      <SelectContent>
        <SelectGroup
          data-subject
          {...({ children: 'SelectGroup', ...props } as ComponentProps<typeof SelectGroup>)}
        />
      </SelectContent>
    </Select>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="select-group"]')
}

function classesOfSelectGroup(
  props: Partial<Record<keyof ComponentProps<typeof SelectGroup>, unknown>> = {},
) {
  return renderSelectGroup(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('SelectGroup', () => {
  it('renders [data-slot="select-group"] with its classes', () => {
    expect(classesOfSelectGroup()).toEqual(expect.arrayContaining([styles.selectGroup]))
  })

  it('appends a consumer className last', () => {
    renderSelectGroup({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger>SelectTrigger</SelectTrigger>
        <SelectContent alignItemWithTrigger={false}>
          <SelectGroup data-subject>SelectGroup</SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger size="sm">SelectTrigger</SelectTrigger>
        <SelectContent>
          <SelectGroup data-subject>SelectGroup</SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger size="default">SelectTrigger</SelectTrigger>
        <SelectContent>
          <SelectGroup data-subject>SelectGroup</SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger>SelectTrigger</SelectTrigger>
        <SelectContent alignItemWithTrigger>
          <SelectGroup data-subject>SelectGroup</SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger id="select-fruit">SelectTrigger</SelectTrigger>
        <SelectContent>
          <SelectGroup data-subject>SelectGroup</SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (7)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger aria-invalid="true">SelectTrigger</SelectTrigger>
        <SelectContent>
          <SelectGroup data-subject>SelectGroup</SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (8)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger id="select-fruit-invalid" aria-invalid>
          SelectTrigger
        </SelectTrigger>
        <SelectContent>
          <SelectGroup data-subject>SelectGroup</SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (9)", () => {
    cleanup()
    render(
      <Select multiple defaultValue={[]} defaultOpen>
        <SelectTrigger>SelectTrigger</SelectTrigger>
        <SelectContent>
          <SelectGroup data-subject>SelectGroup</SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderSelectValue(
  props: Partial<Record<keyof ComponentProps<typeof SelectValue>, unknown>> = {},
) {
  cleanup()
  render(
    <Select defaultOpen>
      <SelectTrigger>SelectTrigger</SelectTrigger>
      <SelectTrigger>
        <SelectValue data-subject {...(props as ComponentProps<typeof SelectValue>)} />
      </SelectTrigger>
    </Select>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="select-value"]')
}

function classesOfSelectValue(
  props: Partial<Record<keyof ComponentProps<typeof SelectValue>, unknown>> = {},
) {
  return renderSelectValue(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('SelectValue', () => {
  it('renders [data-slot="select-value"] with its classes', () => {
    expect(classesOfSelectValue()).toEqual(expect.arrayContaining([styles.selectValue]))
  })

  it('appends a consumer className last', () => {
    renderSelectValue({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger size="sm">SelectTrigger</SelectTrigger>
        <SelectTrigger size="sm">
          <SelectValue data-subject />
        </SelectTrigger>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger size="default">SelectTrigger</SelectTrigger>
        <SelectTrigger size="default">
          <SelectValue data-subject />
        </SelectTrigger>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger id="select-fruit">SelectTrigger</SelectTrigger>
        <SelectTrigger id="select-fruit">
          <SelectValue data-subject />
        </SelectTrigger>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger aria-invalid="true">SelectTrigger</SelectTrigger>
        <SelectTrigger aria-invalid="true">
          <SelectValue data-subject />
        </SelectTrigger>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger id="select-fruit-invalid" aria-invalid>
          SelectTrigger
        </SelectTrigger>
        <SelectTrigger id="select-fruit-invalid" aria-invalid>
          <SelectValue data-subject />
        </SelectTrigger>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (7)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger>SelectTrigger</SelectTrigger>
        <SelectTrigger>
          <SelectValue data-subject>SelectValue</SelectValue>
        </SelectTrigger>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (8)", () => {
    cleanup()
    render(
      <Select multiple defaultValue={[]} defaultOpen>
        <SelectTrigger>SelectTrigger</SelectTrigger>
        <SelectTrigger>
          <SelectValue data-subject>SelectValue</SelectValue>
        </SelectTrigger>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderSelectTrigger(
  props: Partial<Record<keyof ComponentProps<typeof SelectTrigger>, unknown>> = {},
) {
  cleanup()
  render(
    <Select defaultOpen>
      <SelectTrigger
        data-subject
        {...({ children: 'SelectTrigger', ...props } as ComponentProps<typeof SelectTrigger>)}
      />
    </Select>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="select-trigger"]')
}

function classesOfSelectTrigger(
  props: Partial<Record<keyof ComponentProps<typeof SelectTrigger>, unknown>> = {},
) {
  return renderSelectTrigger(props)?.getAttribute('class')?.split(' ') ?? []
}

function htmlOfSelectTrigger(
  props: Partial<Record<keyof ComponentProps<typeof SelectTrigger>, unknown>> = {},
) {
  renderSelectTrigger(props)
  return document.body.innerHTML.replace(USE_ID, '')
}

function attributesOfSelectTrigger(
  props: Partial<Record<keyof ComponentProps<typeof SelectTrigger>, unknown>> = {},
) {
  const element = renderSelectTrigger(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('SelectTrigger', () => {
  it('renders [data-slot="select-trigger"] with its classes', () => {
    expect(classesOfSelectTrigger()).toEqual(expect.arrayContaining([styles.selectTrigger]))
  })

  it('renders the same with size="default" passed explicitly', () => {
    expect(attributesOfSelectTrigger({ size: 'default' })).toEqual(attributesOfSelectTrigger())
  })

  it('renders differently with size="sm"', () => {
    expect(htmlOfSelectTrigger({ size: 'sm' })).not.toBe(htmlOfSelectTrigger())
  })

  it('appends a consumer className last', () => {
    renderSelectTrigger({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger data-subject size="sm">
          SelectTrigger
        </SelectTrigger>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger data-subject size="default">
          SelectTrigger
        </SelectTrigger>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger data-subject id="select-fruit">
          SelectTrigger
        </SelectTrigger>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger data-subject aria-invalid="true">
          SelectTrigger
        </SelectTrigger>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger data-subject id="select-fruit-invalid" aria-invalid>
          SelectTrigger
        </SelectTrigger>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (7)", () => {
    cleanup()
    render(
      <Select multiple defaultValue={[]} defaultOpen>
        <SelectTrigger data-subject>SelectTrigger</SelectTrigger>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderSelectContent(
  props: Partial<Record<keyof ComponentProps<typeof SelectContent>, unknown>> = {},
) {
  cleanup()
  render(
    <Select defaultOpen>
      <SelectTrigger>SelectTrigger</SelectTrigger>
      <SelectContent
        data-subject
        {...({ children: 'SelectContent', ...props } as ComponentProps<typeof SelectContent>)}
      />
    </Select>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="select-content"]')
}

function classesOfSelectContent(
  props: Partial<Record<keyof ComponentProps<typeof SelectContent>, unknown>> = {},
) {
  return renderSelectContent(props)?.getAttribute('class')?.split(' ') ?? []
}

function htmlOfSelectContent(
  props: Partial<Record<keyof ComponentProps<typeof SelectContent>, unknown>> = {},
) {
  renderSelectContent(props)
  return document.body.innerHTML.replace(USE_ID, '')
}

function attributesOfSelectContent(
  props: Partial<Record<keyof ComponentProps<typeof SelectContent>, unknown>> = {},
) {
  const element = renderSelectContent(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('SelectContent', () => {
  it('renders [data-slot="select-content"] with its classes', () => {
    expect(classesOfSelectContent()).toEqual(expect.arrayContaining([styles.selectContent]))
  })

  it('renders the same with side="bottom" passed explicitly', () => {
    expect(attributesOfSelectContent({ side: 'bottom' })).toEqual(attributesOfSelectContent())
  })

  it('renders the same with sideOffset=4 passed explicitly', () => {
    expect(attributesOfSelectContent({ sideOffset: 4 })).toEqual(attributesOfSelectContent())
  })

  it('renders the same with align="center" passed explicitly', () => {
    expect(attributesOfSelectContent({ align: 'center' })).toEqual(attributesOfSelectContent())
  })

  it('renders the same with alignOffset=0 passed explicitly', () => {
    expect(attributesOfSelectContent({ alignOffset: 0 })).toEqual(attributesOfSelectContent())
  })

  it('renders the same with alignItemWithTrigger=true passed explicitly', () => {
    expect(attributesOfSelectContent({ alignItemWithTrigger: true })).toEqual(
      attributesOfSelectContent(),
    )
  })

  it('renders differently with side="left"', () => {
    expect(htmlOfSelectContent({ side: 'left' })).not.toBe(htmlOfSelectContent())
  })

  it('renders differently with side="right"', () => {
    expect(htmlOfSelectContent({ side: 'right' })).not.toBe(htmlOfSelectContent())
  })

  it('renders differently with side="top"', () => {
    expect(htmlOfSelectContent({ side: 'top' })).not.toBe(htmlOfSelectContent())
  })

  it('renders differently with side="inline-start"', () => {
    expect(htmlOfSelectContent({ side: 'inline-start' })).not.toBe(htmlOfSelectContent())
  })

  it('renders differently with side="inline-end"', () => {
    expect(htmlOfSelectContent({ side: 'inline-end' })).not.toBe(htmlOfSelectContent())
  })

  it('renders differently with align="start"', () => {
    expect(htmlOfSelectContent({ align: 'start' })).not.toBe(htmlOfSelectContent())
  })

  it('renders differently with align="end"', () => {
    expect(htmlOfSelectContent({ align: 'end' })).not.toBe(htmlOfSelectContent())
  })

  it('renders differently with alignItemWithTrigger=false', () => {
    expect(htmlOfSelectContent({ alignItemWithTrigger: false })).not.toBe(htmlOfSelectContent())
  })

  it('appends a consumer className last', () => {
    renderSelectContent({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger>SelectTrigger</SelectTrigger>
        <SelectContent data-subject alignItemWithTrigger={false}>
          SelectContent
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger size="sm">SelectTrigger</SelectTrigger>
        <SelectContent data-subject>SelectContent</SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger size="default">SelectTrigger</SelectTrigger>
        <SelectContent data-subject>SelectContent</SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger>SelectTrigger</SelectTrigger>
        <SelectContent data-subject alignItemWithTrigger>
          SelectContent
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger id="select-fruit">SelectTrigger</SelectTrigger>
        <SelectContent data-subject>SelectContent</SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (7)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger aria-invalid="true">SelectTrigger</SelectTrigger>
        <SelectContent data-subject>SelectContent</SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (8)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger id="select-fruit-invalid" aria-invalid>
          SelectTrigger
        </SelectTrigger>
        <SelectContent data-subject>SelectContent</SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (9)", () => {
    cleanup()
    render(
      <Select multiple defaultValue={[]} defaultOpen>
        <SelectTrigger>SelectTrigger</SelectTrigger>
        <SelectContent data-subject>SelectContent</SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderSelectLabel(
  props: Partial<Record<keyof ComponentProps<typeof SelectLabel>, unknown>> = {},
) {
  cleanup()
  render(
    <Select defaultOpen>
      <SelectTrigger>SelectTrigger</SelectTrigger>
      <SelectContent>
        <SelectGroup>
          <SelectLabel
            data-subject
            {...({ children: 'SelectLabel', ...props } as ComponentProps<typeof SelectLabel>)}
          />
        </SelectGroup>
      </SelectContent>
    </Select>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="select-label"]')
}

function classesOfSelectLabel(
  props: Partial<Record<keyof ComponentProps<typeof SelectLabel>, unknown>> = {},
) {
  return renderSelectLabel(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('SelectLabel', () => {
  it('renders [data-slot="select-label"] with its classes', () => {
    expect(classesOfSelectLabel()).toEqual(expect.arrayContaining([styles.selectLabel]))
  })

  it('appends a consumer className last', () => {
    renderSelectLabel({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderSelectItem(
  props: Partial<Record<keyof ComponentProps<typeof SelectItem>, unknown>> = {},
) {
  cleanup()
  render(
    <Select defaultOpen>
      <SelectTrigger>SelectTrigger</SelectTrigger>
      <SelectContent>
        <SelectGroup>
          <SelectItem
            data-subject
            {...({ children: 'SelectItem', ...props } as ComponentProps<typeof SelectItem>)}
          />
        </SelectGroup>
      </SelectContent>
    </Select>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="select-item"]')
}

function classesOfSelectItem(
  props: Partial<Record<keyof ComponentProps<typeof SelectItem>, unknown>> = {},
) {
  return renderSelectItem(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('SelectItem', () => {
  it('renders [data-slot="select-item"] with its classes', () => {
    expect(classesOfSelectItem()).toEqual(expect.arrayContaining([styles.selectItem]))
  })

  it('appends a consumer className last', () => {
    renderSelectItem({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger>SelectTrigger</SelectTrigger>
        <SelectContent alignItemWithTrigger={false}>
          <SelectGroup>
            <SelectItem data-subject>SelectItem</SelectItem>
          </SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger size="sm">SelectTrigger</SelectTrigger>
        <SelectContent>
          <SelectGroup>
            <SelectItem data-subject>SelectItem</SelectItem>
          </SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger size="default">SelectTrigger</SelectTrigger>
        <SelectContent>
          <SelectGroup>
            <SelectItem data-subject>SelectItem</SelectItem>
          </SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger>SelectTrigger</SelectTrigger>
        <SelectContent alignItemWithTrigger>
          <SelectGroup>
            <SelectItem data-subject>SelectItem</SelectItem>
          </SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger id="select-fruit">SelectTrigger</SelectTrigger>
        <SelectContent>
          <SelectGroup>
            <SelectItem data-subject>SelectItem</SelectItem>
          </SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (7)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger aria-invalid="true">SelectTrigger</SelectTrigger>
        <SelectContent>
          <SelectGroup>
            <SelectItem data-subject>SelectItem</SelectItem>
          </SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (8)", () => {
    cleanup()
    render(
      <Select defaultOpen>
        <SelectTrigger id="select-fruit-invalid" aria-invalid>
          SelectTrigger
        </SelectTrigger>
        <SelectContent>
          <SelectGroup>
            <SelectItem data-subject>SelectItem</SelectItem>
          </SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (9)", () => {
    cleanup()
    render(
      <Select multiple defaultValue={[]} defaultOpen>
        <SelectTrigger>SelectTrigger</SelectTrigger>
        <SelectContent>
          <SelectGroup>
            <SelectItem data-subject>SelectItem</SelectItem>
          </SelectGroup>
        </SelectContent>
      </Select>,
    )
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})

function renderSelectSeparator(
  props: Partial<Record<keyof ComponentProps<typeof SelectSeparator>, unknown>> = {},
) {
  cleanup()
  render(
    <Select defaultOpen>
      <SelectTrigger>SelectTrigger</SelectTrigger>
      <SelectContent>
        <SelectSeparator data-subject {...(props as ComponentProps<typeof SelectSeparator>)} />
      </SelectContent>
    </Select>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="select-separator"]')
}

function classesOfSelectSeparator(
  props: Partial<Record<keyof ComponentProps<typeof SelectSeparator>, unknown>> = {},
) {
  return renderSelectSeparator(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('SelectSeparator', () => {
  it('renders [data-slot="select-separator"] with its classes', () => {
    expect(classesOfSelectSeparator()).toEqual(expect.arrayContaining([styles.selectSeparator]))
  })

  it('appends a consumer className last', () => {
    renderSelectSeparator({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderSelectScrollUpButton(
  props: Partial<Record<keyof ComponentProps<typeof SelectScrollUpButton>, unknown>> = {},
) {
  cleanup()
  render(
    <Select defaultOpen>
      <SelectTrigger>SelectTrigger</SelectTrigger>
      <SelectContent>
        <SelectScrollUpButton
          data-subject
          {...({ keepMounted: true, ...props } as ComponentProps<typeof SelectScrollUpButton>)}
        />
      </SelectContent>
    </Select>,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="select-scroll-up-button"]')
}

function classesOfSelectScrollUpButton(
  props: Partial<Record<keyof ComponentProps<typeof SelectScrollUpButton>, unknown>> = {},
) {
  return renderSelectScrollUpButton(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('SelectScrollUpButton', () => {
  it('renders [data-slot="select-scroll-up-button"] with its classes', () => {
    expect(classesOfSelectScrollUpButton()).toEqual(
      expect.arrayContaining([styles.selectScrollUpButton]),
    )
  })

  it('appends a consumer className last', () => {
    renderSelectScrollUpButton({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

function renderSelectScrollDownButton(
  props: Partial<Record<keyof ComponentProps<typeof SelectScrollDownButton>, unknown>> = {},
) {
  cleanup()
  render(
    <Select defaultOpen>
      <SelectTrigger>SelectTrigger</SelectTrigger>
      <SelectContent>
        <SelectScrollDownButton
          data-subject
          {...({ keepMounted: true, ...props } as ComponentProps<typeof SelectScrollDownButton>)}
        />
      </SelectContent>
    </Select>,
  )
  return document
    .querySelector('[data-subject]')
    ?.closest('[data-slot="select-scroll-down-button"]')
}

function classesOfSelectScrollDownButton(
  props: Partial<Record<keyof ComponentProps<typeof SelectScrollDownButton>, unknown>> = {},
) {
  return renderSelectScrollDownButton(props)?.getAttribute('class')?.split(' ') ?? []
}

describe('SelectScrollDownButton', () => {
  it('renders [data-slot="select-scroll-down-button"] with its classes', () => {
    expect(classesOfSelectScrollDownButton()).toEqual(
      expect.arrayContaining([styles.selectScrollDownButton]),
    )
  })

  it('appends a consumer className last', () => {
    renderSelectScrollDownButton({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })
})

describe('re-exports', () => {
  it('re-exports Select from @base-ui\u002Freact\u002Fselect', () => {
    expect(Select).toBe(SelectPrimitive.Root)
  })
})
