// Generated by scripts/mirror from shadcn base-maia/slider. Do not edit.

import { cleanup, render } from '@testing-library/react'
import type { ComponentProps } from 'react'
import { afterEach, describe, expect, it } from 'vitest'
import { Slider } from './Slider'
import styles from './Slider.module.scss'

// React's useId output (_r_1_, and :r1: or «r1» before React 19.1), which
// differs between renders; Base UI puts it in ids and data-id.
const USE_ID = /_r_[0-9a-z]+_|:r[0-9a-z]+:|«r[0-9a-z]+»/g

afterEach(cleanup)

function renderSlider(props: Partial<Record<keyof ComponentProps<typeof Slider>, unknown>> = {}) {
  cleanup()
  render(
    <Slider
      data-subject
      {...({ defaultValue: 50, step: 1, ...props } as ComponentProps<typeof Slider>)}
    />,
  )
  return document.querySelector('[data-subject]')?.closest('[data-slot="slider"]')
}

function classesOfSlider(
  props: Partial<Record<keyof ComponentProps<typeof Slider>, unknown>> = {},
) {
  return renderSlider(props)?.getAttribute('class')?.split(' ') ?? []
}

function attributesOfSlider(
  props: Partial<Record<keyof ComponentProps<typeof Slider>, unknown>> = {},
) {
  const element = renderSlider(props)
  expect(element).toBeTruthy()
  return Object.fromEntries(
    [...(element?.attributes ?? [])].map((a) => [a.name, a.value.replace(USE_ID, '')]),
  )
}

describe('Slider', () => {
  it('renders [data-slot="slider"] with its classes', () => {
    expect(classesOfSlider()).toEqual(expect.arrayContaining([styles.slider]))
  })

  it('renders the same with min=0 passed explicitly', () => {
    expect(attributesOfSlider({ min: 0 })).toEqual(attributesOfSlider())
  })

  it('renders the same with max=100 passed explicitly', () => {
    expect(attributesOfSlider({ max: 100 })).toEqual(attributesOfSlider())
  })

  it('appends a consumer className last', () => {
    renderSlider({ className: 'consumer' })
    const element = document.querySelector('.consumer')
    expect(element?.getAttribute('class')?.split(' ').at(-1)).toBe('consumer')
  })

  it("renders as upstream's example uses it (2)", () => {
    cleanup()
    render(<Slider data-subject defaultValue={[25, 50]} max={100} step={5} />)
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (3)", () => {
    cleanup()
    render(<Slider data-subject defaultValue={[10, 20, 70]} max={100} step={10} />)
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (4)", () => {
    cleanup()
    render(<Slider data-subject defaultValue={[50]} max={100} step={1} orientation="vertical" />)
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (5)", () => {
    cleanup()
    render(<Slider data-subject defaultValue={[25]} max={100} step={1} orientation="vertical" />)
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (6)", () => {
    cleanup()
    render(<Slider data-subject id="slider-demo-temperature" min={0} max={1} step={0.1} />)
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })

  it("renders as upstream's example uses it (7)", () => {
    cleanup()
    render(<Slider data-subject defaultValue={[50]} max={100} step={1} />)
    expect(document.querySelector('[data-subject]')).not.toBeNull()
  })
})
